### ISSUE TITLE
Posibility to have backend drain via dataplane API

### ISSUE THREAD

**Issue by wizardmatas** [haproxytech/dataplaneapi#1]
Hello, HaProxy has backend server drain functionality, it would be great to have drain funkcionality via REST API. Is it possible to include it or get some guidance how to contribute to add it.

Thanks

**Comment by mjuraga** [comment]
We are planning to add an endpoint that would handle Runtime API (aka stats socket) commands, but for this purpose you can set the server weight to 0 through the Data Plane API and have the same effect: "A value of 0 means the server will not participate in load-balancing but will still accept persistent connections."

Note that changing the server weight will be done through the Runtime API and it will not reload haproxy process.

**Comment by wizardmatas** [comment]
Hi, that is great. Do you have any ETA for Runtime API support ?
Thanks,
Matas

**Comment by mjuraga** [comment]
Runtime API support is being worked on but we are not yet ready to announce an ETA for it. We are also collecting community feedback which might influence our roadmap.

**Comment by apsega** [comment]
@mjuraga any updates on this?

**Comment by aiharos** [comment]
> @mjuraga any updates on this?

@apsega  we're not yet ready to announce anything at this time. Perhaps you can tell us what aspect of the Runtime API you are interested in, to inform us better? If it's not related to draining backends, you can also open a new issue.

Thanks!

**Comment by mjuraga** [comment]
Hi @apsega @wizardmatas, I have just pushed a79a41935be1b8d7a8478e00c2528b3682baf7c8. This adds runtime_servers endpoints which allow you to change some runtime (transient) server properties. On GET we use this: https://cbonte.github.io/haproxy-dconv/2.0/management.html#show%20servers%20state

And then you can change the server admin (set server state) and operational (set server health) states. Here you can change each servers admin state to drain. So you can iterate through servers in the backend and set them to drain.
