### ISSUE TITLE
 ​POST /services​/haproxy​/configuration​/raw not working

### ISSUE THREAD

**Issue by HJesenovic** [haproxytech/dataplaneapi#10]
When I POST my raw configuration on `/services​/haproxy​/configuration​/raw` I get a 400 response code with the response body:

`{"code":400,"message":"20: Transaction file 2c9d7697-e4f6-46ad-b1dd-f3c87a87f03f does not exist"}`

**Comment by mjuraga** [comment]
Fixed with commit 2137267bf1a56745f5334eec53156c7637450550
