### ISSUE TITLE
servers: set server state says bad request

### ISSUE THREAD

**Issue by kashifmin** [haproxytech/dataplaneapi#100]
I'm trying to set server state for one of my service using dataplane api. 
```bash
curl -X PUT --user dataplaneapi:mypassword \
       -H "Content-Type: application/json" \
       http://localhost:5555/v2/services/haproxy/runtime/servers/my_service-1/\?backend\=my_service -d '{"admin_state":"drain","operation_state":"up"}'
```
But seems like HA proxy is throwing an error
```
{"code":500,"message":"/Users/kashif/haproxy.sock bad request"}
```
I've tried HAproxy v2.1.14 & also haproxy compiling from the master branch but no luck. Is this an issue with dataplane api? 

Dataplane api version: Compiled from master since I wanted the latest changes from `client-native`

**Comment by mjuraga** [comment]
Can you please share the configuration of the stats socket from the haproxy configuration file, and cli parameters you use for starting the dataplaneapi?

**Comment by kashifmin** [comment]
My HAProxy config:
```cfg
# _version=8

global 
  nbproc 1
  maxconn 4096
  stats socket /Users/kashif/haproxy.sock level admin expose-fd listeners
  stats socket /Users/kashif/haproxy_2.sock user kashif group staff mode 660 level admin
  stats timeout 30s
  log 127.0.0.1 local0
  log 127.0.0.1 local1 debug
  #log loghost    local0 info
  #chroot /usr/share/haproxy
  #daemon
  #debug
  #quiet

defaults 
  mode http
  maxconn 2000
  log global
  option httplog
  option redispatch
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000
  retries 3

userlist dataplane-api 
  user dataplaneapi insecure-password mypassword

frontend grpc-frontend 
  mode http
  bind *:80
  acl acl_myservice1: path_beg /service.MyService
  option forwardfor
  option httplog
  use_backend my_service if acl_myservice1:

backend my_service 
  server my_service-1 localhost:2211 proto h2 check

listen haproxy-monitoring 
  bind *:1936
  mode http
  stats enable
  stats hide-version
  stats realm Haproxy\ Statistics
  stats uri /
  stats auth developer:developer

```

Dataplane API start command:
```bash
./dataplaneapi --host localhost --port 5555 --haproxy-bin /usr/local/bin/haproxy --config-file /usr/local/etc/haproxy.cfg --reload-cmd "brew services restart haproxy" --reload-delay 5 --userlist dataplane-api
```

**Comment by mjuraga** [comment]
This is an issue cause you have two stats sockets defined and nbproc = 1.

To summarize how Runtime client is initialized here: https://github.com/haproxytech/dataplaneapi/blob/master/configure_data_plane.go#L603

If you are running a master socket we always use a master socket with the number of processes configured with nbproc, if there is no master socket configured (as in your case), we check if nbproc is 1, and if it is, we just take the first configured stats socket and use it here (in your case we use: `/Users/kashif/haproxy.sock` and it seems you don't have the permissions to read it). If `nbproc > 1` and no master socket then we look for all configured stats sockets with the `process` keyword to determine which stats socket can be used for accessing specific haproxy worker process.

**Comment by kashifmin** [comment]
@mjuraga 
I've removed the duplicate socket definition. But I was still getting the same error.
I did some debugging and found that there's a bug in `runtime_servers.go`. I have made a PR with the fix: https://github.com/haproxytech/dataplaneapi/pull/101/files

I can confirm it is working after this change.
```sh
curl -X PUT --user dataplaneapi:mypassword \
       -H "Content-Type: application/json" \
       http://localhost:5555/v2/services/haproxy/runtime/servers/my_service-1/\?backend\=my_service -d '{"admin_state":"drain"}'

{"address":"10.0.2.75","admin_state":"drain","id":"1","name":"my_service-1","operational_state":"down","port":80
```
