### ISSUE TITLE
what is "version"

### ISSUE THREAD

**Issue by baonq243** [haproxytech/dataplaneapi#102]
When I create a transaction ID also create a "version".
- This version managerment version of file config?
- Can I revert to the previous version when configuring file were errors?

**Comment by mjuraga** [comment]
Hi, version is the version of the configuration file, which we use for guarding against concurrent editing. When using dataplaneapi you will see the `# _version=1` at the top of the file. So if two users are editing a file and they GET and recieve a version 1, they make some changes and commit the transaction, the first to commit will succeed and the version will be incremented to 2. The second one commiting the transaction will fail in order not to overwrite the changes of the first user.

We currently keep backups of configuration file using `--backups-number` CLI option:

```
Number of backup configuration files you want to keep, stored in the config dir with version number suffix" default:"0"
```

But there is no API endpoint for reverting backups at this time.
