### ISSUE TITLE
Dataplaneapi  can not get servers info

### ISSUE THREAD

**Issue by hedong0411** [haproxytech/dataplaneapi#104]
I have used the haproxy-2.0.14 and the last version dataplaneapi.  I get this result, When I execute the following command:

`curl -X GET --user dataplaneapi:123456 
 http://localhost:5555/v2/services/haproxy/configuration/servers

{"code":602,"message":"backend in query is required"}`

Has anybody ever had this problem?

Haproxy config:
`global
        maxconn         10000
        stats socket    /var/run/haproxy.stat mode 600 level admin
        log             127.0.0.1 local0
        chroot          /var/empty
        nbproc 3
        user root
        group root
        stats socket /run/haproxy.sock

userlist hapee-dataplaneapi
        user dataplaneapi insecure-password 123456

 program api
        command dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /home/gaohd/open_source/haproxy/haproxy-2.0.14/haproxy --config-file /home/gaohd/open_source/haproxy/gaohd.cfg --log-level trace  --reload-cmd "systemctl reload haproxy" --reload-delay 5 --userlist hapee-dataplaneapi

frontend public
        bind            0.0.0.0:8080
        mode            http
        log             global
        option          httplog
        maxconn         8000
        timeout client  30s
        default_backend static

backend static
        mode            http
        balance         roundrobin
        retries         2
        timeout connect 5s
        timeout server  5s
        server          statsrv1 127.0.0.1:80 check inter 1000
        server          statsrv2 127.0.0.1:81 check inter 1000`

**Comment by mjuraga** [comment]
Hi, you need to add backend as a qs parameter, so something like this:

```
GET /v2/services/haproxy/configuration/servers?backend=static
```

**Comment by hedong0411** [comment]
It works！ Thank you very much mjuraga.
