### ISSUE TITLE
How to delete servers from backend?

### ISSUE THREAD

**Issue by hedong0411** [haproxytech/dataplaneapi#105]
I added server to backend with this command, But how can I delete it ?

`curl -X POST --user dataplaneapi:123456 -H "Content-Type: application/json" -d '{"name": "server1", "address": "192.168.0.108", "port": 82, "check": "enabled", "maxconn": 30, "weight": 100}' "http://localhost:5555/v2/services/haproxy/configuration/servers?backend=static&transaction_id=cfa4f272-1145-439b-9007-6d35b1704794"`

**Comment by mjuraga** [comment]
For deleting servers you can use the DELETE HTTP method on that server's resource:

```
DELETE /v2/services/haproxy/configuration/servers/server1?backend=static
```

**Comment by mjuraga** [comment]
For more information you can look here: https://www.haproxy.com/blog/programmatic-haproxy-configuration-using-the-data-plane-api/ about an intro how to use the dataplaneapi.

And our full docs are here: https://www.haproxy.com/documentation/hapee/1-9r1/configuration/dataplaneapi/

**Comment by hedong0411** [comment]
It works ！ Thank you very much mjuraga！
