### ISSUE TITLE
Setting the ID when adding a server to a backend

### ISSUE THREAD

**Issue by nachojimenez** [haproxytech/dataplaneapi#106]
We are trying to dynamically add servers to a backend, but while keeping consistency so the `hash_type consistent` algorithm keeps using the same servers. 

According to the haproxy documentation, the hash tables are based on the "ID" value of the server, but it looks like that value is not settable  through the dataplaneapi project. Am I missing someting?

**Comment by mjuraga** [comment]
No it is not settable via the dataplaneapi currently, you can check the server IDs by querying `/v2/services/haproxy/runtime/servers` endpoint.
