### ISSUE TITLE
Backend balance algorithms

### ISSUE THREAD

**Issue by bmarkovic** [haproxytech/dataplaneapi#11]
Hello,

Currently, according to the swagger schema and the `x-dependency` property of `Backend.balance.arguments`, only when `uri` and `uri_param` balance algorithms are chosen, it is possible to send additional arguments in the `arguments` array. For all other algorithms it's not possible to send additional arguments.

However, according to the [configuration documentation](https://www.haproxy.com/documentation/hapee/1-9r1/onepage/#balance) the following balance algorithms should also probably be included, and accept additional arguments:

- `random` - which accepts an integer, a number of draws for the consistent hashing function (the number of times a random server is selected before choosing the last loaded of those selected) and should render like this:
   ```haproxy
   balance random(3)
   ```

- `hdr` - this is not currently part of the Swagger schema, this algorithm accepts a header name as string parameter, and additional `use_domain_only` parameter and should get rendered as:
   ```haproxy
   balance hdr(HeaderName)
   balance hdr(HeaderName) use_domain_only
   ```
   it would probably be best if the first argument in the array is rendered inside the parenthesis;

- `rdp-cooke` - this algorithm is also not currently part of the Swagger schema, it accepts a name of the cookie for [RDP protocol](https://www.haproxy.com/blog/microsoft-remote-desktop-services-rds-load-balancing-and-protection/) and defaults to `mstshash` if not present, rendered as:
   ```haproxy
   balance rdp-cookie(somecookie)
   ```
   again, I'd propose that the first argument in the array is rendered inside the parenthesis.

I suppose these are used infrequently but it'd still be great to have all the possibilities of config file covered by the API.

**Comment by mjuraga** [comment]
We will add this to the roadmap.

**Comment by gitforbit** [comment]
Hi @bmarkovic 

We reworked balance implementation. We removed `arguments` field and instead of it, we added support for all missing options denoted with `x-dependency`.
