### ISSUE TITLE
maps files uploaded via /maps/ endpoint is not propagated to /maps_entries/

### ISSUE THREAD

**Issue by nvarscar** [haproxytech/dataplaneapi#113]
## Setup
A map file is uploaded via 
```
DELETE /services/haproxy/runtime/maps/mapname?forceDelete=true
POST /services/haproxy/runtime/maps with files={"fileUpload": ("mapname", <content>)} 
```
The file appears on the disk drive as it should and contains all the maps from file mapname
## Problem
The following request
```
GET /services/haproxy/runtime/maps_entries?map=mapname
```
Does not return any entries once the maps are uploaded.
Moreover, if anything POSTS a new entry via
```
POST /services/haproxy/runtime/map_entries?map=mapname
```
once the flush occurs, the uploaded file contents are erased and will now contain only a single entry from the `/map_entries/` POST.

**Comment by mjuraga** [comment]
This is a bug, we can confirm it and we will work on it.

**Comment by gitforbit** [comment]
Hi @nvarscar,

Fixed with https://github.com/haproxytech/dataplaneapi/commit/4025d3e5c62e76056bac353b21bc16f0c2376709. 
We added `force_reload` parameter for POST. It can be used to immediately update HAProxy with new entries. Hopefully it works for you.

**Comment by aiharos** [comment]
If you find the issue persists we will reopen the issue.
