### ISSUE TITLE
The HAProxy config file is occasionally truncated

### ISSUE THREAD

**Issue by akutz** [haproxytech/dataplaneapi#114]
We have noticed that on rare occasions the HAProxy config file (`/etc/haproxy/haproxy.cfg`) is truncated. I suppose this could be something occurring as a result of HAProxy, but I believe it is a potential bug in the Data Plane API's `copyFile` function: https://github.com/haproxytech/dataplaneapi/blob/f2a732aff1d0d65c869691972c935b89f4cec0c8/haproxy/reload_agent.go#L370-L388

Since Golang's stdlib `os.Create` call truncates an existing file, if an error occurs between truncating the destination and with the actual copy, a file with existing content could be truncated by the Data Plane API's `copyFile` function.

We will update this ticket to include logs if we are able to reproduce this again. Thanks!

**Comment by mjuraga** [comment]
Thanks for the report, we are aware of this and working on a fix.

**Comment by akutz** [comment]
Thanks @mjuraga! To satisfy my own curiosity, is the truncation related to the above code, or something else?

**Comment by akutz** [comment]
@mjuraga We're going to test the above patch internally. It should at least help identify whether the described problem is the root cause.

**Comment by mjuraga** [comment]
Hi @akutz, we currently have a fix for this ourselves in the client-native package: https://github.com/haproxytech/client-native/commit/db0e04f2da808bd217889c8869acd5d0ba885fe2 and https://github.com/haproxytech/client-native/commit/d959aecfb0d0e2fa737abf69aa563c91270ecd5e.

Also we changed the way we are writing files in our config-parser: https://github.com/haproxytech/config-parser/commit/9e0567637fff16963493ef1bc989ab7d334cee6c

Hopefully all those changes mitigate the issue you are having. All of the changes will soon land in the dataplaneapi project, as we currently have a couple of features in the pipeline waiting for a new commit here, but you can test by building the dataplaneapi with the above commits from client-native and config-parser packages and see if the issue still persists.

**Comment by akutz** [comment]
Hi @mjuraga,

Thank you! So, something interesting, both of our patches use `os.Rename` to facilitate a move op instead of copy. I have not tried compiling with your patches, but with the patch I created in the linked PR, my colleague is seeing the following error:

```log
al msg="Cannot initialize reload agent: rename /tmp/426561979 /etc/haproxy/haproxy.cfg.lkg: invalid cross-device link"
```

Based on your patch, https://github.com/haproxytech/client-native/commit/db0e04f2da808bd217889c8869acd5d0ba885fe2#diff-26af34f6109c65b82c09ff1ab815d32dR498-R500 *could* fail if the source and destination files are on different filesystems. 

I updated our patch to avoid this issue - https://github.com/haproxytech/dataplaneapi/pull/115/files#diff-7bee23633a9d529297272f5aa9dcba49R384-R388.

While it is likely you're not moving files from a `tmpfs` filesystem, you *could* potentially be moving files across filesystems depending on how people partition their hosts where HAProxy and the DP API are running.

**Comment by akutz** [comment]
Hi @mjuraga,

I am running with your patched binary now to see if we can reproduce the issue any longer. On that note, do you know how to consistently reproduce it? It would be helpful if we could do so deterministically in order to use that process to validate the patch is successful. Thanks!

**Comment by mjuraga** [comment]
Hi @akutz,

we haven't found an exact case to reproduce your issue, but we identified that we can make our source-code more robust when dealing with files. Now the client-native does not write files at all, only case when we rename is when transaction fails, and that is renaming to a subdirectory of the transaction dir. All the other cases, the client-native just dumps the in-memory parser for that transaction to a file, using config-parser's Save method which uses https://github.com/google/renameio.

In the latest patch, we also changed the default transaction directory from `/tmp` as we identified that this is not the best solution for the only reason why we are dumping transactions to disk and that is persistence. The new default is `/etc/haproxy/transactions` as we find it more transparent, persistent, and hopefully avoids possible errors when dealing with files across filesystems.

**Comment by akutz** [comment]
Hi @mjuraga,

Unless I am missing something, it looks like your commit https://github.com/haproxytech/dataplaneapi/commit/c1aaee75dc32b433288cf5999394337b2e54551a should fix this issue. Do you plan to tag a release soon?

**Comment by mjuraga** [comment]
Yes, we are planning a release soon. Can you confirm that this commit solves the issue for you?

**Comment by akutz** [comment]
Hi @mjuraga,

Yes, it does fix it. I also validated https://github.com/haproxytech/dataplaneapi/commit/2b0d5822b330579fdc5cc6e3f533f59b8b5a3428.
