### ISSUE TITLE
The API does not seem to work with "listen" groups in haproxy.cfg

### ISSUE THREAD

**Issue by davesargrad** [haproxytech/dataplaneapi#116]
I am using HAPROXY for TCP-only traffic. I need to dynamically update the haproxy configuration.

I dont have frontends and backends. Rather I have listen. From the [HAProxy Configuration documentation](https://www.haproxy.org/download/2.2/doc/configuration.txt).
![image](https://user-images.githubusercontent.com/48793689/86372891-cbc03b80-bc50-11ea-8905-89bdb2d35702.png)

So what portion of the dataplaneapi API provides access to CRUD operations on listen?

**Comment by mjuraga** [comment]
Hi, the dataplaneapi does not support `listen` section, as listen is just a frontend and backend merged into one section. As a workaround you can split your section into `frontend` and `backend` using `default_backend` directive to connect them, and split the directives between them.

**Comment by davesargrad** [comment]
Hi. Thanks. I did figure this out, and what you describe is adequate for my purposes.
