### ISSUE TITLE
configuring acl

### ISSUE THREAD

**Issue by abhimanyunagrath** [haproxytech/dataplaneapi#118]
Hi , 

I have a acl defined as : 
`acl badips src -f /etc/haproxy/bad_ip.txt` 

that reads and block ips from a file.

Now I am using dataplane API to add IPs to the file bad_ip.txt

`curl -X POST --user admin:test -H "Content-Type: application/json" -d '{"acl_file":"/etc/haproxy/test.txt","id": 0, "cond": "if", "cond_test": "{ src 192.168.50.20 }", "type": "deny", "index" : 0}' "http://localhost:5555/v2/services/haproxy/configuration/http_request_rules?parent_type=frontend&parent_name=tracxn-http&version=24"
`
But this is not working . Please let me know how to do it.

**Comment by mjuraga** [comment]
The dataplaneapi does not manage acl files, you will have to populate the acl file yourself. The `http_requet_rules` endpoint has CRUD operations for `http-request` directives in the haproxy configuration file.

Please check our specification for more details: https://www.haproxy.com/documentation/hapee/1-9r1/configuration/dataplaneapi/
