### ISSUE TITLE
Error Code 400, Message Code 14 On Transaction Commit 

### ISSUE THREAD

**Issue by davesargrad** [haproxytech/dataplaneapi#119]
### Provided Dataplane API Example Fails
I am trying to build a transactional interface to the api.. I'm in a dev mode.  I am following [this ](https://www.haproxy.com/blog/new-haproxy-data-plane-api/) documentation. I'm trying to follow a portion of the example exactly, (the portion that adds a frontend). 

### Lack of Documentation on Code 400, Message 14 
I'm seeing an error when I commit my transaction, depsite the fact that the posts to create a frontend and add a bind succeed. On the final commit I get a code 400, message 14. I am trying to figure out why

Here, in debugger,  we see 4 underlined interactions with the API. The first 3 are fine: Start Transaction, Create Frontend (202), Add Bind (202), Commit Transaction (400)

![image](https://user-images.githubusercontent.com/48793689/87150125-81a60e00-c27f-11ea-9702-fbdcd292e7f9.png)

### Repeatable with Example Code Provided on DATAPLANEAPI Documentation Page
I've also included a snippet of code in comment below, that shows how to replicate this with the dataplaneapi  [documented example](https://www.haproxy.com/blog/new-haproxy-data-plane-api/).

This problem seems perfectly repeatable. I've developed a simple script as follows:

I start by exporting trans_id (in the following start a transaction - assuming version 1)
`curl -X POST -H "Content-Type: application/json" --user dataplaneapi:abc123 "http://127.0.0.1:5555/v2/services/haproxy/transactions?version=1"`

```
export trans_id=CHANGEME
export pw=CHANGEME
```

 ```
curl -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/configuration/backends?transaction_id=$trans_id" -d '{"name": "test_backend", "mode":"http", "balance": {"algorithm":"roundrobin"}, "httpchk": {"method": "HEAD", "uri": "/", "version": "HTTP/1.1"}}' -X POST

curl -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/configuration/servers?backend=test_backend&transaction_id=$trans_id" -d '{"name": "server1", "address": "127.0.0.1", "port": 8080, "check": "enabled", "maxconn": 30, "weight": 100}' -X POST

 curl -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/configuration/frontends?transaction_id=$trans_id" -d '{"name": "test_frontend", "mode": "http", "default_backend": "test_backend", "maxconn": 2000}' -X POST

curl -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/configuration/binds?frontend=test_frontend&transaction_id=$trans_id" -d '{"name": "http", "address": "*", "port": 80}' -X POST

curl -X PUT -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/transactions/$trans_id"
```

When I try to commit my transactions, I get the following response.
{"code":400,"message":"14: ERR transactionId=774...  "}

Despite the fact that the transactonid was valid and in progress.

I've been digging through the dataplaneapi codebase to try to isolate this problem: so far to no avail.

### Looking online for clues

[This ](https://github.com/haproxytech/dataplaneapi/issues/23)issue seems related. It references the same kind of cryptic message "14 ERR...". However my posts work, the only thing that doesnt work is my commit. Also I just checked my command line, and I am pointing to a proper haproxy binary.

![image](https://user-images.githubusercontent.com/48793689/87155773-8ff92780-c289-11ea-99d5-fac16874ef55.png)

### DataPlaneAPI Version
I am using version 2.0.3
![image](https://user-images.githubusercontent.com/48793689/87154396-27a94680-c287-11ea-83eb-7092deb3fccf.png)

**Comment by davesargrad** [comment]
I figured out I can delete the /tmp/haproxy transaction directory.. So I just have the one question about message 14

**Comment by davesargrad** [comment]
This problem seems perfectly repeatable. I've developed a simple script as follows:

I start by exporting trans_id (in the following start a transaction - assuming version 1)
`curl -X POST -H "Content-Type: application/json" --user dataplaneapi:abc123 "http://127.0.0.1:5555/v2/services/haproxy/transactions?version=1"`

```
export trans_id=CHANGEME
export pw=CHANGEME
```

 ```
curl -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/configuration/backends?transaction_id=$trans_id" -d '{"name": "test_backend", "mode":"http", "balance": {"algorithm":"roundrobin"}, "httpchk": {"method": "HEAD", "uri": "/", "version": "HTTP/1.1"}}' -X POST


curl -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/configuration/servers?backend=test_backend&transaction_id=$trans_id" -d '{"name": "server1", "address": "127.0.0.1", "port": 8080, "check": "enabled", "maxconn": 30, "weight": 100}' -X POST


 curl -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/configuration/frontends?transaction_id=$trans_id" -d '{"name": "test_frontend", "mode": "http", "default_backend": "test_backend", "maxconn": 2000}' -X POST

curl -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/configuration/binds?frontend=test_frontend&transaction_id=$trans_id" -d '{"name": "http", "address": "*", "port": 80}' -X POST

curl -X PUT -H "Content-Type: application/json" --user dataplaneapi:$pw "http://127.0.0.1:5555/v2/services/haproxy/transactions/$trans_id"
```

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/87144135-4868a080-c275-11ea-8e6e-5855ec98a7a5.png)

**Comment by davesargrad** [comment]
Hi @oktalz 
I'd very much appreciate if you could take a look at this issue. If you can provide guidance, I'd be glad to dig a bit to help isolate this.

**Comment by mjuraga** [comment]
I'll take a look at this, thank you for your extensive report. Can you please try building dataplaneapi with the latest commit in the master to see if the problem still persists in the meantime?

**Comment by mjuraga** [comment]
Can you just share the version of the haproxy you are running,

`/usr/sbin/haproxy -vv` in your case

**Comment by davesargrad** [comment]
Hi. 

I built and ran dataplaneapi in the debugger. 

I've isolated the problem in dlv.

![image](https://user-images.githubusercontent.com/48793689/87162302-bcb23c80-c293-11ea-98c1-18239a4fbbca.png)

**Comment by davesargrad** [comment]
I am using version 1.5.18

![image](https://user-images.githubusercontent.com/48793689/87162368-d489c080-c293-11ea-844a-1ac71873efde.png)

**Comment by davesargrad** [comment]
The file being checked.. when the error occurs.. seems to be just fine
![image](https://user-images.githubusercontent.com/48793689/87162759-5f6abb00-c294-11ea-9408-18b55b9a34c0.png)

**Comment by davesargrad** [comment]
@mjuraga Thanks so much for your fast response to this. I'm glad to help you isolate. I'll dig in debugger further.

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/87164232-888c4b00-c296-11ea-98d8-0fbf7df0d153.png)

**Comment by davesargrad** [comment]
Digging further .. it seems that its an problem with how the haproxy commandline is being invoked.. which could (to your point) tie to haproxy version

![image](https://user-images.githubusercontent.com/48793689/87164707-1700cc80-c297-11ea-9a57-2e4402f7a36f.png)

**Comment by davesargrad** [comment]
Looks like I'm using haproxy that is bundled with centos 7. Perhaps I need to build or download a later version.. It would be nice if the dataplaneapi does a check of the haproxy version.. and reports a mismatch.

**Comment by davesargrad** [comment]
I've installed 2.2.0 using [these ](https://upcloud.com/community/tutorials/haproxy-load-balancer-centos/)instructions ... 

![image](https://user-images.githubusercontent.com/48793689/87167496-0e11fa00-c29b-11ea-8d89-64beadb837be.png)

I'm about to configure and test with the api

**Comment by davesargrad** [comment]
That worked!!!

![image](https://user-images.githubusercontent.com/48793689/87167880-a9a36a80-c29b-11ea-8059-629947afadcb.png)

**Comment by davesargrad** [comment]
My suggestion on closing this issue... Please update the dataplaneapi so that it does a version check, and so that it provides a more proper error message on a dependency mismatch..

Thanks very much for pointing me in the right direction.

**Comment by davesargrad** [comment]
One issue I still see is the following reload failure

![image](https://user-images.githubusercontent.com/48793689/87176222-ce9dda80-c2a7-11ea-9aba-e9675018b321.png)

**Comment by davesargrad** [comment]
I'll close this issue, and write a separate issue on that failure.

**Comment by vandrovisky** [comment]
I need help, I'm using dataplaneapi version 2.7.2 and haproxy version 2.7
still the error persists. Anything else that can be done?
![Captura de tela de 2023-02-17 15-20-14](https://user-images.githubusercontent.com/88595552/219748651-b097391a-b8e5-48da-ba78-6c7892b15334.png)

**Comment by jameswest368** [comment]
Same here haproxy 2.7.4 and dataplane 2.7.3 don't work together and give this rather vague ` 14: err transactionid=...`

The resultant config file ( from` /tmp/haproxy/failed/haproxy.cfg.<transactionId>` ) is valid according to `haproxy -c -f <filename>`

Using haproxy 2.6..10 seems to work fine

I didn't see anything that said 2.7 wasn't supported - did I miss something ?

**Comment by mjuraga** [comment]
@vandrovisky it seems you managed to segfault HAProxy itself, so HAProxy process crashed, you should investigate why HAProxy crashes with that configuration.

@jameswest368 can you check this comment: https://github.com/haproxytech/dataplaneapi/issues/297#issuecomment-1476139686

We should definitely improve error reporting in those cases.

**Comment by bernielomax** [comment]
I am experiencing the same issue running `haproxytech/haproxy-alpine` 2.7 & 2.8. @jameswest368  is correct. The issue goes away when running 2.6.10. FYI the API does not work out of the box when following the [Enable Data Plane API](https://hub.docker.com/r/haproxytech/haproxy-alpine) instructions. It seems https://github.com/haproxytech/dataplaneapi/pull/294 is getting in the way as well. Is this API considered production ready or should we be holding off?

**Comment by josephkeiser** [comment]
@bernielomax I started a new issue for the incompatibility: #297

**Comment by mjuraga** [comment]
@bernielomax let's continue the conversation in #297
