### ISSUE TITLE
HAProxy service fails on restart by dataplaneapi

### ISSUE THREAD

**Issue by davesargrad** [haproxytech/dataplaneapi#120]
After haproxy is restarted by dataplaneapi it fails to start. 
![image](https://user-images.githubusercontent.com/48793689/87300575-11e08f00-c4dc-11ea-878d-7bd6993f8318.png)

I am able to start it manually however.

I run dataplaneapi in this way:
`dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "service haproxy reload" --restar t-cmd "service haproxy restart"  --reload-delay 5 --userlist dataplaneapi --log-level trace --log-to file`

I am using the haproxy [sample ](https://github.com/haproxy/haproxy/blob/master/examples/haproxy.init)haproxy.init

I tried to comment out line 26 since that seemed to cause a problem.
`[ ${NETWORKING} = "no" ] && exit 0`

![image](https://user-images.githubusercontent.com/48793689/87301193-21140c80-c4dd-11ea-9448-225e7b0d3904.png)

Once I restart haproxy manually, it stays up and running with the configuration file provided by dataplaneapi. In the following its been up for 13 minutes.

![image](https://user-images.githubusercontent.com/48793689/87301663-fd9d9180-c4dd-11ea-8efd-f1e8ce9b48cf.png)

Why does haproxy fail when it is restarted by dataplaneapi?

I've better characterized the problem. HAProxy does eventually restart properly when dataplaneapi kills it. The real problem is it seems to take longer than I expected, which would mean that services are unavailable for the 30 seconds when HAProxy is restarting.

Is there a way to configure dataplaneapi to simply have haproxy reload its configuration, rather than to kill haproxy and restart it?  (Apparently [others ](https://discourse.haproxy.org/t/dataplane-api-simple-reload-command/5259)have seen related shortcomings).

**Comment by gitforbit** [comment]
Hi,
You have a typo in dataplaneapi command. `--restar t-cmd` should be `--restart-cmd`
