### ISSUE TITLE
Doc in dockerhub is confuse to new users

### ISSUE THREAD

**Issue by felixPG** [haproxytech/dataplaneapi#126]
Hi Team!!!

In your dockerhub image (https://hub.docker.com/r/haproxytech/haproxy-debian) the section of dataplane api configuration is wrong:

``` userlist haproxy-dataplaneapi
    user admin insecure-password mypassword

program api
   command /usr/bin/dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "kill -SIGUSR2 1" --reload-delay 5 --userlist hapee-dataplaneapi
   no option start-on-reload
```

 In the doc are defined a userlist as name **haproxy-dataplaneapi** but in command you use --userlist **hapee-dataplaneapi** is wrong, need to be the defined userlist **haproxy-dataplaneapi**

Also in the docker run section:

```
docker run -d --name my-running-haproxy --expose 5555 -v /path/to/etc/haproxy:/usr/local/etc/haproxy:rw haproxytech/haproxy-debian
```

...you specify a volume targeting **/usr/local/etc/haproxy** but in the configuration the haproxy.cfg is in **/etc/haproxy/haproxy.cfg**

Please, does anybody could rewrite this part in the dockerhub doc?

**Comment by dkorunic** [comment]
Thanks @felixPG for reporting, I'll handle it.

**Comment by dkorunic** [comment]
I have revisited this issue and I wanted to clarify the second issue, with supposed problem in regards to `/etc/haproxy` vs `/usr/local/etc/haproxy`. HAProxy is installed as per Unix/Linux hierarchy standards into `/usr/local` prefix. Main configuration location is (as per above) in `/usr/local/etc/haproxy` and main configuration file is typically `/usr/local/etc/haproxy/haproxy.cfg`. We use `/etc/haproxy` just as a symlink to `/usr/local/etc/haproxy`, as observable in the [Dockerfile](https://github.com/haproxytech/haproxy-docker-debian/blob/14e0c4bbf826dbf568ce76c33d1f8aeec1ac8b90/2.3/Dockerfile#L42).

So in this regard it is expected that the bind mount / exposed volume goes into `/usr/local/etc/haproxy` and not `/etc/haproxy` (which is actually just a symlink).

**Comment by dkorunic** [comment]
First issue (userlist naming) resolved in Alpine/Debian/Ubuntu README files.
