### ISSUE TITLE
Not able to add pgsql-check to backends

### ISSUE THREAD

**Issue by adarshprakash** [haproxytech/dataplaneapi#129]
Hi, I was trying to add a new backend with pgsql-check. But there is no provision to add argument 'user' (which is necessary for pgsql-check). If I try to add this without user I am getting response, 

> {'code': 500, 'message': 'invalid data'}

So I thought of moving pgsql-check to default section to avoid adding checks to each backend. But then error occurs like

> {'code': 400, 'message': '14: ERR transactionId=b24c72a5-6f53-49ae-b6f8-be932c77b6d6 \nline=21 msg="\'option pgsql-check\' expects \'user <username>\' as argument."'}

My haproxy config and python script used for adding backend are given below.

```
# _version=20

global 
  daemon
  chroot /var/lib/haproxy
  user haproxy
  group haproxy
  master-worker
  stats socket ipv4@127.0.0.1:9999 level admin
  stats socket /var/run/haproxy.sock user haproxy group haproxy mode 666 level admin
  stats timeout 2m
  log /dev/log local0
  log /dev/log local1 notice

defaults 
  mode tcp
  balance roundrobin
  log global
  option tcplog
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000
  default-server inter 1s downinter 1s rise 2 fall 1
  option  pgsql-check user haproxy

userlist controller 
  user haproxy insecure-password mypassword

frontend frontend1 
  bind distdb_ro:8001
  default_backend backend1

frontend frontend2 
  bind distdb_rw:8002
  default_backend backend2

backend backend1 
  option pgsql-check user haproxy
  server node1 localhost:9001 check

backend backend2 
  option pgsql-check user haproxy
  server node1 localhost:9002 check

listen stats 
  mode http
  bind :32700
  stats enable
  stats refresh 60s
  stats uri /
  stats hide-version
  stats auth someuser:password

program api 
  command dataplaneapi --host 127.0.0.1 --port 5555 --config-file /home/local/adarsh/currently_working/haproxy_apis/haproxy.cfg --reload-cmd "systemctl reload haproxy" --reload-delay 5
  no option start-on-reload
```

python script
```
#!/usr/bin/python

import sys
import requests
     
dataplane_url = "http://localhost:5555/v2/services/haproxy"
auth_str = ('haproxy', 'mypassword')

def start_transaction():
    r1 = requests.post(f'{dataplane_url}/transactions', params={'version': 20}, auth=auth_str)

    return r1.json()["id"]

def commit_transaction(id):
    r1 = requests.put(f'{dataplane_url}/transactions/{id}', auth=auth_str)
    print(r1.json())

def add_backend():
    backend_obj = {
        'name': 'backend9'
    }
    transaction_id = start_transaction()
    r = requests.post(
        f'{dataplane_url}/configuration/backends', params={'transaction_id': transaction_id}, auth=auth_str, json=backend_obj
    )
    print(r.json())

    commit_transaction(transaction_id)

add_backend()
```

Out of the context question : Is it possible to retrieve the current configuration version somehow? Currently I am hardcoding it inside my script.

**Comment by adarshprakash** [comment]
Sometimes getting another error after adding pgsql-check. 

> {"code":500,"message":"interface conversion: common.ParserData is *types.OptionPgsqlCheck, not *types.SimpleOption: /home/local/ZOHOCORP/adarsh-7270/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.0/configuration/configuration.go:625 parseField"}

**Comment by adarshprakash** [comment]
Sometimes getting another error when calling GET on '**configuration/backends**' (with pgsql-check enabled).

>     {"code":500,"message":"interface conversion: common.ParserData is *types.OptionPgsqlCheck, not *types.SimpleOption: /home/local/adarsh/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.0/configuration/configuration.go:625 parseField"}

**Comment by adarshprakash** [comment]
> Sometimes getting another error while calling GET on '**configuration/backends**' (with pgsql-check enabled).
> 
> > ```
> > {"code":500,"message":"interface conversion: common.ParserData is *types.OptionPgsqlCheck, not *types.SimpleOption: /home/local/adarsh/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.0/configuration/configuration.go:625 parseField"}
> > ```

This problem had something to do with `getDefaultParser` in `section-parsers.go` in **config-parser repo**. I have raised a pull request there.

**Comment by oktalz** [comment]
this was indeed error in config-parser.

**Comment by aiharos** [comment]
Should be fixed in master
