### ISSUE TITLE
Dataplaneapi doesn't respect its own --config-file param

### ISSUE THREAD

**Issue by PavelPikat** [haproxytech/dataplaneapi#131]
I have 2 config files, `haproxy.cfg` with defaults, and `dataplaneapi.cfg` with frontend.
Content of `haproxy.cfg`:
```
defaults
    log     global
program dataplaneapi
    command /usr/local/bin/build/dataplaneapi  --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/conf.d/dataplaneapi.cfg --reload-cmd "systemctl reload haproxy"
```

Content of `dataplaneapi.cfg`:
```
frontend main_fe
    mode http
    bind *:80
```

When I query dataplaneapi (`v2/services/haproxy/configuration/frontends`), I don't get any frontends.
When I query defaults (`v2/services/haproxy/configuration/defaults`), I get the content of `haproxy.cfg`

I would expect that dataplaneapi actually works with the config file that is passed to it via `--config-file` parameter.

My HAProxy service configuration has the following default:
```
CONFIG="/etc/haproxy/conf.d/haproxy.cfg"

EXTRAOPTS="-f /etc/haproxy/conf.d/dataplaneapi.cfg"
```

**Comment by aiharos** [comment]
Hi @PavelPikat ,

Can you let us know the distribution & version you are running, as well as the dataplane and haproxy versions?

**Comment by PavelPikat** [comment]
I am using Ubuntu 18.04 with HAProxy 2.2 and Dataplaneapi 2.1.0

**Comment by aiharos** [comment]
As of 224a5883a4825d4f87c4e3d38cbce4e5f7ecb700 we should no longer be overriding the config file specified on the commandline option to dataplane with the first config file in use by haproxy.
