### ISSUE TITLE
Add more than one server to a backend

### ISSUE THREAD

**Issue by felixPG** [haproxytech/dataplaneapi#133]
I need to add more than one server in one API call.  Something like this JSON, but the object *servers* does not exist in the API, following your docs:  https://www.haproxy.com/documentation/dataplaneapi/latest/#operation/createServer

```
{
  "servers": [
    {
      "address": "127.0.0.1",
      "check": "enabled",
      "max-connections": 500,
      "name": "server8",
      "port": 8088,
      "weight": 80
    },
    {
      "address": "127.0.0.1",
      "check": "enabled",
      "max-connections": 500,
      "name": "server9",
      "port": 8089,
      "weight": 80
    }
  ]
}
```
The above JSON rise me an error from the API

```
{"code":602,"message":"name in body is required"}
```

So, How can I add more than one servers instead of add one at a time?

**Comment by aiharos** [comment]
Hi @felixPG

You should start a new transaction, do any and all changes you want to have applied atomically and then commit.

https://www.haproxy.com/documentation/dataplaneapi/latest/#operation/startTransaction

**Comment by felixPG** [comment]
Thanks for your reply @aiharos .I know the process:

```
1. Get version
2. Start a transaction
3. Make changes to config
4. Commit the transaction
```
But in the process to add a backend to the server you need to add one by one, example:

```
curl -X POST --user admin:mypassword \
-H "Content-Type: application/json" \
-d '{"name": "server1", "address": "127.0.0.1", "port": 8080, "check": "enabled", "maxconn": 30, "weight": 100}' \
"http://localhost:5555/v2/services/haproxy/configuration/servers?backend=test_backend&transaction_id=b9a0ecd7-b8ae-4ef8-8865-0cd5e38396cd"
```
The problem is that I dont want to repeat the POST for every servers that I want to add to a backend (even as part of the same transaction).

**Comment by aiharos** [comment]
Another option would be to edit the 'sites' resource for the associated frontend/backend https://www.haproxy.com/documentation/dataplaneapi/latest/#operation/replaceSite

Right now we don't support replacing the entire list of servers directly on the servers resource, but we are open to discuss adding this in the future if there is enough interest in this feature.

**Comment by felixPG** [comment]
Well, site is a "workaround" @aiharos. Thanks for the tip, but Im interesting in the feature that I mentioned. How many adepts :-) the feature need to get to implement it?

**Comment by aiharos** [comment]
We've added it to our "nice-to-have" list. if more people ask for something like this we'll reprioritize to start working on it sooner. Of course, if you're open to contributing we'll gladly discuss PRs!

**Comment by felixPG** [comment]
Nice @aiharos. I was asking because I develop a kubernetes controller to create ha_proxy configurations dynamically from NodePort k8s services https://github.com/felix-dpg/harporias
