### ISSUE TITLE
Cannot set TLS properly

### ISSUE THREAD

**Issue by uMtMu** [haproxytech/dataplaneapi#134]
Hi, i am trying to set TLS, i tried like below.

```
dataplaneapi --scheme https --tls-host 0.0.0.0 --tls-port 5555 --tls-certificate server/server-cert.pem --tls-key server/server-key.pem --tls-ca ca/ca-cert.pem -b /usr/sbin/haproxy -c /etc/haproxy/haproxy.cfg  -d 5 -r "service haproxy reload" -s "service haproxy restart" --userlist dataplane-api -t /tmp/haproxy
```

and my keys created like below in same machine

```
mkdir ca server
cd ca
openssl genrsa 2048 > ca-key.pem
openssl req -new -x509 -nodes -days 730 -key ca-key.pem -out ca-cert.pem # CN=127.0.0.1
cd ../server
openssl req -newkey rsa:2048 -days 730 -nodes -keyout server-key.pem -out server-req.pem # CN=127.0.0.1
openssl x509 -req -in server-req.pem -days 730 -CA ../ca/ca-cert.pem -CAkey ../ca/ca-key.pem  -set_serial 01 -out server-cert.pem
```

Browser says "Error code: SEC_ERROR_UNKNOWN_ISSUER", i guess this means you signed yourself, i don't know you. I accept and continue. This time dataplaneapi says "tls: client didn't provide a certificate".

What is the missing part?

**Comment by aiharos** [comment]
Setting the --tls-ca option enables client certificate validation (mTLS, where the client, i.e. browser also has to present it's own SSL certificate signed by the same/trusted Certificate Authority), just removing the --tls-ca option should be enough for configuring self-signed SSL for just dataplane.
