### ISSUE TITLE
DPAPI should return 404 instead of 400 for missing configs

### ISSUE THREAD

**Issue by brakthehack** [haproxytech/dataplaneapi#135]
### Observed

When querying backend switching rules with a missing configuration we receive 400 (Bad Request)
```
root@423683236af094ddc6f0341afdc25de3 [ ~ ]# curl -u 'wcp:vmware' -k https://$haproxy_ip:5556/v2/services/haproxy/configuration/backend_switching_rules?frontend=sharedcluster-1600449883/sharedcluster-2dae24fd-a6c70d8d12ac9441f633b
{"code":400,"message":"11: frontend sharedcluster-1600449883/sharedcluster-2dae24fd-a6c70d8d12ac9441f633b does not exist"}
```

### Expected

I would expect us to return 404 or even 410.

### Commentary

From MDN:

> The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Given the client didn't make a malformed request or other client side error, I don't think 400 is ever appropriate here. We have a valid request, and until the request is made, it's not on the client to reason about the availability of the resource until it asks the server.

**Comment by aiharos** [comment]
The team had a lengthy discussion about this. In the end, we concluded that filtering for entries that do not exist should return an empty array and 200, but trying to create an entry with an invalid parent should stay 400. The request consists of both the body and url and query parameters, and in that case the "deceptive request routing" fits well. 

The improved behavior has been implemented with 382bf4313b4207c9e9f0fadf42b5c39f867aa9cd
