### ISSUE TITLE
Support for monitor-uri and monitor-fail

### ISSUE THREAD

**Issue by ngroupp** [haproxytech/dataplaneapi#138]
The Data Plane API (DPA) appears to support neither the 'monitor-uri' nor 'monitor-fail' parameters. These are commonly used to integrate with upstream services for cross-region failover or monitoring (e.g. Cedexis, Pingdom). While the monitor-uri parameter can be added to a defaults section managed outside of the DPA, the monitor-fail parameter cannot. This prevents the use of common, well documented configurations such as:

```HAProxy
 frontend www
        mode http
        acl site_dead nbsrv(dynamic) lt 2
        acl site_dead nbsrv(static)  lt 2
        monitor-uri   /site_alive
        monitor fail  if site_dead

```
Please add support or provide guidance around automating this use-case with the DPA.

**Comment by prometherion** [comment]
The Feature is addressed by the latest commits, especially b74c1c4297f1f9cd6667eae3b04597de6b7daff6
