### ISSUE TITLE
not able to set "timeout tunnel <timeout>" in backend using  AddBackend call

### ISSUE THREAD

**Issue by sigmonsays** [haproxytech/dataplaneapi#140]
The "Add a backend" API call at https://www.haproxy.com/documentation/dataplaneapi/latest/#operation/createBackend does not allow me eto set tunnel timeout.

It does however have the other timeout options such as server and queue.

**Comment by mjuraga** [comment]
Hi @sigmonsays, I don't seem to be having that issue locally, can you share the dataplaneapi and haproxy versions? And also the call you are using to create a backend that fails setting the tunnel timeout?
