### ISSUE TITLE
http-check expect status 200 in backend causes panic

### ISSUE THREAD

**Issue by sigmonsays** [haproxytech/dataplaneapi#144]
http-check expect status 200 in backend causes panic when attempting to list the backend

To reproduce, create a haproxy.cfg with the following backend
```
backend be1
        mode http                                        
        balance source                                
        http-check expect status 200
```

Fetch backend via dataplane api

```
sig@desktop2:~$ curl -s --user $user -H "Content-Type: application/json" "$service/v2/services/haproxy/configuration/backends" |jq .
{
  "code": 500,
  "message": "interface conversion: common.ParserData is []types.HTTPAction, not []types.HTTPCheckV2: /home/vagrant/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.1-0.20201116103227-1420d747ec2c/configuration/configuration.go:399 parseField"
}
```

API logs
`
time="2020-11-20T16:07:56-05:00" level=error msg="Panic interface conversion: common.ParserData is []types.HTTPAction, not []types.HTTPCheckV2" stack_trace="\n/home/vagrant/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.1-0.20201116103227-1420d747ec2c/configuration/configuration.go:399 parseField\n/home/vagrant/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.1-0.20201116103227-1420d747ec2c/configuration/configuration.go:294 ParseSection\n/home/vagrant/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.1-0.20201116103227-1420d747ec2c/configuration/backend.go:47 (*Client).GetBackends\n/home/vagrant/haproxy-dataplane-api/dataplaneapi/handlers/backend.go:160 (*GetBackendsHandlerImpl).Handle\n/home/vagrant/haproxy-dataplane-api/dataplaneapi/operations/backend/get_backends.go:90 (*GetBackends).ServeHTTP\n/home/vagrant/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/operation.go:28 NewOperationExecutor.func1\n/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP\n/home/vagrant/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/router.go:77 NewRouter.func1\n/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP\n/home/vagrant/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/redoc.go:72 Redoc.func1\n/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP\n/home/vagrant/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/spec.go:46 Spec.func1\n/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP\n/home/vagrant/haproxy-dataplane-api/dataplaneapi/adapters/adapters.go:152 RecoverMiddleware.func1.1\n/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP\n/home/vagrant/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 (*Cors).Handler.func1\n/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP\n/home/vagrant/haproxy-dataplane-api/dataplaneapi/adapters/adapters.go:166 LoggingMiddleware.func1.1\n/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP\n/home/vagrant/sdk/go1.15/src/net/http/server.go:2843 serverHandler.ServeHTTP\n/home/vagrant/sdk/go1.15/src/net/http/server.go:1925 (*conn).serve\n/home/vagrant/sdk/go1.15/src/runtime/asm_amd64.s:1374 goexit"
`

If you expand the new lines in the stack you get
```

/home/vagrant/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.1-0.20201116103227-1420d747ec2c/configuration/configuration.go:399 parseField
/home/vagrant/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.1-0.20201116103227-1420d747ec2c/configuration/configuration.go:294 ParseSection
/home/vagrant/go/pkg/mod/github.com/haproxytech/client-native/v2@v2.1.1-0.20201116103227-1420d747ec2c/configuration/backend.go:47 (*Client).GetBackends
/home/vagrant/haproxy-dataplane-api/dataplaneapi/handlers/backend.go:160 (*GetBackendsHandlerImpl).Handle
/home/vagrant/haproxy-dataplane-api/dataplaneapi/operations/backend/get_backends.go:90 (*GetBackends).ServeHTTP
/home/vagrant/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/operation.go:28 NewOperationExecutor.func1
/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP
/home/vagrant/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/router.go:77 NewRouter.func1
/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP
/home/vagrant/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/redoc.go:72 Redoc.func1
/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP
/home/vagrant/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/spec.go:46 Spec.func1
/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP
/home/vagrant/haproxy-dataplane-api/dataplaneapi/adapters/adapters.go:152 RecoverMiddleware.func1.1
/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP
/home/vagrant/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 (*Cors).Handler.func1
/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP
/home/vagrant/haproxy-dataplane-api/dataplaneapi/adapters/adapters.go:166 LoggingMiddleware.func1.1
/home/vagrant/sdk/go1.15/src/net/http/server.go:2042 HandlerFunc.ServeHTTP
/home/vagrant/sdk/go1.15/src/net/http/server.go:2843 serverHandler.ServeHTTP
/home/vagrant/sdk/go1.15/src/net/http/server.go:1925 (*conn).serve
/home/vagrant/sdk/go1.15/src/runtime/asm_amd64.s:1374 goexit

```

**Comment by aiharos** [comment]
Thank you for the report, we're looking into confirming this.

**Comment by prometherion** [comment]
Hi @sigmonsays, we just pushed the commit 8f38732f5799d69227a6db86a7ee7695e527f74a that should fix this unexpected panic: it has been caused by [a bug](https://github.com/haproxytech/config-parser/commit/82ebcd4e6d2c97c1c4784d4a6b9343f8d0ae2c59) introduced in the underlying `config-parsers` package.

Feel free to close this issue once double-checked it works!

**Comment by sigmonsays** [comment]
Thanks!

Verified fix using the previous mentioned curl call ($service/v2/services/haproxy/configuration/backends). No longer returns a 500 and contains the expected structure.
