### ISSUE TITLE
Adding http_request_rule via API fails with error "Unexpected status code '0' "

### ISSUE THREAD

**Issue by frank2b** [haproxytech/dataplaneapi#145]
I am trying to add a http_request_rule via API but getting error :
curl -X POST --user <user>:<pass> \
       -H "Content-Type: application/json" \
       -d '{"index": 0, "cond":"if", "cond_test": "{ var(txn.modsec.code) -m int gt 0 }", "type": "deny"}' \
       "http://localhost:5555/v2/services/haproxy/configuration/http_request_rules?parent_name=<front>&parent_type=frontend&transaction_id=<tr id>"

Error while trying to commit :
{"code":400,"message":"14: ERR transactionId=898a0c99-0e64-466b-a37f-6660a4ea14a4 \nline=49 msg=\"error detected in frontend '<front>' while parsing 'http-request deny' rule Unexpected status code '0'.\""}

Adding the rule manually to the haproxy config works well.
What am I missing ?
Thx Frank

**Comment by frank2b** [comment]
Sorry, the data I placed in "<>" was deleted. So, the curl call was correct . It looks like this :
curl -X POST --user user:password \
       -H "Content-Type: application/json" \
       -d '{"index": 0, "cond":"if", "cond_test": "{ var(txn.modsec.code) -m int gt 0 }", "type": "deny"}' \
"http://localhost:5555/v2/services/haproxy/configuration/http_request_rules?parent_name=system_front&parent_type=frontend&transaction_id=898a0c99-0e64-466b-a37f-6660a4ea14a4"

**Comment by frank2b** [comment]
HAproxy version : HA-Proxy version 2.2.2 2020/07/31 
HAProxy Data Plane API :  v2.1.0 af9b8e4

**Comment by oktalz** [comment]
hi @frank2b 
this was error in dataplaneapi specification that was fixed with https://github.com/haproxytech/dataplaneapi-specification/commit/70331571e8bc13fecb82f2e77404cf52a62b072a

next week you can expect new version that fixes it

until then for 2.1.0 solution is to add `"deny_status": 403` when pushing change

so this would look like
```
curl -X POST --user user:password
-H "Content-Type: application/json"
-d '{"index": 0, "cond":"if", "cond_test": "{ var(txn.modsec.code) -m int gt 0 }", "deny_status": 403, "type": "deny"}'
"http://localhost:5555/v2/services/haproxy/configuration/http_request_rules?parent_name=system_front&parent_type=frontend&transaction_id=898a0c99-0e64-466b-a37f-6660a4ea14a4"
```

btw to post code/script on github you can wrap it with ```

 ```
    ```
    my code
    ```
 ```
