### ISSUE TITLE
Invalid error condition "redir_code in body should be one of [301 302 303]"

### ISSUE THREAD

**Issue by june07** [haproxytech/dataplaneapi#147]
Seems that this is an invalid error condition when using end point:
/v2/services/haproxy/configuration/http_request_rules

Redirect codes should include 307 and 308 as per:
https://github.com/haproxytech/dataplaneapi-specification/blob/master/models/configuration.yaml#L1396

Instead we have:
https://github.com/haproxytech/dataplaneapi-specification/blob/master/models/configuration.yaml#L1748

In my case this is causing 307 redirects to fail with error:
`redir_code in body should be one of [301 302 303]`

**Comment by aiharos** [comment]
Thanks for the report! This looks like a bug in the specification, we'll fix it!

**Comment by oktalz** [comment]
@june07 changes in specification are merged
