### ISSUE TITLE
Problem with "forwardfor" options in GET /services/haproxy/configuration/backends

### ISSUE THREAD

**Issue by mabramovic92** [haproxytech/dataplaneapi#15]
When we set `enabled` option to "enabled" and `ifnone` option to `true` for `forwardfor` (
```
"forwardfor": {
  "enabled": "enabled",
  "ifnone": true
}
```
), it is saved as it should but for GET request we get `enabled` as "disabled": 
```
"forwardfor": {
  "enabled": "disabled",
  "ifnone": true
}
```
.

**Comment by mjuraga** [comment]
Fixed with https://github.com/haproxytech/dataplaneapi/commit/a44ccdc4be5f02bbb55cbdc66d49f68ab5625c86
