### ISSUE TITLE
HAProxy issue reading file with 'http-request return'

### ISSUE THREAD

**Issue by avillost** [haproxytech/dataplaneapi#150]
HAProxy Version: 2.2.2
Filesize = 3KB
File permissions: -rwxrwxrwx. 1 f604258 f604258 3009 Jan  5 09:58 keys

Code:
http-request return status 200 content-type "application/json; charset=UTF-8" file /tmp/haproxy/keys if { path -i /adfs/discovery/keys }

Error:
[ALERT] 004/100451 (8473) : parsing [/local/idanywhere/etc/haproxy/conf/haproxy.cfg:68] : error detected in frontend 'fe_http_idainfra' while parsing 'http-request return' rule : error opening file '/tmp/haproxy/keys'.
[ALERT] 004/100451 (8473) : Error(s) found in configuration file : /local/idanywhere/etc/haproxy/conf/haproxy.cfg

I used the content-type that was given in Postman:
Content-Length →2995
Content-Type →application/json;charset=UTF-8
Date →Mon, 04 Jan 2021 21:35:09 GMT
Server →Microsoft-HTTPAPI/2.0 

What am I missing?

**Comment by mjuraga** [comment]
Is this dataplaneapi issue or HAProxy issue?

If you are having problems using HAProxy please refer to: https://github.com/haproxy/haproxy or post a question to the mailing list: http://www.haproxy.org/#tact
