### ISSUE TITLE
code: 602, message: "index in body is required" when trying to add/create an ACL

### ISSUE THREAD

**Issue by aintbrokedontfix** [haproxytech/dataplaneapi#151]
I am trying to run the following:
```
curl --location --request POST 'http://localhost:5555/v2/services/haproxy/configuration/acls?parent_type=frontend&parent_name=test_frontend&transaction_id=c9375396-4bab-4da5-bcd4-7e787c058fe5' \
--header 'Authorization: Basic YWRtaW4tbW9haTozOTVlOGFiOS1iZDNmLTQ5MjYtYTExOS0wOTMwYzg0ZTJkYTc=' \
--header 'Content-Type: application/json' \
--data-raw '{"id": 0, "acl_name": "is_example", "criterion": "req.hdr(Host)", "value": "example.com"}'
```

The frontend is known as "test_frontend" However, I get the following error and can't find what it means anywhere: 

```
{
    "code": 602,
    "message": "index in body is required"
}
```

**Comment by aintbrokedontfix** [comment]
Please update the documentation and examples:
The blog post : https://www.haproxy.com/blog/new-haproxy-data-plane-api/ shows the following parameters need to be passed to create an ACL:

```
curl -X POST --user admin:mypassword \
       -H "Content-Type: application/json" \
       -d '{"id": 0, "cond": "if", "cond_test": "is_example", "name": "example_servers"}' \
       "http://localhost:5555/v1/services/haproxy/configuration/backend_switching_rules?frontend=test_frontend&transaction_id=7d0d6737-655e-4489-92eb-6d29cdd69827"
```

The example should read/show the key word **"index": 0**. The example shows _"id": 0_ which is wrong:
```
curl -X POST --user admin:mypassword \
       -H "Content-Type: application/json" \
       -d '{"index": 0, "cond": "if", "cond_test": "is_example", "name": "example_servers"}' \
       "http://localhost:5555/v1/services/haproxy/configuration/backend_switching_rules?frontend=test_frontend&transaction_id=7d0d6737-655e-4489-92eb-6d29cdd69827"
```
The same documentation error can be found in the following URLs:

- https://www.haproxy.com/documentation/hapee/1-8r2/reference/dataplaneapi/#configuration-example
- https://www.haproxy.com/documentation/hapee/1-9r1/reference/dataplaneapi/#configuration-example
- https://www.haproxy.com/documentation/hapee/2-2r1/reference/dataplaneapi/#configuration-example

The Swagger doc is correct:
https://www.haproxy.com/documentation/dataplaneapi/latest/#operation/getAcls

**Comment by NickMRamirez** [comment]
I have added this issue to our internal documentation issues list.

**Comment by NickMRamirez** [comment]
In the end, we will likely remove the ACL examples from that part of the documentation. It's sufficient to have the other examples for GETs, POSTs, and transactions, but in-depth docs about more specific use cases like adding ACLs can remain in the embedded http://localhost:5555/v2/docs API URL.

**Comment by NickMRamirez** [comment]
Those incorrect examples have been removed from the latest version of the documentation. 
http://localhost:4000/documentation/hapee/2-2r1/api/data-plane-api/usage/
