### ISSUE TITLE
Support for 'http-request return' 

### ISSUE THREAD

**Issue by schegi** [haproxytech/dataplaneapi#155]
I would like to know if there are any plans to add support for the http-request return action (HAProxy 2.2+, i guess). If not i would like to look into that. Besides specification, config-parser and client-native integration is there something else i missed?

Greets Stefan

**Comment by schegi** [comment]
I already started to work on this, integration to config parser is nearly finished. I am a bit unshure how to add this to the swagger, will make a PR to the dataplaneapi-specification and would be glad if someone could take a closer look and confirm if it complies with or violates your expectations to your specifications.

Btw: cannot find any documentation related to x-dependency often used in the specification can someone point me to this?

stefan

**Comment by prometherion** [comment]
Hi @schegi and thanks for contributing!

> cannot find any documentation related to x-dependency often used in the specification

The `x-dependency` attribute is used for internal purposes, mostly for UI projects, so you can easily ignore them.

**Comment by schegi** [comment]
Thx, already open a PR for the specification https://github.com/haproxytech/dataplaneapi-specification/pull/29, mabe someone is willing to take a look. Client native is also finished but i'll wait for the models to be generated.

**Comment by schegi** [comment]
Ok specification, config-parser are merged, client-native is open. Can somebody give it a kick so that i can finally build a new dataplane API?

**Comment by oktalz** [comment]
@schegi client-native PR will be merged later today

**Comment by schegi** [comment]
Done
