### ISSUE TITLE
Managed lua files 

### ISSUE THREAD

**Issue by Elufimov** [haproxytech/dataplaneapi#156]
It would be very useful to have an ability to work with lua files like with SSL certificates and map files.

**Comment by aiharos** [comment]
Thank you for the suggestion! We'll discuss this for inclusion on our rodmaps.

**Comment by mjuraga** [comment]
Hi, we have added a general storage type endpoint which let's you upload any file to the `general_storage_dir` specified in the dataplaneapi configuration file. This is something that can be use for example for uploading lua files.

**Comment by Elufimov** [comment]
Thx I will take a look at it in near future.
