### ISSUE TITLE
Expose maps through the API

### ISSUE THREAD

**Issue by titansmc** [haproxytech/dataplaneapi#16]
Hi,
We want to use dataplaneapi to find out which is the backend for a specific service name like myapp.domain.com . We have the association stored in a map file, so, would it be possible to retrieve it through the API? I don't see any endpoint I can get that information from?

Cheers.

**Comment by titansmc** [comment]
Hi,
Is there any update on this? We have to make decisions based on the software maturity.

**Comment by mjuraga** [comment]
Hi, we put this into our roadmap, and are working on this for the v2 of the API.

**Comment by thriqon** [comment]
Hi, is the roadmap public? I have a use case to change map contents via the API...

**Comment by mjuraga** [comment]
We have added the ability to upload the map file trough the dataplaneaapi and it's in the 2.0 release: https://github.com/haproxytech/dataplaneapi/releases/tag/v2.0.0

**Comment by titansmc** [comment]
@mjuraga so is it possible to get them too?

**Comment by mjuraga** [comment]
Yes, you can upload the map file and use all the actions available in the Runtime API: get map, set map, add map, del map using the methods for on the `/v2/services/haproxy/runtime/maps` and `/v2/services/haproxy/runtime/maps_entries` endpoints.

Also there are two new ne CLI options: `--update-map-files` and `--update-map-files-period` that will update the map files on disk in the periods you configure, so your dynamic map files changes (whether trough http-request rules or using the Runtime API) persist through a reload/restart of the HAProxy.

**Comment by mjuraga** [comment]
If you are happy with this feature, you can close the issue.

**Comment by titansmc** [comment]
Thanks a lot
