### ISSUE TITLE
Deleting a map entry by id always returns 204 even when the id or map don't exist

### ISSUE THREAD

**Issue by andyallan** [haproxytech/dataplaneapi#160]
https://www.haproxy.com/documentation/dataplaneapi/latest/#operation/deleteRuntimeMapEntry

No matter what "id" value (or "map") you send, the result is always 204. The docs state that a 404 should be returned if the specified resource cannot be found. 

`curl -I -X GET --user user:password -H "Content-Type: application/json" "http://ip:5555/v2/services/haproxy/runtime/maps_entries/{id}?map={map}"`

Replace {id} and {map} with appropriate entries. You'll always get a 204 returned.

```
dataplaneapi -v
HAProxy Data Plane API v2.2.0 68bd22b

Build from: https://github.com/haproxytech/dataplaneapi.git
Build date: 2021-01-15T13:48:22Z
```

**Comment by mjuraga** [comment]
Duplicate of #159
