### ISSUE TITLE
httpchk regex too strict

### ISSUE THREAD

**Issue by mr-simonski** [haproxytech/dataplaneapi#161]
In our static configuration we use a special `httpchk` option as we use Tomcat in our backend configuration which runs into problems if no `Host `header is given in a HTTP request. Because of that we add `\r\nHost:\ subdomain.example.com` to our `httpchk `option which works fine:

```
backend my-api
	balance roundrobin
	option httpchk GET /healthcheck HTTP/1.1\r\nHost:\ subdomain.example.com
	http-check expect rstatus (2|3)[0-9][0-9]

	server myserver_8787 123.123.123.123:8787 check inter 10s fastinter 5s fall 2 rise 1 pool-purge-delay 30s
```

If we use the dataplane api and try to set the `httpchk `option programmatically like that:

```
{
"method": "GET",
"uri": "/healthcheck\\r\\nHost:\\ subdomain.example.com",
"version": "HTTP/1.1"
}
```

or that:

```
{
"method": "GET",
"uri": "/healthcheck HTTP/1.1\\r\\nHost:\\ subdomain.example.com"
}
```

... I get the following feedback: `uri in body should match '^[^\\\\s]+$'`

How could I add special headers for the healthcheck purpose? Any workaround?

**Comment by fmaslennikov** [comment]
We faced this issue too. HAProxy documentation tells us to use httpchk send instead. But i didn't see implementation of httpchk send functionality in dataplane api.

**Comment by mr-simonski** [comment]
Our quickfix for now was to switch to HTTP/1.0 which doesn't need to have a `Host` header set.

**Comment by mjuraga** [comment]
Hi @mr-simonski thanks for the report. This is a bug and we'll look into it.

**Comment by amelhusic** [comment]
Hi @mr-simonski 

We changed pattern validation regex [here](https://github.com/haproxytech/client-native/commit/68e3c8b8baa39f334ca3ec03932370ca4d930ba4). Please note that `uri` should consist of one word, but `version` could have more than one word. Sample request that works:

```
> PUT /v2/services/haproxy/configuration/backends/my-api?version=71 HTTP/1.1
> Host: 127.0.0.1:5679
> User-Agent: insomnia/2021.1.1
> Content-Type: application/json
> Authorization: Basic YWRtaW46YWRtaW4=
> Accept: */*
> Content-Length: 255

{
   "name": "my-api",
   "adv_check": "httpchk",
   "balance": {
      "algorithm": "roundrobin"
     },
   "httpchk_params": {
      "method": "GET",
      "uri": "/healthcheck",
      "version": "HTTP/1.1\\r\\nHost:\\ subdomain.example.com"
     }
 }

```
