### ISSUE TITLE
Regular expression specification inconsistency between documentation and go spec

### ISSUE THREAD

**Issue by bren-doyle** [haproxytech/dataplaneapi#162]
In the Haproxy specification (https://www.haproxy.com/documentation/dataplaneapi/latest/) the specification for adding a backend http-check list the "pattern" as 
`"^[^\s]+$"`
where as in embedded_spec.go it is listed as 
`"^[^\\s]+$"`
Consequently if I try and add "^((?!false).|\s)*$" as a pattern, whilst it matches the documented spec, it fails the go spec:

{"code":400,"message":"parsing data body from \"\" failed, because invalid character 's' in string escape code"}{"code":400,"message":"11: backend example_bes does not exist"}

**Comment by amelhusic** [comment]
Hi @bren-doyle ,

We removed pattern validation [here](https://github.com/haproxytech/client-native/commit/f8af7e73b99b364383bb204d099b9f4122c8844b). As for regex, can you try to use `^((?!false).|\\s)*$` ?
If I understood correctly intention of regex you used, it suppose to allow everything except `false`. I tested it here:
https://regex101.com/r/IFuLiC/1/.

**Comment by bren-doyle** [comment]
Sounds good thanks.
