### ISSUE TITLE
Get one ACL/Backendswitching line based on name

### ISSUE THREAD

**Issue by bren-doyle** [haproxytech/dataplaneapi#166]
Given that you need the index value to delete an ACL or backend switching entry, it would be better if the APIs to retrieve a single line for either took the ACL/Rule name as input not index and returned the index value that the ACL/rule name is currently at. If there have been many additions and deletions of ACLs/Rules, then at any given point in time we can't be certain at what index an ALC/Rule is at. Currently to delete an entry we have to retrieve the entire list, walk through it to find the specific ACL/Rule based on name, get then associated index, then delete it.

**Comment by oktalz** [comment]
hi @bren-doyle 
ACL name is not unique, you can have multiple ACLs with same name, and that configuration is valid.
So name can't be used as an id

**Comment by bren-doyle** [comment]
Sure, but you could return a array of matching name entries, would make it easier to find the index needed to delete an entry

**Comment by mjuraga** [comment]
We could add a qs parameter name to filter only ACLs with given name on GET method if that would help you.

**Comment by mjuraga** [comment]
Hi @bren-doyle, we've added a qs param to filter ACLs by name in https://github.com/haproxytech/dataplaneapi/commit/da36014041a3086837894691980cc52834cb7635

**Comment by bren-doyle** [comment]
Yeah, that would help, thanks
