### ISSUE TITLE
Service Discovery Not Always Picking Up

### ISSUE THREAD

**Issue by lmcdasm** [haproxytech/dataplaneapi#171]
Hey there.

We have a consul node setup and have the dataplane API setup and running.

I am able to add the Service Discovery endpoint - 

![image](https://user-images.githubusercontent.com/9358276/107894301-477ba980-6efd-11eb-9c27-deda721102c9.png)

I can see in the log files that the endpoint is added, however when new Services Register in Consul, i only see the dataplane API pull them every once and a while, meaning that if restart the Consul fresh and haproxy/dataplane fresh and register the service with Consul, i can see haproxy creating the backend.

however, if i point the dataplane API at another instance of Consul with services already registered, i dont see the dataplane doing anything (no new backends are setup).

Im running haproxy-2.4-dev7
the dataplaneapi is from the release.
here is my haproxy.cfg (its pretty vanilla)

I tried to set the dataplane log level to trace, but i dont see anything "extra" - nothing indicating that its polling consul.
I also did a snoop and i dont see anything coming from the dataplane api to consul (despite being reistered)

global
    log         stdout local0
    chroot      /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    pidfile     /var/run/haproxy.pid
    maxconn     50000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    #stats socket /var/lib/haproxy/stats

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option forwardfor       except 127.0.0.0/8
    timeout connect         5000
    timeout client          240000
    timeout server          240000
    maxconn                 50000

userlist haproxy-dataplaneapi
        user admin insecure-password mypassword
        user dataplane insecure-password password

program api
   command /usr/bin/dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /usr/local/etc/haproxy/haproxy.cfg --reload-cmd "kill -SIGUSR2 1" --reload-delay 5 --userlist haproxy-dataplaneapi --log-level=trace --log-to=stdout
   no option start-on-reload

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend  main
    bind *:80
    # bind *:443 ssl # To be completed ....

    acl url_static       path_beg       -i /static /images /javascript /stylesheets
    acl url_static       path_end       -i .jpg .gif .png .css .js

    use_backend static          if url_static
    default_backend             app

#---------------------------------------------------------------------
# static backend for serving up images, stylesheets and such
#---------------------------------------------------------------------
backend static
    balance     roundrobin
    server      static1 127.0.0.1:4331 check
    server      static2 127.0.0.1:4332 check

#---------------------------------------------------------------------
# round robin balancing between the various backends
#---------------------------------------------------------------------
backend app
    balance     roundrobin
    server  app1 127.0.0.1:5001 check
    server  app2 127.0.0.1:5002 check
    server  app3 127.0.0.1:5003 check
    server  app4 127.0.0.1:5004 check

Here is the log when i did the CURL to registry the consul with the dataplane api.

128>Feb 14 07:59:29 haproxy[10]: backend app has no server available!
time="2021-02-14T08:00:12Z" level=info msg="started handling request" method=POST remote="10.179.48.6:46810" request=/v2/service_discovery/consul request_id=01EYFRVS2JB29ES3SNG8ZE3YSP
time="2021-02-14T08:00:12Z" level=info msg="completed handling request" length=277B request_id=01EYFRVS2JB29ES3SNG8ZE3YSP status=201 took="621.932µs"

**Comment by lmcdasm** [comment]
Hello All.

A bit more information.

if i use a simple CURL with the following payload to register a two services (echo 1 and echo 2) with Consul, after doing a fresh start of the haproxy with dataplane setup (and adding the consul server) , then im able to see the backend created 

![image](https://user-images.githubusercontent.com/9358276/107898555-00e07c00-6f0a-11eb-984d-437e6c49e97a.png)


however, when i an using the consul go client, and i and using AgentServiceRegister call, it seems that while the service is registered in Consul, haproxy (dataplane) is not picking it up and making a backend.

**Comment by mjuraga** [comment]
Hi @lmcdasm thank you for your report, can you please try building dataplaneapi from master and trying again? Maybe this commit : https://github.com/haproxytech/dataplaneapi/commit/309c65f5f10ead20cd557229ee010df72d9c7c81 fixes your issue.
