### ISSUE TITLE
Transactions failing with other than 409 (wrong version) does not decrement transaction counter.

### ISSUE THREAD

**Issue by schegi** [haproxytech/dataplaneapi#177]
Related to: https://github.com/haproxytech/dataplaneapi/issues/173

Sry for reporting again, but it seems like the fix for the translation counter issue (https://github.com/haproxytech/dataplaneapi/commit/bb617cab4c70615d52c38cceb8a16f2172dbdb35) only solves the issue for transactions failed due to version issues. If a transaction commit fails due to something else, e.g. failed validation on commit (getting a 400), the internal transaction counter is still not decreased. That again leads to the same situation as described in https://github.com/haproxytech/dataplaneapi/issues/173, with each failed transaction you could start one less until you finally reach the max active transaction threshold and you are not able to start transactions any more.

**Comment by prometherion** [comment]
Thanks for reporting this @schegi! We're actually working on an improvement dealing with these cases, we'll ping you back once delivered to the main branch so you can test it on your own and gives us appreciated feedback.

**Comment by schegi** [comment]
Thx

**Comment by schegi** [comment]
Any news on this? We really rely on this to be fixed and are willing to invest time.

**Comment by mjuraga** [comment]
This is actively being worked on, and should be merged soon. We'll let you know.

**Comment by schegi** [comment]
Hi, looked over the code again cause we really need this to be fixed and it seems like that the issue should not occure anymore. Still found the TransactionCounter in your RateLimitedStratTransactionHandlerImpl but it seems it is currently only initialized and not used anymore. Are there any Plans to reactivate the ratelimit feature in the future?

**Comment by mjuraga** [comment]
@schegi what do you mean with it's not used anymore. I can see that it is used if you specify `--max-open-transactions` parameter. Can you elaborate more?

**Comment by schegi** [comment]
Sry my fault, just realized that the decrease/increase calls where removed, didn't get the new handling with the actualCount function. 
Tested the new version successfully and it seems to work now.  Another thing, during my tests i realized that you return a 400 if someone tries to cancel a non-existing (failed) transaction, wouldn't it be better to return a 404? Should i open a new issue for that?

From my point of view this issue can be closed.

**Comment by mjuraga** [comment]
Well if the transaction is failed, it's not non-existing, you can still fetch it. So it is a bad request, trying to commit a failed transaction.

**Comment by schegi** [comment]
Not trying to commit it but to cancel it. it returns a 400 stating transaction does not exist, e.g. Transaction 274925d5-3103-4b8c-886d-24eefb810ff4 does not exist code=400. (274925d5-3103-4b8c-886d-24eefb810ff4 previously failed)
