### ISSUE TITLE
Request to /v2/services/haproxy/transactions?version=1 return a 429 Too Many Requests

### ISSUE THREAD

**Issue by aintbrokedontfix** [haproxytech/dataplaneapi#178]
Repeated request for a transaction returns a 429 Too Many Requests. Is it possible to change the threshold? If not what is the threshold? 20? 

Thanks!

**Comment by mjuraga** [comment]
Hi @aintbrokedontfix, the threshold is whatever you set with `--max-open-transactions`. If you don't specify that option, then no rate limiting is used for transactions.
