### ISSUE TITLE
default_server ciphers ignored 

### ISSUE THREAD

**Issue by bren-doyle** [haproxytech/dataplaneapi#180]
request to backend enddpoint that specifies:

         "default_server": {"ciphers": "ECDHE-RSA-AES128-GCM-SHA256"}

generates a config file entry of:
  default-server

i.e It is ignored

**Comment by mjuraga** [comment]
I can confirm that this is a bug. We'll fix it and it will be included in the next release. Thank you for your report.

**Comment by bren-doyle** [comment]
By the way 'ssl-max-ver' and 'ssl-min-ver are also ignored

**Comment by mjuraga** [comment]
This should be fixed in the next release. It is added here: https://github.com/haproxytech/client-native/commit/d7e5a56fb630e488fab8d05cd20edc3a9d43fbc0
