### ISSUE TITLE
No Configuration-version in response header for 422 responses.

### ISSUE THREAD

**Issue by schegi** [haproxytech/dataplaneapi#183]
When adding a misconfigured entity (e.g. a Backend without 'required' name) the dataplaneapi does answer with a 422 unprocessable entity. The spec explicitely defines bad request (400), version conflict (409) and as default a general error. All of them are defined to contain a configuration-version field in the header, but the actual 422 response does not contain the Configuration-version field in the response header.

> curl -H"Content-Type: application/json" -X POST http://localhost:5555/v2/services/haproxy/configuration/backends\?version\=1 -d '{}'
> 
> HTTP/1.1 422 Unprocessable Entity
> Content-Type: application/json
> Vary: Origin
> Date: Thu, 08 Apr 2021 13:04:00 GMT
> Content-Length: 49
> 
> {"code":602,"message":"name in body is required"}

For the defined error messages, e.g. version conflict (409) the header field is present. Try this assuming the current configuration version is != 1:
> curl -H"Content-Type: application/json" -X POST http://localhost:5555/v2/services/haproxy/configuration/backends\?version\=1 -d '{"name": "test"}'
> 
> HTTP/1.1 409 Conflict
> **Configuration-Version: 0**
> Content-Type: application/json
> Vary: Origin
> Date: Thu, 08 Apr 2021 13:04:09 GMT
> Content-Length: 85
> 
> {"code":409,"message":"15: version in configuration file is 10, given version is 8"}

This is not only true for backend, as shown in the example but for at least 422 responses given to POST requests on all kinds of entities. Not shure if this also applies to errors other than 422.
This currently causes us trouble with go clients generated from the spec using go-swagger.

Stefan

**Comment by mjuraga** [comment]
Hi Stefan, we are working on making this more standardized across all endpoints, it should land in the master soon.

**Comment by mjuraga** [comment]
Hi Stefan all our endpoints should now return config version. This is in master with this commit: https://github.com/haproxytech/dataplaneapi/commit/cccaea786e054a1a567c81e63a2bf5467b8900cc

**Comment by schegi** [comment]
Thx

**Comment by june07** [comment]
Seems this might still be an issue... using v2.6.1...

Although it's provided in the body... the header still has no configuration-version as per the docs.

![image](https://user-images.githubusercontent.com/11353590/204152715-3e8a0dca-5871-48b7-a04b-4fabf8f2e32d.png)
