### ISSUE TITLE
Batch map entries handling

### ISSUE THREAD

**Issue by Duvieusam** [haproxytech/dataplaneapi#189]
I am currently working with map files which are used as whitelists and are dynamically updated through the Dataplane API. I sometimes have to insert or delete more than 100 IP addresses in a map file which result in more than 100 HTTP calls.
I tried using the Replace Map call in storage category but it reloads the Haproxy which is dropping my long term TCP connections.

Is there a way to update a bunch of entries in a map file without sending a lot of HTTP requests or reloading Hap?

**Comment by bedis** [comment]
Hi
Reloading should not drop any connections. Can you share with us more information on the way you're triggering the reloads?

**Comment by Duvieusam** [comment]
Hi,
Reloads are tiggered by this https://www.haproxy.com/documentation/dataplaneapi/latest/#operation/replaceStorageMapFile

**Comment by amelhusic** [comment]
Hi @Duvieusam,

In https://github.com/haproxytech/dataplaneapi/commit/fe2a06148891ac045f166bdb02a241bcaae3ff4d we added a new endpoint for `add map mayload`. If you are using a HAProxy 2.4 version you can update your maps atomically and teoretically without size limitation (we use `prepare, add, commit` commands for this purpose) and if you are using lower HAProxy versions, you can still send payload but be aware that there is a `tune.bufsize` limitation we have to use (up to 8192 bytes)
