### ISSUE TITLE
Cannot delete, update, or get a single map entry

### ISSUE THREAD

**Issue by brenc** [haproxytech/dataplaneapi#190]
HAProxy Data Plane API v2.2.1
HA-Proxy version 2.2.13-5f3eb59

I can get maps, get a map's entries, and add map entries with the API. However, I keep getting errors when trying to delete, update, or get a single map entry.

Take the following map:
```
[
  {
    "description": "pattern loaded from file '/etc/haproxy/maps/disabled_paths.map' used by map at file '/etc/haproxy/haproxy.cfg' line 744",
    "file": "/etc/haproxy/maps/disabled_paths.map",
    "id": "128",
    "storage_name": "disabled_paths.map"
  }
]
```
With contents:
```
 [
  {
    "id": "0x5615e12fb6c0",
    "key": "/test/path",
    "value": "1"
  }
]
```
I want to update the value to "0" so I send `PUT /v2/services/haproxy/runtime/maps_entries/0x5615e12fb6c0?map=disabled_paths` with the following JSON body:
```
{
  "value": "0"
}
```
Which returns this:
```
{
  "code": 404,
  "message": "[3]  entry not found.\n [set map /etc/haproxy/maps/disabled_paths.map 0x5615e12ffb10 0] not found"
}
```
Looks like the Data Plane API is sending the ID directly to the runtime API which expects `#id` so I then send `PUT /v2/services/haproxy/runtime/maps_entries/#0x5615e12fb6c0?map=disabled_paths`:
```
{
  "code": 405,
  "message": "method PUT is not allowed, but [GET,POST] are"
}
```
Same thing for `DELETE /v2/services/haproxy/runtime/maps_entries/0x5615e12fb6c0?map=disabled_paths`:
```
{
  "code": 404,
  "message": "[3]  Key not found.\n [del map /etc/haproxy/maps/disabled_paths.map 0x5615e12fb6c0] not found"
}
```
`DELETE /v2/services/haproxy/runtime/maps_entries/#0x5615e12fb6c0?map=disabled_paths`:
```
{
  "code": 405,
  "message": "method DELETE is not allowed, but [GET,POST] are"
}
```
`GET /v2/services/haproxy/runtime/maps_entries/0x5615e12fb6c0?map=disabled_paths`:
```
{
  "code": 404,
  "message": "0x5615e1303b30 not found"
}
```
`GET /v2/services/haproxy/runtime/maps_entries/#0x5615e12fb6c0?map=disabled_paths`:
```
{
  "code": 602,
  "message": "map in query is required"
}
```
The docs are pretty confusing and there are no real example queries so I could be missing something. I've tried several permutations of the ID but nothing seems to work. What am I missing?

**Comment by amelhusic** [comment]
Hi @brenc ,

There are two types of `id`s here. One you get from runtime entries, e.g.:
```
{
    "id": "0x55a690806c30",
    "key": "www.example.com",
    "value": "be_static"
 }

```
and one you get as map file identifier, e.g.
```
{
  "description": "pattern loaded from file '/tmp/maps/hosts.map' used by map at file '/etc/haproxy/haproxy.cfg' line 33",
  "file": "/tmp/maps/hosts.map",
  "id": "4"
}

```

For the following endpoints, you should use `key` as a parameter, not `id`:
```
GET	  /services/haproxy/runtime/maps_entries/{{ id }} => /services/haproxy/runtime/maps_entries/{{ key }}
PUT 	  /services/haproxy/runtime/maps_entries/{{ id }} => /services/haproxy/runtime/maps_entries/{{ key }}
```

For this endpoint you can use either `key` or `id` from runtime entries (please note that `id` should be encoded):
`DELETE /services/haproxy/runtime/maps_entries/{{ id }}`

This endpoint is using `map`  (it could be either map file name or map `id`) as a parameter:
```
GET /services/haproxy/runtime/maps_entries
```
You can use it in 2 different ways:
 ```
 a) GET /services/haproxy/runtime/maps_entries?map=%235
 b) GET /services/haproxy/runtime/maps_entries?map=host2
```

For this endpoint `id` from runtime entries should be encoded and passed as parameter:
` DELETE /services/haproxy/runtime/maps_entries/{{ id }}``

We are aware that parameter naming here is not the best, so we are considering to make some changes in future.
I think I covered all cases and endpoints with `runtime_entries`, but if something else is not working as you expected, we would be glad to answer that too.

**Comment by brenc** [comment]
Hrmm yeah this is super confusing. But it looks like the missing component was URL encoding the key / ID depending on the endpoint which appears to work. Thanks.
