### ISSUE TITLE
Can dataplaneapi be ran as non-root user?

### ISSUE THREAD

**Issue by cachemeoutside** [haproxytech/dataplaneapi#193]
Hello,

I'm fairly new and at the beginning stages of setting up dataplaneapi in our environment. I've been following the instructions on this page:

https://www.haproxy.com/documentation/hapee/2-2r1/api/data-plane-api/installation/haproxy-community/

I am using the HAProxy process manager method of running the dataplaneapi proc, but I can't seem to get it to work with a non-root user. I would get permission denied errors(not sure where it's attempting to write the dataplaneapi.yaml file).

I can get HAProxy(without dataplaneapi) running as a non-root user configured with systemd and not have issues. I had to resort to changing the systemd service user to root to get it to run properly. But this ends up creating dataplaneapi managed files to be owned by root.

Here's the command I used to start the dataplaneapi proc:

```
program api
  command /opt/dataplaneapi/bin/dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/local/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "systemctl reload haproxy" --reload-delay 5 --userlist haproxy-dataplaneapi
  no option start-on-reload
```

If there are any guides/examples/configs you can post, that'll be very helpful. Thank you for the great work!

EDIT:
Running HAProxy 2.2.13 and Dataplaneapi 2.2.1

**Comment by mjuraga** [comment]
Hi @cachemeoutside we've added options to set gid and uid for the dataplaneapi process, and it's already in master. They should be released with the new version soon.

In the meanwhile you can try to build the latest dataplaneapi and set `--uid` and `--gid` parameters for the dataplaneapi.

**Comment by oktalz** [comment]
also prerequisite for using this is to build dataplaneapi with Go 1.16

**Comment by mjuraga** [comment]
Hi, you can try this feature out with the new v2.3.0 release.
