### ISSUE TITLE
No reload on transactions only adding bind

### ISSUE THREAD

**Issue by schegi** [haproxytech/dataplaneapi#196]
Hi,

came across the following issue. If i open a transaction and just add a bind in this transaction and then commit it without force_reload, the haproxy config reload is not triggered. If i add force_reload the reload will be triggered. I only recognize it to (not) happen for binds. 

Steps to reproduce:
Watch to changes in haproxy logs, e.g. 'journalctrl -u haproxy -f'

1. Create a backend, e.g. '{"name": "test-backend}' and a frontend '{"name": "test-frontend", "default_backend": "test-backend", "mode": "http"}'. For every transaction commit you use for these changes you should see something, like 'Month DAY HH:MM:SS localhost systemd[1]: Reloaded HAProxy Load Balancer.'
2. Open a new transaction
3. Add a bind to 'test-frontend', '{"name":"test-bind", "address": "*", "port": 888}'
4. Commit the transaction. This time you will not see any reload action in the log.

Stefan

**Comment by mjuraga** [comment]
Hm, I've tried to reproduce your steps, but haven't been able to do so. Can you try this with our latest released version?
