### ISSUE TITLE
Build date cannot be parsed

### ISSUE THREAD

**Issue by georgijd-form3** [haproxytech/dataplaneapi#197]
Hello,

I've noticed that the build artifact has an incorrect build date which cannot be parsed resulting in lots of errors in the logs.

These are the startup logs (notice the format of the build date)

```
time="2021-05-07T08:29:24Z" level=info msg="HAProxy Data Plane API v2.2.1 7fb8e05"
time="2021-05-07T08:29:24Z" level=info msg="Build from: https://github.com/haproxytech/dataplaneapi.git"
time="2021-05-07T08:29:24Z" level=info msg="Build date: 2021-04-07T11:50:45Z"
```

Upon calling the `/v2/info` endpoint we get the following error log:

```
parsing time "2021-04-07T11:50:45Z": extra text: "Z"
```

It must be something specific to the build environment because when running `make build` locally (or in GitHub Workflows) the date is in the correct format:

```
❯ make build
mkdir -p /repos/dataplaneapi/build
GOOS=linux CGO_ENABLED=0 go build -trimpath -ldflags "-X main.GitRepo=git@github.com:georgijd/dataplaneapi.git -X main.GitTag=v2.2.0-rc1 -X main.GitCommit=de441b7 -X main.GitDirty=.dev -X main.BuildTime=2021-05-07T11:42:12" -o /repos/dataplaneapi/build/dataplaneapi /repos/dataplaneapi/cmd/dataplaneapi/
```

The offending code: https://github.com/haproxytech/dataplaneapi/blob/de441b7ddfd1678c0de5c6b19166556b38ed9889/handlers/information.go#L72-L77

**Comment by mjuraga** [comment]
Hi, thank you for your report, it seems it's something when built with goreleaser. We will look into it.
