### ISSUE TITLE
add support for external-check 

### ISSUE THREAD

**Issue by yuzhichang** [haproxytech/dataplaneapi#2]
I'm using following haproxy.cfg with haproxy 2.0. 
I want to manage the config with dataplane api. However it doesn't support `external-check` and `on-marked-down` yet.

```
global
    ......
    external-check

listen citus-coordinator-master
    bind *:5440
    mode tcp
    balance first
    option external-check
    external-check path "/usr/bin:/bin"
    external-check command /usr/local/bin/pg_is_master.sh
    server co0 10.126.144.141:10000 check inter 5000 on-marked-down shutdown-sessions
    server co1 10.126.144.142:10001 check inter 5000 on-marked-down shutdown-sessions

```

**Comment by mjuraga** [comment]
We don't support those options and we don't support shutdown-sessions as of now. Also we do not parse listen section, and I encourage you to split those in frontend/backend pair, you can have more flexibility moving forward. 

If you are willing to add those options yourself I can guide you how to contribute them, if not, we can add them to the roadmap.

**Comment by yuzhichang** [comment]
I'll try following changes: 
- add client SDK
- add `external-check` and `on-marked-down` support
- dismiss [haproxytech/models](https://github.com/haproxytech/models) since the whole project is  generated from dataplaneapi-specification

**Comment by mjuraga** [comment]
Yes, here are the steps for adding these options. E.g. for ```on-marked-down``` you can do the following:

1. Add it to the model of the [server in specification](https://github.com/haproxytech/dataplaneapi-specification/blob/master/models/haproxy.yaml#L438) and build haproxy_spec.yaml with the build binary
2. Using that built yaml generate new [models](https://github.com/haproxytech/models)
3. Add the option [here](https://github.com/haproxytech/client-native/blob/master/configuration/server.go)

**Comment by mjuraga** [comment]
For ```external-check```, you should first add ```option external-check``` support: 

1. Add it to config parser as a SimpleOption [here](https://github.com/haproxytech/config-parser/blob/master/section-parsers.go) in Defaults and Backend sections
2. Add it to the specification and models as above and then add add those options to the client-native [here](https://github.com/haproxytech/client-native/blob/master/configuration/configuration.go)

Same applies for ```external-check command``` and ```external-check path```, just you may have to write separate parsers for them, not use SimpleOption (check parsers.StickTable for example)

**Comment by mjuraga** [comment]
@yuzhichang great work on this so far, now all that is left is adding those options to client-native, and then just generating the new dataplaneapi so that it updates the specification in the server.

**Comment by yuzhichang** [comment]
@mjuraga I just opened following pull requests:
https://github.com/haproxytech/dataplaneapi-specification/pull/3
https://github.com/haproxytech/models/pull/2
https://github.com/haproxytech/config-parser/pull/2

I've hold on the pull request for client-native since its go.mod need revision of above repos.

**Comment by mjuraga** [comment]
I'll look into those PRs as soon as possible.

To answer your questions: 

- It is a bit of a pain for contributing, but we went with the thought that all those packages could be interesting in separate projects (client-native for go integration, someone maybe only wants to use config-parser for it) and we wanted to make it cleaner for importing and tagging versions, we wanted to be able to tag versions independently
- There are multiple benefits to using Runtime API (aka stats socket), we use it in dataplaneapi to get the stats and information endpoints using ```show stats``` and ```show info``` commands, also we change some options that can be changed dynamically without the need to reload HAProxy, like server address and port, etc...

**Comment by mjuraga** [comment]
Added in https://github.com/haproxytech/dataplaneapi/tree/v1.0.1

**Comment by yuzhichang** [comment]
@mjuraga I have a question. Is it doable to mark-down a server via dataplaneapi to force break existing backend TCP connections?  Haproxy external-check has [bugs](https://github.com/haproxy/haproxy/issues/141). I'm looking to `on-marked-down shutdown-sessions` without `option external-check`.

**Comment by mjuraga** [comment]
Have you checked ```disabled`` keyword (https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#5.2-disabled). You can set this by setting server ```maintenance``` property to ```enabled```. Not that this change is done through RuntimeAPI so if only this is changed, HAProxy won't be reloaded.

**Comment by yuzhichang** [comment]
@mjuraga Unfortunately I verified that adding `disabled` keyword to a server and reloading haproxy doesn't break existing backend connections with it even there's `on-marked-down shutdown-sessions`.
