### ISSUE TITLE
regex validation is restricting too match use_backend names

### ISSUE THREAD

**Issue by mjuraga** [haproxytech/dataplaneapi#20]
use_backend "use_backend %[req.cookie(foo)]" is not working due to regex limitation which only allows this '^[A-Za-z0-9-.:]+$' so regex validation should probably be relaxed

**Comment by mjuraga** [comment]
Fixed with https://github.com/haproxytech/dataplaneapi/commit/c0be0a2b94d3ff34c7dd861811ae57e1bed60daf

**Comment by mumrau** [comment]
Sorry to undig this issue, but I am wondering how to use the `use_backend` directive given the fact that the whitespace isn't part of the regex, I'm using `dataplaneapi` on `v1.2.4`, which appears to include this issue in the release.

I might have missed out on something big but if you can enlighten me (@mjuraga), it would be greatly appreciated.

**Comment by mumrau** [comment]
My use-case is quite simple, I would like to reproduce this kind of config:
```
acl my-stack hdr_dom(Host) mydomain.com
use_backend my-backend if my-stack
```

It doesn't work with the following payload:
```
{
    "id": 0,
    "name": "use_backend my-backend",
    "cond": "if",
    "cond_test": "my-stack"
}
```
It results in `{'code': 605, 'message': "name in body should match '^[^\\s]+$'"}`.

**Comment by mjuraga** [comment]
You don't need the `use_backend` keyword in the `name` key when posting to `backend_switching_rules` endpoint. Try this:
```
{
    "id": 0,
    "name": "my-backend",
    "cond": "if",
    "cond_test": "my-stack"
}
```
