### ISSUE TITLE
Advanced options for "tcp-check"

### ISSUE THREAD

**Issue by edhar-rybak** [haproxytech/dataplaneapi#203]
Hi! Am I missing something or advanced options for `option tcp-check` are not implemented in API? 
I'm looking for `tcp-check connect` `tcp-check send-binary` and `tcp-check expect binary`, but can't find anything in docs.
I expected something similar to `httpchk_params` for Backend configuration section.

**Comment by mjuraga** [comment]
Hi @edhar-rybak , we currently only have `adv_check` which can be set to value `tcp_check` and then in turn that sets just `option tcp-check` line in the config. We currently don't support `tcp-check` options in the config file, but we can add them in the next version.

**Comment by edhar-rybak** [comment]
Thanks for the answer @mjuraga. I think it would be great if dataplaneapi could cover all supported features in configuration. So this is similar to #153.

**Comment by mjuraga** [comment]
This has been added in v2.5.0.
