### ISSUE TITLE
Consul cluster service discovery 

### ISSUE THREAD

**Issue by guppyltd** [haproxytech/dataplaneapi#213]
Hi,
Is there any configuration in order to specify array ips for Consul in order to take advantage of a Consul cluster instead of a standalone setup?

Thanks!

**Comment by bbayszczak** [comment]
Hi,

On our side, we installed a Consul client agent on the same host than HAProxy. It allowed us to use `127.0.0.1` address during the Consul service discovery setup.
And the Consul agent know each node of the Consul cluster 🙂
