### ISSUE TITLE
Backups directory: no such file or directory

### ISSUE THREAD

**Issue by drwahl** [haproxytech/dataplaneapi#214]
The backups directory must be manually created before dataplaneapi can start. If you try to start dataplaneapi without this directory, you get the following error message:
level=fatal msg="Cannot initialize reload agent: open /tmp/haproxy/backups/.haproxy_dataplaneapi.cfg.lkg693378279: no such file or directory"

Dataplaneapi should at least try to create the directories it needs and not fail to startup if they do not exist.

**Comment by mjuraga** [comment]
Hi, this has been fixed with: https://github.com/haproxytech/dataplaneapi/commit/0c33f73e5d6633e3a2f1acc53bfa411f1a0e5bce
