### ISSUE TITLE
aws service discover doesn't work without credentials

### ISSUE THREAD

**Issue by bbstilson** [haproxytech/dataplaneapi#226]
In the [documentation](https://github.com/haproxytech/dataplaneapi/blob/master/discovery/AWS.md#authorization), it is claimed that:

> In case of Data Plane API running in an EC2 with a IAM Role attached (as AmazonEC2ReadOnlyAccess), there's no need for additional credentials.

However, this does not appear to be true.

With the following stanza in my `dataplaneapi.hcl`:

```hcl
service_discovery {
  aws_regions = [
    {
      Enabled = true
      Name = "haproxy-backend"
      Region = "us-west-2"
      IPV4Address = "private"
      RetryTimeout = 10
      ServerSlotsBase = 10
      ServerSlotsGrowthIncrement = 10
      ServerSlotsGrowthType = "exponential"
    },
  ]
}
```

I receive this (unhelpful) error message:

```
HAProxy Data Plane API v2.4.2 0e81c50
Build from: git@github.com:haproxytech/dataplaneapi.git
Build date: 2021-12-06T16:01:30Z
discovery job starting
Serving data plane at http://[::]:5555
127.0.0.1 - - [06/Dec/2021:23:15:40 +0000] "GET /v2 HTTP/1.1 401 64 "-" "Go-http-client/1.1" 126
discovery job update triggered
discovery job stopping
discovery job reconciliation completed
error while updating service: 14: err transactionId=ea00071d-2181-483c-a187-3fcfcd1612b5 
```

Specifically: `error while updating service: 14: err transactionId=ea00071d-2181-483c-a187-3fcfcd1612b5 `

When I look at the configuration file again, I see that the aws credentials fields have been added with empty values:

```hcl
service_discovery {
  aws_regions = [
    {
      AccessKeyID = ""
      Description                = ""
      Enabled                    = true
      ID                         = "93706517-acfc-4bc7-8119-93b65d58d6ee"
      IPV4Address                = "private"
      Name                       = "haproxy-backend"
      Region                     = "us-west-2"
      RetryTimeout               = 10
      SecretAccessKey            = ""
      ServerSlotsBase            = 10
      ServerSlotsGrowthIncrement = 10
      ServerSlotsGrowthType      = "exponential"
    },
}
```

If I add my credentials:

```
HAProxy Data Plane API v2.4.2 0e81c50
Build from: git@github.com:haproxytech/dataplaneapi.git
Build date: 2021-12-06T16:01:30Z
discovery job starting
Serving data plane at http://[::]:5555
127.0.0.1 - - [06/Dec/2021:23:14:31 +0000] "GET /v2 HTTP/1.1 401 64 "-" "Go-http-client/1.1" 165
discovery job update triggered
discovery job stopping
discovery job reconciliation completed
```

The backend isn't added to the `/etc/haproxy/haproxy.cfg` in either case, but the latter doesn't seem to have an error.

**Comment by prometherion** [comment]
Hi @bbstilson and thanks for reporting this issue!

I tried to replicate your issue as follows:

1. creating an IAM role named `ec2-readonly` with the `AmazonEC2ReadOnlyAccess` policy attached.
2. launched the EC2 instance with this role.
3. downloaded the Dataplane API (tested with `HAProxy Data Plane API v2.4.2 0e81c50`)
4. configured the Dataplane API configuration as follows.
   ```hcl
   dataplaneapi {
      scheme = ["http"]
      port   = 80

      user "admin" {
         insecure = true
         password = "adminpwd"
      }
   }

   haproxy {
      config_file = "/etc/haproxy/haproxy.cfg"
      haproxy_bin = "/usr/sbin/haproxy"
   }

   service_discovery {
      aws_regions = [
         {
            Description                = "test"
            Enabled                    = true
            IPV4Address                = "private"
            Name                       = "haproxy-backend"
            Region                     = "us-east-1"
            RetryTimeout               = 10
            ServerSlotsBase            = 10
            ServerSlotsGrowthIncrement = 10
            ServerSlotsGrowthType      = "exponential"
         },
      ]
   }

   log_targets = [
      {
         log_to           = "stdout"
         log_level        = "debug"
      },
   ]
   ```
5. Started to retrieve instances

And everything seems fine and working as expected, from logs I see several messages as follow, YMMV: `DEBU[0060] discovery job reconciliation completed        ID=12a5727c-9f71-4676-8b69-859df943fb58 ServiceDiscovery=AWS` 

To ensure the EC2 role is working as expected, I'm also testing with local AWS CLI:

```
[ec2-user@ip-172-31-63-108 build]$ aws ec2 describe-instances --region us-east-1 > /dev/null
[ec2-user@ip-172-31-63-108 build]$ echo $?
0
```

When I add some tagged instances that are going to be _discovered_, everything seems fine.

```
DEBU[0062] discovery job reconciliation completed        ID=12a5727c-9f71-4676-8b69-859df943fb58 ServiceDiscovery=AWS
DEBU[0062] Scheduling a new reload...                    reload_id=2021-12-07-0
DEBU[0062] Scheduling a new reload...                    reload_id=2021-12-07-0
DEBU[0062] discovery job reconciliation completed        ID=12a5727c-9f71-4676-8b69-859df943fb58 ServiceDiscovery=AWS
```

I guess the issue you're facing is related to the HAProxy version: I'm using `HA-Proxy version 2.2.0` that offers the flag `-W` (master-worker mode, don't remember when introduced) and this mode is mandatory for Dataplane API, the configuration check is performed [as follows](https://github.com/haproxytech/client-native/blob/26ecdb7596f69b58c3055b36707ba2f136c9798e/configuration/transaction.go#L249-L252).

Please, double-check your version of HAProxy to understand if you're affected by this sort of unsupported version, and if you can't upgrade you could try to force the `validate_cmd` from your [configuration file](https://github.com/haproxytech/dataplaneapi/blob/6c36f82dca233fa5bc4343861a022401b7d2f9df/configuration/examples/example-full.hcl#L75-L81).

**Comment by bbstilson** [comment]
Thanks for the quick response @dkorunic! I'm running HAProxy version `HAProxy version 2.6-dev0-73dec76` and HAProxy dataplane api version `v2.4.1 b7f016b`. These come from the docker image: `haproxytech/haproxy-ubuntu:2.6`. 

I've confirmed that I can access the EC2 instances from within the docker container:

```bash
aws ec2 describe-instances --filters Name=tag:HAProxy:Service:Name,Values=haproxy-backend | jq .Reservations[].Instances[].InstanceId -r
i-01e1c9b687292144a
```

I've also confirmed that haproxy is running in master-mode:

```
# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.2 192940 81068 ?        Ss   22:15   0:00 haproxy -sf 8 9 -x /var/run/haproxy.sock -W -db -f /usr/local/etc/haproxy/haproxy.cfg
root           8  0.2  0.1 728844 51704 ?        Sl   22:15   0:00 /usr/local/bin/dataplaneapi -f /usr/local/etc/haproxy/dataplaneapi.hcl --reload-cmd kill -SIGUSR2 1
root           9  0.0  0.2 1287072 72320 ?       Sl   22:15   0:00 haproxy -W -db -f /usr/local/etc/haproxy/haproxy.cfg
```

When I start the container, I do get what seem like success logs:

```
haproxy_1  | {"ID":"201b874f-608c-4db2-a573-ebfb2e5bc6bc","ServiceDiscovery":"AWS","level":"debug","msg":"discovery job starting","time":"2021-12-07T22:15:16Z"}
haproxy_1  | {"ID":"201b874f-608c-4db2-a573-ebfb2e5bc6bc","ServiceDiscovery":"AWS","level":"debug","msg":"discovery job update triggered","time":"2021-12-07T22:15:26Z"}
haproxy_1  | {"ID":"201b874f-608c-4db2-a573-ebfb2e5bc6bc","ServiceDiscovery":"AWS","level":"debug","msg":"discovery job reconciliation completed","time":"2021-12-07T22:15:27Z"}
haproxy_1  | {"ID":"201b874f-608c-4db2-a573-ebfb2e5bc6bc","ServiceDiscovery":"AWS","level":"debug","msg":"discovery job stopping","time":"2021-12-07T22:15:27Z"}
```

However, there are two issues:

1) That transaction doesn't seem to exist
  - I checked both the api and the transaction dir.
2) The configuration is not updated.

I've checked `/var/log` and `/tmp/haproxy` and there isn't anything in either location.

I've updated my dataplaneapi.hcl a bit:

```hcl
dataplaneapi {
  host = "0.0.0.0"
  port = 5555
  scheme = ["http"]

  user "admin" {
    insecure = true
    password = "admin"
  }

  transaction {
    transaction_dir = "/tmp/haproxy"
  }
}

haproxy {
  config_file = "/usr/local/etc/haproxy/haproxy.cfg"
  haproxy_bin = "/usr/local/sbin/haproxy"

  reload {
    reload_cmd  = "service haproxy reload"
    restart_cmd = "service haproxy restart"
    reload_delay = "5"
  }
}

service_discovery {
  aws_regions = [
    {
      AccessKeyID = "***"
      SecretAccessKey = "***"
      Region = "us-west-2"
      Enabled = true
      Description = "test"
      Name = "haproxy-backend"
      IPV4Address = "private"
      RetryTimeout = 10
      ServerSlotsBase = 10
      ServerSlotsGrowthIncrement = 10
      ServerSlotsGrowthType = "exponential"
    },
  ]
}

log_targets = [
  {
    log_to = "stdout"
    log_level = "debug"
    log_format = "json"
    log_types = ["app", "access"]
  }
]
```

**Comment by bbstilson** [comment]
This might be something: 

```
 service --status-all
 [ ? ]  hwclock.sh
 [ - ]  procps
```

The reload/restart commands can't work because haproxy isn't running as a service.
