### ISSUE TITLE
BUG - Duplicate comments added to top of config file after each change

### ISSUE THREAD

**Issue by thegagne** [haproxytech/dataplaneapi#227]
After making changes with the dataplane API, I noticed there are duplicate comments at the top of the config file for each change.

These are the lines that get duplicated over and over:

```
# Dataplaneapi managed File
# changing file directly can cause a conflict if dataplaneapi is running
```

It looks like it's supposed to be checking if those comments exist, and adding them if they don't. I think the check must be failing as it just adds them repeatedly. Above those comments is the _md5hash and _version comments, not sure if those are conflicting here or not.

While these are just comments, it really litters the file up quickly if you make a lot of changes.

**Comment by oktalz** [comment]
@thegagne thx for reporting this, 
indeed there were a bug in underlying library that caused this.

I believe that today's new release (v2.4.3) have already included a fix fro this.

**Comment by kevev** [comment]
This is still happening in latest version: v2.7.2 3d8f41f

# _version=483
# Dataplaneapi managed File
# changing file directly can cause a conflict if dataplaneapi is running
# Dataplaneapi managed File
# changing file directly can cause a conflict if dataplaneapi is running
# Dataplaneapi managed File
