### ISSUE TITLE
AWS EC2 Autodiscovery Cookie Value

### ISSUE THREAD

**Issue by dragoangel** [haproxytech/dataplaneapi#229]
Most of settings can be set via `default-server` and will fit generated `backend` section, but use of `cookie` for header based sticky connections with `default-server` can't fit, as it not accept `%[vars]`.

Can you please additionally parse `HAProxy:Service:Cookie` or staff like that to generate `server` directive with `cookie` set in HAproxy config?

**Comment by bedis** [comment]
Hi,

You can use the "cookie dynamic" parameter:
https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#4.2-cookie

Baptiste

**Comment by dragoangel** [comment]
Hi @bedis thanks a lot for quick reply and suggestion. Looks this my solution that I missed.
