### ISSUE TITLE
api: missing a simple way to add / delete entry to the acl

### ISSUE THREAD

**Issue by f1-outsourcing** [haproxytech/dataplaneapi#241]
I get the feeling that, I maybe missed something in the api reference guide. Is it really like this that you can not add or delete an ip to an acl?

**Comment by mjuraga** [comment]
Hi, what ACLs are we talking about here? We currently have two resources: `/services/haproxy/configuration/acls` - which represent `acl` line in the configuration file and `/services/haproxy/runtime/acls` - which represent acls in the RuntimeAPI (stats socket) or the acl files.

If we are talking about the runtime ACLs, then you can use `/services/haproxy/runtime/acl_file_entries` for managing entries in acl files.

**Comment by f1-outsourcing** [comment]
Afaik from the docs, it is not possible to do one simple put/push request to update an existing acl by adding an ip.

**Comment by mjuraga** [comment]
Are we talking about dataplaneapi or haproxy here?
