### ISSUE TITLE
suggestion needed for building the package 

### ISSUE THREAD

**Issue by alfredzj** [haproxytech/dataplaneapi#244]
Hi I am Amazon Linux 2 and try to build it. However, it always stuck here:

```
go: downloading github.com/hashicorp/golang-lru v0.5.0
go build github.com/aws/aws-sdk-go-v2/service/ec2: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
make: *** [build] Error 1

```
I am using go 1.17.8. HA-Proxy version 1.5.18; Any idea?

**Comment by dkorunic** [comment]
Most likely caused by lack of memory on EC2 instance. Please try increasing the instance size.

**Comment by alfredzj** [comment]
> Most likely caused by lack of memory on EC2 instance. Please try increasing the instance size.

Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        475M     0  475M   0% /dev
tmpfs           483M     0  483M   0% /dev/shm
tmpfs           483M  472K  483M   1% /run
tmpfs           483M     0  483M   0% /sys/fs/cgroup
/dev/xvda1      8.0G  2.9G  5.2G  36% /
tmpfs            97M     0   97M   0% /run/user/1000

I am not quite sure about this. Seems that there is a lot available space.

**Comment by alfredzj** [comment]
> Most likely caused by lack of memory on EC2 instance. Please try increasing the instance size.

Thanks for the reply. I found another link with similar issue: Most likely it went OOM (out of memory). Building needs a VM of at least 2 cores and 4GB RAM at minimum.. but really AWS EC2 support is really out of scope for this project.
