### ISSUE TITLE
Help needed to run the dataplaneapi

### ISSUE THREAD

**Issue by alfredzj** [haproxytech/dataplaneapi#245]
[ec2-user]$ sudo dataplaneapi -f /etc/haproxy/dataplaneapi.hcl
sudo: dataplaneapi: command not found
[ec2-user]$ dataplaneapi
time="2022-03-04T15:40:52Z" level=fatal msg="Error saving configuration: open /etc/haproxy/dataplaneapi.hcl: permission denied"

I have followed instruction here: https://www.haproxy.com/documentation/hapee/latest/api/data-plane-api/installation/haproxy-community/

`
git clone https://github.com/haproxytech/dataplaneapi.git
cd dataplaneapi/
make build 
chmod +x build/dataplaneapi
sudo cp build/dataplaneapi /usr/local/bin/
`

Btw, I am using Amazon Linux 2 EC2 instance.

**Comment by dkorunic** [comment]
When running `sudo dataplaneapi`, if it results in _command not found_ you should:
- either modify `$PATH` variable to contain `/usr/local/bin`, ie. with:
```shell
export PATH=$PATH:/usr/local/bin
sudo dataplaneapi -f /etc/haproxy/dataplaneapi.hcl
```
- or call `sudo /usr/local/bin/dataplaneapi -f /etc/haproxy/dataplaneapi.hcl`

**Comment by alfredzj** [comment]
> When running `sudo dataplaneapi`, if it results in _command not found_ you should:
> 
> * either modify `$PATH` variable to contain `/usr/local/bin`, ie. with:
> 
> ```shell
> export PATH=$PATH:/usr/local/bin
> sudo dataplaneapi -f /etc/haproxy/dataplaneapi.hcl
> ```
> 
> * or call `sudo /usr/local/bin/dataplaneapi -f /etc/haproxy/dataplaneapi.hcl`

Yes, I have this in my $PATH but it seems not working.

[ec2-user]$ echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/go/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin

However, if I run sudo /usr/local/bin/dataplaneapi -f /etc/haproxy/dataplaneapi.hcl, I am having some other errors. 
```
time="2022-03-04T16:25:56Z" level=warning msg="Error setting up runtime client with socket: /var/run/haproxy.sock : dial unix /var/run/haproxy.sock: connect: no such file or directory"
time="2022-03-04T16:25:56Z" level=warning msg="Runtime API not configured, not using it: dial unix /var/run/haproxy.sock: connect: no such file or directory"
```

Thanks! Any suggestions on both issues?

**Comment by dkorunic** [comment]
It says that HAProxy is not responding on `/var/run/haproxy.sock`. It is either that you haven't started HAProxy or it was been configured but with wrong admin socket, not corresponding to defaults and/or what's configured in `dataplaneapi.hcl`.

**Comment by alfredzj** [comment]
> ays that HAProxy is not responding on `/var/run/haproxy.sock`. It is either that you haven't started HAProxy or it was been configured but with wrong admin socket, not corresponding to defaults and/or what's configured in `dataplaneapi`

Thanks again. Btw, do you know why command not found even I have that folder in my path?

**Comment by dkorunic** [comment]
@alfredzj Because `sudo` by default changes security context and doesn't inherit your current environment variables. The example above presumed you will do the export in **root** user shell configuration files, or that you'll run sudo with -E parameter to keep existing environment.
