### ISSUE TITLE
Adding a new server to a backend ignores ID parameter

### ISSUE THREAD

**Issue by mklokocka** [haproxytech/dataplaneapi#249]
Hey, as far as I can tell from documentation (https://www.haproxy.com/documentation/dataplaneapi/enterprise/#post-/services/haproxy/configuration/servers) I should be able to add new servers to a backend with a specified `id`. However, the `id` parameter gets ignored completely (I see it in the response from Data Plane API but it's not in the haproxy configuration).

I tested this out with versions 2.4.5, 2.4.6, and 2.5.1. Haproxy is v2.1.3.

**Comment by mjuraga** [comment]
Hi @mklokocka tnx for reporting, we will take a look at this.

**Comment by mjuraga** [comment]
This is fixed in the upstream library: https://github.com/haproxytech/client-native/commit/24714fe7548fd79923f0731215b500fe11e29e75

And will land in master soon, and will be in some of the next releases.
