### ISSUE TITLE
Support more HTTP Request Rewrite Rules

### ISSUE THREAD

**Issue by checkito** [haproxytech/dataplaneapi#25]
Hello,

Currently only limited subset of HTTP Request Rewrite Rules [are supported](https://github.com/haproxytech/models/blob/master/http_request_rule.go#L107).
Are there any plans of introducing more request modifiers, such as [set-uri](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-http-request%20set-uri),  [set-query](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-http-request%20set-query), [set-path](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-http-request%20set-path), etc.? The latter is extremely important for microservices/containerized scenarios.

Thanks in advance.

**Comment by gitforbit** [comment]
Hi @checkito 

We added support for set-uri and set-query options.
Support for set-path will be added very soon.

Kind regards

**Comment by mjuraga** [comment]
set-uri, set-query and set-path support released in [v1.2.4](https://github.com/haproxytech/dataplaneapi/releases/tag/v1.2.4)

**Comment by checkito** [comment]
Awesome! Thanks :+1:
