### ISSUE TITLE
Smartos/Illumos binary

### ISSUE THREAD

**Issue by marcheschi** [haproxytech/dataplaneapi#251]
hi 
I'm trying to compile dataplane api in Smartos (Illumos) , but I got this error:
`
# github.com/gofrs/flock
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:28:22: undefined: syscall.LOCK_EX
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:39:22: undefined: syscall.LOCK_SH
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:57:12: undefined: syscall.Flock
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:67:12: undefined: syscall.Flock
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:97:12: undefined: syscall.Flock
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:97:42: undefined: syscall.LOCK_UN
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:119:21: undefined: syscall.LOCK_EX
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:131:21: undefined: syscall.LOCK_SH
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:151:9: undefined: syscall.Flock
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:151:44: undefined: syscall.LOCK_NB
../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:151:44: too many errors
# github.com/nathanaelle/syslog5424/v2
../go/pkg/mod/github.com/nathanaelle/syslog5424/v2@v2.0.5/connector-local_other.go:10:14: undefined: ErrorNoConnecion
make: *** [Makefile:24: build] Error 2
`

Do you have any advice?
Thank you
Paolo

**Comment by marcheschi** [comment]
This is related to : 
#https://github.com/gofrs/flock/issues/53

**Comment by marcheschi** [comment]
If I do
`GOOS=illumos CGO_ENABLED=0 go build -trimpath -ldflags "-X \"main.GitRepo=https://github.com/haproxytech/dataplaneapi.git\" -X main.GitTag=v2.5.0 -X main.GitCommit=3ce6624 -X main.GitDirty=.dev.dirty -X main.BuildTime=2022-03-23T13:46:34Z" -o /root/dataplaneapi/build/dataplaneapi /root/dataplaneapi/cmd/dataplaneapi/`

it goes better:
# github.com/nathanaelle/syslog5424/v2
../go/pkg/mod/github.com/nathanaelle/syslog5424/v2@v2.0.5/connector-local_other.go:10:14: undefined: ErrorNoConnecion

but still does not work

**Comment by marcheschi** [comment]
No Why using LX zones when it is possible to go native.
I contacted Nathanaelle,  who made a patch for compiling on illumos.
https://github.com/nathanaelle/syslog5424/issues/11#issuecomment-1078646470
After updating the code from github, and copy to the right folder Now It works

Thank you
Paolo

**Comment by dkorunic** [comment]
@marcheschi There is an unknown number of possible issue with this port since it is undergoing little to no testing, at least from our side.

**Comment by marcheschi** [comment]
@dkorunic 
I understand, I see that you produce the binary for a plethora of architectures, so you test it every binary you produce? for example  ppc arm s390 ?
What I ask is only to include the possibility to compile that without any warranty, in the spirit of Open-Source, since the patches are already there.
Thank you
Paolo

**Comment by dkorunic** [comment]
@marcheschi To some extent yes, with the emphasis on popular OS/arch combinations (linux and amd64/arm64). In regards to Illumos, I don't think that will happen as compile issues with a single architecture would break the whole build/release/push pipeline, since builds have to be done all at once, given how Docker multiarch-manifests work, as well as how in general our builds work.
We really can't support and build for all and any OS/arch combination, since many of them are broken and/or some of included dependancies weren't designed for such a combination to begin with. Sadly, this is a **wontfix** case.
