### ISSUE TITLE
after update path /etc/haproxy is required

### ISSUE THREAD

**Issue by f1-outsourcing** [haproxytech/dataplaneapi#259]
I was testing the container, and all of a sudden the acl files are not loaded

[ALERT] 173/210358 (26) : parsing [/etc/haproxy/haproxy.cfg:76] : error detected while parsing ACL 'blacklistweb' : failed to open pattern file <clouds.acl>.

I can correct this easily to make the cwd /etc/haproxy

I have the impression that the default directory being read is not /etc/haproxy any more, but the current. I think this changed at least since version HAProxy version 2.2.22-16420af, released 2022/03/14

I do not think such changes should occur in minor updates.

**Comment by mjuraga** [comment]
This is an haproxy issue, so it should be reported to: https://github.com/haproxy/haproxy
