### ISSUE TITLE
HTTP response rule "del-header" is not returned

### ISSUE THREAD

**Issue by checkito** [haproxytech/dataplaneapi#26]
Hi,

assuming I have the following frontend configuration:
```
frontend http
  bind *:80
  mode http
  http-response del-header X-Powered-By
  default_backend default
```

the `http_response_rules` endpoint with `parent_name=http&parent_type=frontend` returns emtpy rule list.

Same applies to backends.

Albeit other response rules (add-header, set-header, replace-header) are returned.

**Comment by mjuraga** [comment]
Hello, thank you for your report, I can confirm this is a bug and we are working on fixing it.

**Comment by gitforbit** [comment]
Fixed with https://github.com/haproxytech/dataplaneapi/commit/dfa6c29d350f10cfa571e0f89bb30875d1a5f3d7
