### ISSUE TITLE
Wrong status code 400 when deleting non-existing transaction

### ISSUE THREAD

**Issue by leahneukirchen** [haproxytech/dataplaneapi#269]
```
% curl -X DELETE localhost:5555/v2/services/haproxy/transactions/111
{"code":400,"message":"20: transaction 111 does not exist"}
```

According to the documentation (https://www.haproxy.com/documentation/dataplaneapi/enterprise/#delete-/services/haproxy/transactions/-id- ) and general REST behavior, this should be status 404.

**Comment by mjuraga** [comment]
Thank you for the report we'll fix that in the upcoming versions.

**Comment by mjuraga** [comment]
This is fixed, and will be available in the next releases. Thank you for your report.
