### ISSUE TITLE
Support multiple ssl_certificate on frontend bindings

### ISSUE THREAD

**Issue by joachimcarrein** [haproxytech/dataplaneapi#27]
We use multiple SSL certificates for subdomain wildcards.
However the api does not allow to create a line as the following:
bind :443 name https crt domain.pem crt sub.domain.pem crt sub2.domain.pem ssl

the pem's would be for *.domain.com, *.sub.domain.com and *.sub2.domain.com
If we create multiple bind lines, it seems like HAProxy doesn't use SNI correctly, and is servers the first certificate most of the time.

**Comment by AdminHodor** [comment]
We have the same challenge. And you are right, for HAProxy to go into SNI mode, the SSL certificates have to be on the same binding line

**Comment by oktalz** [comment]
Why don't you put certs in same dir and just use ?
```
bind :443 name https crt /etc/haproxy/certs/ ssl
```

**Comment by joachimcarrein** [comment]
Right, didn't know that you could also specify a folder instead of a direct file. This does indeed work for our purpose.

**Comment by olafnorge** [comment]
For me this approach does not work.

If I send:

```json
{
	"address": "*",
	"name": "https",
	"port": 8443,
	"ssl": true,
	"ssl_certificate": "/certs/"
}
```

I get 

```json
{
    "code": 400,
    "message": "14: ERR transactionId=3e45f471-d535-4368-b9d9-235998b04633 \nline=54 msg=\"'bind *:8443' :\""
}
```

My certs are at `/certs` which looks like:

```bash
/certs # ls -lah
total 64K    
drwxr-xr-x    1 root     root        4.0K Sep 21 19:58 .
drwxr-xr-x    1 root     root          97 Sep 21 19:58 ..
-rw-r--r--    1 root     root          17 May 28 15:16 crt-list.txt # <--- list of all ther certs
-rw-r-----    1 root     root        7.0K Sep 21 19:56 example.com.combined.pem
-rw-r-----    1 root     root         527 Sep 21 19:56 example.com.combined.pem.ocsp
-rw-r-----    1 root     root         424 Aug 28 21:30 dhparam.pem
-rw-r-----    1 root     root        7.0K Sep 21 19:56 example.org.combined.pem
-rw-r-----    1 root     root         527 Sep 21 19:56 example.org.combined.pem.ocsp
-rw-r-----    1 root     root        2.6K Nov 16  2018 dummy.pem # <--- wildcard self signed cert
-rw-r-----    1 root     root        7.0K Sep 21 19:56 example.biz.combined.pem
-rw-r-----    1 root     root         527 Sep 21 19:56 example.biz.combined.pem.ocsp
-rw-r-----    1 root     root        7.0K Sep 21 19:56 example.co.uk.combined.pem
-rw-r-----    1 root     root         527 Sep 21 19:56 example.co.uk.combined.pem.ocsp
```

**Comment by olafnorge** [comment]
> For me this approach does not work.
> 
> If I send:
> 
> ```json
> {
> 	"address": "*",
> 	"name": "https",
> 	"port": 8443,
> 	"ssl": true,
> 	"ssl_certificate": "/certs/"
> }
> ```
> 
> I get
> 
> ```json
> {
>     "code": 400,
>     "message": "14: ERR transactionId=3e45f471-d535-4368-b9d9-235998b04633 \nline=54 msg=\"'bind *:8443' :\""
> }
> ```
> 
> My certs are at `/certs` which looks like:
> 
> ```shell
> /certs # ls -lah
> total 64K    
> drwxr-xr-x    1 root     root        4.0K Sep 21 19:58 .
> drwxr-xr-x    1 root     root          97 Sep 21 19:58 ..
> -rw-r--r--    1 root     root          17 May 28 15:16 crt-list.txt # <--- list of all ther certs
> -rw-r-----    1 root     root        7.0K Sep 21 19:56 example.com.combined.pem
> -rw-r-----    1 root     root         527 Sep 21 19:56 example.com.combined.pem.ocsp
> -rw-r-----    1 root     root         424 Aug 28 21:30 dhparam.pem
> -rw-r-----    1 root     root        7.0K Sep 21 19:56 example.org.combined.pem
> -rw-r-----    1 root     root         527 Sep 21 19:56 example.org.combined.pem.ocsp
> -rw-r-----    1 root     root        2.6K Nov 16  2018 dummy.pem # <--- wildcard self signed cert
> -rw-r-----    1 root     root        7.0K Sep 21 19:56 example.biz.combined.pem
> -rw-r-----    1 root     root         527 Sep 21 19:56 example.biz.combined.pem.ocsp
> -rw-r-----    1 root     root        7.0K Sep 21 19:56 example.co.uk.combined.pem
> -rw-r-----    1 root     root         527 Sep 21 19:56 example.co.uk.combined.pem.ocsp
> ```

Nevermind, I copied the certs into a blank folder and it works now for me.
