### ISSUE TITLE
Wrong address when adding an ipv6 server to a backend

### ISSUE THREAD

**Issue by guillaumeclair** [haproxytech/dataplaneapi#271]
Hello, all.

Weeks ago, I posted an issue about ipv6 frontends that has been solved in release 2.6.1. The problem was in the parsing of ipv6 address. Now It seems that there is a similar issue on servers.

Condition to reproduce :

**curl -X POST --user user:pass -H "Content-Type: application/json" -d '{"name": "backend_10.234.168.188_5752_http_000", "mode":"http", "balance": {"algorithm":"roundrobin"}}' http://host:5555/v2/services/haproxy/configuration/backends?version=700** --> OK

**curl -X GET --user user:pass http://host:5555/v2/services/haproxy/configuration/backends/backend_10.234.168.188_5752_http_000**

{"_version":701,"data":{"balance":{"algorithm":"roundrobin"},"mode":"http","name":"backend_10.234.168.188_5752_http_000"}}

**curl -X POST --user user:pass  -H "Content-Type: application/json" -d '{"name": "server1", "address": "2a01:c940:a1:901::2", "port": 8080, "check": "enabled", "maxconn": 30, "weight": 100}' "http://host:5555/v2/services/haproxy/configuration/servers?backend=backend_10.234.168.188_5752_http_000&version=701**

{"check":"enabled","maxconn":30,"proxy-v2-options":null,"weight":100,"address":"2a01:c940:a1:901::2","name":"server1","port":8080}

BUT :

**curl -X GET --user user:pass "http://host:5555/v2/services/haproxy/configuration/servers/server1?backend=backend_10.234.168.188_5752_http_000"**

{"_version":702,"data":{"check":"enabled","maxconn":30,"proxy-v2-options":null,"weight":100,"address":"2a01:c940:a1:901::2:8080","name":"server1"}}

See the 'address' field ? port is attached to address, whereas It was expected to be in a separate field named 'port'.

Furthermore, this has an impact on server1 runtime properties:

**curl -X GET --user user:pass "http://host:5555/v2/services/haproxy/runtime/servers/server1?backend=backend_10.234.168.188_5752_http_000"**

{"code":500,"message":"no data for backend_10.234.168.188_5752_http_000/server1: not found"}

Can you please provide a fix for these two bugs in a future release ? Many thx.

**Comment by mjuraga** [comment]
Hi, thanks for the report, we'll look into it.

**Comment by oliwer** [comment]
I have fixed the IPv6 issue. The patch is coming soon.

On the other hand, the runtime API works fine for me. Are you sure your HAProxy gets properly reloaded after you add the server with the API?
