### ISSUE TITLE
Backend section is missing server

### ISSUE THREAD

**Issue by jpl-vitac** [haproxytech/dataplaneapi#275]
I have a backend configured as such:

```
backend test_rstp_backend
  mode tcp
  option forwardfor
  server server1 10.8.15.102:554 check
```

But when I load it using the API:

```
curl -s --user user::pw http://localhost:9998/v2/services/haproxy/configuration/backends | jq
{
  "_version": 2,
  "data": [
    {
      "forwardfor": {
        "enabled": "enabled"
      },
      "mode": "tcp",
      "name": "test_rstp_backend"
    }
  ]
}
```

Note that the server line is missing. Furthermore, the docs don't specify how to create new ones with this field.

**Comment by mjuraga** [comment]
Hi @jpl-vitac, you can fetch the servers as a standalone resource at `/v2/services/haproxy/configuration/servers?parent_type=backend&parent_name=test_rstp_backend`
