### ISSUE TITLE
Newb questions - validate dataplance.hcl or ensure it does not kill haproxy

### ISSUE THREAD

**Issue by jeffdyke** [haproxytech/dataplaneapi#276]
I hate to open this here, please point me in another spot, i have posted a similar query to reddit on r/haproxy

I have the dataplane api successfully deployed into a few haproxy integrations,  for testing.  I manage the dataplane.hcl via saltstack (i know its odd).  If i make a mistake to the dataplane configuration it will kill all haproxy threads.  should i use a `hclq` solution b/c it would barf if malformed, and i could stop a restart.  Or is there something obvious in the docs i have missed.   

Thank you, and for this software.

**Comment by jeffdyke** [comment]
Is this considered normal, if it breaks while in the `api` section of `haproxy.cfg`, for instance i had no quotes around a bare word, my fault obviously, but it took down haproxy.  I'll replicate this today and send the logs.  Have to wait until people are off of that system.  Appreciate your response.

**Comment by jeffdyke** [comment]
actually it was still on my screen, the `name` variable was not quoted. 
```
Oct 23 18:01:57 staginglb02 haproxy[489597]: configuration file /etc/haproxy/dataplane.hcl not valid: At 2:8: Unknown token: 2:8 IDENT staginglb02
Oct 23 18:01:57 staginglb02 haproxy[489595]: [NOTICE]   (489595) : haproxy version is 2.6.6-1ppa1~jammy
Oct 23 18:01:57 staginglb02 haproxy[489595]: [NOTICE]   (489595) : path to executable is /usr/sbin/haproxy
Oct 23 18:01:57 staginglb02 haproxy[489595]: [ALERT]    (489595) : Current program 'api' (489597) exited with code 1 (Exit)
Oct 23 18:01:57 staginglb02 haproxy[489595]: [ALERT]    (489595) : exit-on-failure: killing every processes with SIGTERM
Oct 23 18:01:57 staginglb02 haproxy[489595]: [ALERT]    (489595) : Current worker (489598) exited with code 143 (Terminated)
Oct 23 18:01:57 staginglb02 haproxy[489595]: [WARNING]  (489595) : All workers exited. Exiting... (1)
```
And `haproxy` went down with it.

**Comment by jeffdyke** [comment]
I caught another one of these, and it would seem what ever is forcing this
```
Oct 24 20:38:49 server01 haproxy[502571]: [ALERT]    (502571) : exit-on-failure: killing every processes with SIGTERM
```
The error is 
```
Oct 24 20:38:49 server01 haproxy[502573]: configuration file /etc/haproxy/dataplane.hcl not valid: At 43:5: error while trying to parse object within list: At 55:19: expected: IDENT | STRING | ASSIGN | LBRACE got: SUB
```
Totally understand this is my error, perhaps i should ask about this in a haproxy forum, as the `api` block is part of the core.

**Comment by mjuraga** [comment]
This is unfortunately the behaviour of the `program` section, I would suggest you start dataplaneapi as a standalone process, maybe running under `systemd` to help with this issue, in that case broken dataplaneapi configuration won't affect your haproxy process.
