### ISSUE TITLE
How to append new ip address to ACL whitelist file?

### ISSUE THREAD

**Issue by RemcoSchilder** [haproxytech/dataplaneapi#278]
I was using the following url from the DataPlaneApi to add a new entry to my whitelist(ACL) file: http://localhost:5555/v2/services/haproxy/runtime/acl_file_entries

The problem is that this doesn’t actually saves it to the file. Because when I execute the post request, which I mentioned above, the file is still empty.
The weird thing is that the post request succeeds and when I run the same url but change the http type to “GET”, it shows that the new entry has been added.
But when I restart HAProxy to see if the entry has been succesfully saved to my whitelist file, it shows an empty whitelist file.

Can someone explain to me how I append new IP addresses to my whitelist file?
For example, which endpoint do I have to use?

Greetings,
Remco

**Comment by mjuraga** [comment]
Hi @RemcoSchilder, using `runtime/*` endpoints will only do the changes in the HAProxy runtime (using the stats socket). To manage the files on the disk, you can use the `storage/` endpoints. In this case the `storage/general`.
