### ISSUE TITLE
API: user: Cannot add user to existing userlist.

### ISSUE THREAD

**Issue by toblu96** [haproxytech/dataplaneapi#279]
Hello,

I am not able to add a user to a userlist using the dataplane API. 

**HAProxy infos:**
image: haproxytech/haproxy-debian:2.6.6
HAPROXY_BRANCH: 2.6
HAPROXY_MINOR: 2.6.6
HAPROXY_SHA256: d0c80c90c04ae79598b58b9749d53787f00f7b515175e7d8203f2796e6a6594d

**Current configuration file** (haproxy.cfg):
```
global
  master-worker
  stats socket /var/run/api.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
  log stdout format raw local0 info

defaults
  mode http
  log global
  timeout connect 5s
  timeout client 5s
  timeout server 5s

userlist haproxy-dataplaneapi
  user admin insecure-password admin

frontend myfrontend
  bind :80
  default_backend webservers

backend webservers
  server s1 web1:8080 check
  server s2 web2:8080 check
  server s3 web3:8080 check

program api
  command /usr/bin/dataplaneapi --host 0.0.0.0 --port 4444 --haproxy-bin /usr/local/sbin/haproxy --config-file /usr/local/etc/haproxy/haproxy.cfg --reload-cmd "kill -SIGUSR2 1" --reload-delay 5 --userlist haproxy-dataplaneapi
  no option start-on-reload
```

**Steps to reproduce** (all requests are handled within the same transaction):
1. Add new userlist
![image](https://user-images.githubusercontent.com/25683183/203069038-449f8b76-a568-48e4-a0e5-4cbce170dd34.png)

2. Add group to userlist
![image](https://user-images.githubusercontent.com/25683183/203069080-4395c3a3-1553-46bd-9715-063a26bff5a7.png)

3. Add user to userlist
![image](https://user-images.githubusercontent.com/25683183/203069107-d2ce5c6f-2fe5-4121-ae97-0033614db857.png)

Current userlist config after API calls:
```
userlist custom-userlist
  group projectgroup1
```
Expected userlist config:
```
userlist custom-userlist
  group projectgroup1
  user admin insecure-password admin groups projectgroup1
```

It seems that the API responds with a 201 (created) even though the user never ends up in the configuration and the file is never updated.

A direct request to this user list also returns an empty list.
![image](https://user-images.githubusercontent.com/25683183/203068940-0426629f-2ed8-4466-9605-73a2b63cc505.png)

Is there a mistake on my end or is this a bug?

Thanks in advance, any help appreciated.

**Comment by mjuraga** [comment]
Hi, this should be fixed with: https://github.com/haproxytech/dataplaneapi/commit/04f7b83ca8e512b40a15c18c4c85ec0e03ecfad9 and will be included in the next releases.

**Comment by toblu96** [comment]
Hi @mjuraga, was able to test the new version today. Works perfectly fine, thanks a lot!
