### ISSUE TITLE
"Panic runtime error: invalid memory address or nil pointer dereference" when using `Add a new payload`

### ISSUE THREAD

**Issue by Andrew-Velychenko** [haproxytech/dataplaneapi#280]
When I start HAProxy with DataPlane, `Add a new payload` works fine for a while. But after some time I get this response "_The remote server returned an error: (500) Internal Server Error._". 
And in the log file I get this message:
level=error msg="Panic runtime error: invalid memory address or nil pointer dereference" stack_trace="\n/usr/local/go/src/runtime/panic.go:259 panicmem\n/home/mjuraga/projects/go/pkg/mod/github.com/haproxytech/client-native/v4@v4.0.1/runtime/version.go:66 (*HAProxyVersion).IsBiggerOrEqual\n/home/mjuraga/projects/go/pkg/mod/github.com/haproxytech/client-native/v4@v4.0.1/runtime/runtime_client.go:142 (*client).IsVersionBiggerOrEqual\n/home/mjuraga/projects/go/pkg/mod/github.com/haproxytech/client-native/v4@v4.0.1/runtime/runtime_client.go:747 (*client).AddMapPayloadVersioned\n/home/mjuraga/projects/haproxytech/release/dataplaneapi/handlers/map.go:195 (*MapsAddPayloadRuntimeMapHandlerImpl).Handle\n/home/mjuraga/projects/haproxytech/release/dataplaneapi/operations/maps/add_payload_runtime_map.go:83 (*AddPayloadRuntimeMap).ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/operation.go:28 NewOperationExecutor.func1\n/usr/local/go/src/net/http/server.go:2109 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:78 NewRouter.func1\n/usr/local/go/src/net/http/server.go:2109 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/redoc.go:72 Redoc.func1\n/usr/local/go/src/net/http/server.go:2109 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/spec.go:46 Spec.func1\n/usr/local/go/src/net/http/server.go:2109 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 (*Cors).Handler.func1\n/usr/local/go/src/net/http/server.go:2109 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/haproxytech/release/dataplaneapi/adapters/adapters.go:148 ConfigVersionMiddleware.func1.1\n/usr/local/go/src/net/http/server.go:2109 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/haproxytech/release/dataplaneapi/adapters/adapters.go:115 RecoverMiddleware.func1.1\n/usr/local/go/src/net/http/server.go:2109 HandlerFunc.ServeHTTP\n/usr/local/go/src/net/http/server.go:2947 serverHandler.ServeHTTP\n/usr/local/go/src/net/http/server.go:1991 (*conn).serve\n/usr/local/go/src/runtime/asm_amd64.s:1594 goexit"

Restart HAProxy with DataPlane helps, but only for a while. So I have to restart HAProxy with DataPlane again and again.

**Comment by mjuraga** [comment]
Hi @Andrew-Velychenko thank you for the report. What do you mean by `Add a new payload`, which endpoints are you calling on the API?

**Comment by mjuraga** [comment]
This should be fixed in the latest versions.
