### ISSUE TITLE
Renaming by replacing frontend not working

### ISSUE THREAD

**Issue by bartweber** [haproxytech/dataplaneapi#281]
Problem can be reproduced by the following steps.
1. Create frontend:
   ```
   POST http://<host>:<port>/v2/services/haproxy/configuration/frontends?version=<version>
   Authorization: Basic <username> <password>
   Content-Type: application/json
   
   {
     "name": "foo",
     "mode": "http"
   }
   ```
2. Replace frontend:
   ```
   PUT http://<host>:<port>/v2/services/haproxy/configuration/frontends/foo?version=<version>
   Authorization: Basic <username> <password>
   Content-Type: application/json
   
   {
     "name": "bar",
     "mode": "http"
   }
   ```

The configuration after step 1:
```
frontend foo
  mode http
```
The configuration after step 2:
```
frontend foo
  mode http
```
Expected the configuration after step 2 to be:
```
frontend bar
   mode http
```
The response of the request in step 2 has status 202. The request seems to be ignored. The same results can be achieved by using transactions.

**Comment by mjuraga** [comment]
Hi @bartweber this is by design, we don't allow renaming of sections as they are used as identifiers on the API URLs. To rename, please delete and create the frontend again.
