### ISSUE TITLE
HA Proxy Dataplane ACL Runtime does not persistent in ACL file

### ISSUE THREAD

**Issue by Rezkmike** [haproxytech/dataplaneapi#287]
**Current Problem :** 

Im using this ```/v2/services/haproxy/runtime/acl_file_entries``` endpoint to add entries to ACL files. However, the newly added ACL list doesnt added into the ACL file.

**Expected Behavior :**

After ran the API, the newly added ACL data apprear in the ACL file

**Question :**

How to make the changes persistent in the ACL file?

**Comment by mjuraga** [comment]
Hi @Rezkmike the `runtime` endpoints deal only with calls to the HAProxy's runtime API (configured stats socket) and they are only changed in memory and don't persist on the disk.

We currently don't have a storage endpoint for the ACLs but as a workaround you can use `/services/haproxy/storage/general` endpoint to store any file in the configured storage directory. You can then reference those files in the HAProxy configuration.

**Comment by Rezkmike** [comment]
I created custom API to update and delete FQDN from the ACL file, and run hot-reload to take effect the newly added FQDN in the ACL file.

Thanks ! @mjuraga
