### ISSUE TITLE
Haproxy can support udp protocol but dataplaneapi cannot

### ISSUE THREAD

**Issue by cylonchau** [haproxytech/dataplaneapi#288]
haproxy 2 already support udp protocol, but add a udp frontend with dataplaneapi, occurred following error

the dataplaneapi cannot support udp protocol

```
mode in body should be one of [http tcp]"
```

```json
{
  "default_backend": "test_backend1",

  "maxconn": 2000,
  "mode": "udp",
  "name": "test_frontend3232"
}
```

**Comment by dkorunic** [comment]
@cylonchau No it doesn't, are you referring to some other proxy? To refer to the documentation: https://docs.haproxy.org/2.7/configuration.html#4.2-mode. It is either HTTP or TCP, generic UDP proxying is not supported.

**Comment by cylonchau** [comment]
Get, Thank you for you timely reply.
