### ISSUE TITLE
Dataplane API and docker (Error reading userlist dataplane-api userlist in conf: section missing")

### ISSUE THREAD

**Issue by duusty** [haproxytech/dataplaneapi#29]
Hello everyone,

iam running the haproxy container (version 2.0.6) and trying to set up the data plane api with it.
I have edited the docker-entry to download the latest data plane version and start it via the
haproxy program section inside the config.

Unfortunately I have a problem with accessing the userlist and haproxy reports the following warning when starting.

> time="2019-09-23T12:42:48Z" level=warning msg="Runtime API not configured, not using it"

When I use the same config on a normal linux host with haproxy installed everything is working. I think it could be an issue with the socket inside the docker container and the resulting warning message i have received.

Are there any "best practices" how to set up the new api with the docker version of haproxy?

```
global
    log stdout format raw local0 info
    stats socket ipv4@0.0.0.0:9999 level admin
    stats socket /var/run/haproxy.sock mode 666 level admin
    stats timeout 30s
    master-worker 
    daemon


defaults
    log global
    option http-server-close
    option httplog
    mode http
    timeout http-request 5s
    timeout connect 5s
    timeout server 10s
    timeout client 30s



listen stats
    bind 0.0.0.0:1454
    mode http
    option http-use-htx
    http-request use-service prometheus-exporter if { path /metrics }
    stats enable
    stats hide-version
    stats uri /stats
    http-request set-log-level silent


userlist dataplane-api
    user admin password ****

program api
    command dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "service haproxy reload" --reload-delay 5 --userlist dataplane-api
    no option start-on-reload



frontend proxy_in
    bind ipv4@0.0.0.0:80
    default_backend proxy_out

backend proxy_out
    server backend_01 0.0.0.0:443 ssl verify none check weight 1 maxconn 3000
```

**Comment by olafnorge** [comment]
@duusty my config looks like this and I create it just before I śtart haproxy.

```
# _version=1

global
# in order to work chroot, user, and group must be existent beforehand
#  chroot /var/lib/haproxy
#  user haproxy
#  group haproxy 
  master-worker no-exit-on-failure
  mworker-max-reloads 5
  pidfile /run/haproxy.pid
# use following line if user and group exist
#  stats socket /run/haproxy.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
# otherwise use this line
  stats socket /run/haproxy.sock mode 660 level admin expose-fd listeners
  log stdout format raw daemon err

defaults
  mode http
  log global

userlist dataplane-api
  user controller insecure-password controller

program api
  # in a container we use 'kill -SIGUSR2 1' to reload haproxy
  # means reload command is '--reload-cmd="kill -SIGUSR2 1"'
  # also haproxy's binary should be in the PATH so we use '--haproxy-bin=haproxy' here
  command dataplaneapi --host=127.0.0.1 --port=5555 --config-file=/usr/local/etc/haproxy/haproxy.cfg --userlist=dataplane-api --haproxy-bin=haproxy --reload-delay=5 --reload-cmd="kill -SIGUSR2 1" --reload-retention=5 --show-system-info --log-to=stdout --log-level=error --log-format=text
  no option start-on-reload

```

Hope that helps to get you going forward.

**Comment by jiki974** [comment]
I was also facing the same issue, it was due to the CR chars added by windows : https://discourse.haproxy.org/t/haproxy-dataplaneapi-error/4223/3

After executing dos2unix on the haproxy.cfg everything works now.

**Comment by oktalz** [comment]
Hi @jiki974,
thx for reporting this. this might be the issue with config-parser package that dataplaneapi is using. 
I will try to see if that is the case.

**Comment by Fireant456** [comment]
> After executing dos2unix on the haproxy.cfg everything works as excpected.

I LOVE YOU, been battling with this for a while and HAProxyTech has been absolutely useless in assisting to find the solution...

**Comment by janstadt** [comment]
Im still hitting this issue. The latest haproxytech/haproxy-debian docker image just immediately exits. I ran dos2unix on the cfg file before building my own image and copying the cfg file in there. Do you guys run dos2unix as a run step inside the Dockerfile as well after copying?

I also saw that other issue about the incorrect --config-file location in the documentation and have since updated it. With this code below commented out the app runs but i dont have any dataplane.

```
userlist haproxy-dataplaneapi
  user admin insecure-password mypassword

program api
  command /usr/bin/dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /usr/local/etc/haproxy/haproxy.cfg --reload-cmd "kill -SIGUSR2 1" --reload-delay 5 --userlist hapee-dataplaneapi
  no option start-on-reload
```

This is what im running. 
` docker run -d --name my-running-haproxy --expose 5555 -p 6969:80 my-haproxy`

When running the validation step on the cfg file it also passes. Really confused by this. I had thought it was because i was mounting the cfg volume into the base container at first but it still doesnt work when just building my own container.

**Comment by Ne00n** [comment]
Any ideas on this? Running into this with the latest dataplane api and haproxy 2.8
