### ISSUE TITLE
Dataplaneapi won't start

### ISSUE THREAD

**Issue by quotto33** [haproxytech/dataplaneapi#290]
I installed on ubuntu following these instructions:

https://www.haproxy.com/documentation/hapee/latest/api/data-plane-api/installation/haproxy-community/

When I try to start it: sudo dataplaneapi -f /etc/haproxy/dataplaneapi.hcl

it never starts. Just a flashing cursor on a blank line. Any suggestions? Here is my config file:

config_version = 2

name = "ip-172-31-63-16"

mode = "single"

dataplaneapi {
  host = "172.31.63.16"
  port = 5566

  user "admin" {
    insecure = true
    password = "xxxxxxxxxxxxxx"
  }

  transaction {
    transaction_dir = "/tmp/haproxy"
  }

  advertised {}
}

haproxy {
  config_file = "/etc/haproxy/haproxy.cfg"
  haproxy_bin = "/usr/sbin/haproxy"

  reload {
    reload_delay    = 5
    reload_cmd      = "systemctl reload haproxy"
    restart_cmd     = "systemctl restart haproxy"
    status_cmd      = "systemctl status haproxy"
    reload_strategy = "custom"
  }
}

**Comment by davhdavh** [comment]
>Just a flashing cursor on a blank line

That is starting, use Curl to try to connect to it
