### ISSUE TITLE
Unable to configure intermediate ca

### ISSUE THREAD

**Issue by stevenmccormack** [haproxytech/dataplaneapi#291]
I am having trouble to configure the full certificate chain.  When I set up the following, dataplane api works and is using the correct certificate, but the chain is not visible in the browser, so every intermediate cert needs to be trusted by the client:

```
tls {
    tls_host          = "0.0.0.0"
    tls_port          = 6000
    tls_certificate   = "/etc/haproxy/ssl/cert.pem"
    tls_key           = "/etc/haproxy/ssl/cert.key"
    tls_listen_limit  = 10
    tls_keep_alive    = "1m"
    tls_read_timeout  = "10s"
    tls_write_timeout = "10s"
  }
```
I also tried to supply a concatenated file (cert+intermediate+root) instead of _/etc/haproxy/ssl/cert.pem_. This did not change the result. 
I have seen that there is a **tls_ca** parameter in the [full configuration example](https://github.com/haproxytech/dataplaneapi/blob/master/configuration/examples/example-full.hcl). But this seems to activate client certificate authentication, which is not what I want. 
Is there any way to configure the ca chain?

**Comment by dkorunic** [comment]
Hi @stevenmccormack, we are using `tls.LoadX509KeyPair()` to load x509 certificate in PEM format and that function from Golang `tls` library will load leaf certificate and everything else in the chain (intermediate and root certificate) that has been appended in the file, each following the other. Just concatenating leaf, intermediates and root certificates in PEM format to a final file should be sufficient. Can you please use `openssl s_client -connect IP:tls_port -showcerts` and show what you get when you follow the above steps?
