### ISSUE TITLE
about design issue

### ISSUE THREAD

**Issue by cylonchau** [haproxytech/dataplaneapi#292]
Hi haproxy group!

I have two question about design

### q1: The structural models.Backend or models.Frontend, models.Server etc.. for example Port attribute or ConnectTimeout type is int64 pointer, why designed like this. 

If get a server  with cilent-sdk and compare other server, the Port value is equal, but these two server always no equal, because the pointer values different.

I think the port attribute and other int type attribute, unnecessary designed pointer type. Due to the port range  is 1-65536, the int type fulfill requirement.

### q2: The models.Server attribute `connect_timeout`  is dataplane api return the json type, and the go type is `ConnectTimeout *int64 `json:"connect_timeout,omitempty"` . why designed like this. 

If get a server via dataplane api, convert the json string to go struct, but the name diffrent, so always false (json to interface to struct, finally is map to go struct), because is haproxy has backend then return `{version:"", data:[...........]}` , if haproxy backend is null, then  `{version:"", data:[]}`, at this time,  type is diffrent (ok is string, failed is `[]` )

Use map to go struct with `github.com/mitchellh/mapstructure`, due to connect_timeout and ConnectTimeout is diffrent, then error.

```

* '[0]' has invalid keys: connect_timeout
* '[1]' has invalid keys: connect_timeout
* '[2]' has invalid keys: connect_timeout
[]
```

**Comment by mjuraga** [comment]
Unfortunately this is because of our validation methods in the generated part of the code. Sometimes we need to have required fields, and we need to check whether they've been set or not. In some cases those fields are int and value 0 (default nil value for int type) is a valid one. So we need to know whether the user wanted to set the 0 value or he didn't send the value at all (doesn't want an option to be set). That's why those fields are pointers, so we can differentiate between 0 value and nil value.

**Comment by cylonchau** [comment]
> Unfortunately this is because of our validation methods in the generated part of the code. Sometimes we need to have required fields, and we need to check whether they've been set or not. In some cases those fields are int and value 0 (default nil value for int type) is a valid one. So we need to know whether the user wanted to set the 0 value or he didn't send the value at all (doesn't want an option to be set). That's why those fields are pointers, so we can differentiate between 0 value and nil value.

Thank you @mjuraga  I understand, but the struce contain a pointer port type, then compare two struct always diffrent. example

```go
port := int(64) // suppose port address is 0x00001
models.Port{
   Port: &port 
}

port2 := getPort()  // suppose port.Port address is 0x00002

// compare
0x00002 != 0x00001 // always diff, but the value is equal

```

I think port 0 is a invalied number, nil and 0 there is no difference.

**Comment by cylonchau** [comment]
Thank you @mjuraga
