### ISSUE TITLE
Error in --restart-cmd

### ISSUE THREAD

**Issue by vandrovisky** [haproxytech/dataplaneapi#296]
I detected a bug referring to the "--restart-cmd" field of the dataplane api
when removing this variable from the api program, the system requires it to be allocated, as shown in the error below:
configuration error: the custom reload strategy requires these options to be set: ReloadCmd, RestartCmd

Now, when appending the --restart-cmd variable with any type of command to restart the system, it generates the error below:

Successfully copied 2.56kB to my-running-haproxy:/usr/local/etc/haproxy/haproxy.cfg
[root@localhost ~]# docker start -i my-running-haproxy
[NOTICE] (1) : New program 'api' (8) forked
[NOTICE] (1) : New worker (9) forked
[NOTICE] (1) : Loading success.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x10d9a9b]

goroutine 1 [running]:
github.com/haproxytech/dataplaneapi.SyncWithFileSettings(0xc0000ef080, 0xc000050370?)
github.com/haproxytech/dataplaneapi/dataplaneapi_configuration.go:38 +0xfb
main.startServer(0xc000370a00)
github.com/haproxytech/dataplaneapi/cmd/dataplaneapi/main.go:137 +0x7f2
main.main()
github.com/haproxytech/dataplaneapi/cmd/dataplaneapi/main.go:59 +0x3d
[NOTICE] (1) : haproxy version is 2.7.4-d28541d
[NOTICE] (1) : path to executable is /usr/local/sbin/haproxy
[ALERT] (1) : Current program 'api' (8) exited with code 2 (Exit)
[ALERT] (1) : exit-on-failure: killing every processes with SIGTERM
[ALERT] (1) : Current worker (9) exited with code 143 (Terminated)
[WARNING] (1) : All workers exited. Exiting... (2)

tested both in debian and ubuntu containers
the haproxy.cfg file is below:

GNU nano 2.3.1 File: haproxy.cfg

global
log /dev/log local0
log /dev/log local1 notice
chroot /var/lib/haproxy
user haproxy
group haproxy
master worker
daemon

userlist haproxy-dataplaneapi
user admin insecure-password adminpwd

program api
command /usr/bin/dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /usr/local/etc/haproxy/hapro$
no option start-on-reload

defaults
global log
mode http
option httplog
option dontlognull
connect timeout 5000
client timeout 50000
server timeout 50000

frontend http_front
bind *:80
default_backend http_back

backend http_back
balance roundrobin
server server1 127.0.0.1:8234
server server2 127.0.0.1:8323.

**Comment by vandrovisky** [comment]
I was informed that the problem has been found and will come up in a next update

**Comment by mjuraga** [comment]
Hi @vandrovisky this has been fixed with: https://github.com/haproxytech/dataplaneapi/commit/83b7655422e1b2b3095a3f4e01da1552d1a4826a and a new version is coming soon.

**Comment by vandrovisky** [comment]
Hey ! Thanks for the feedback
