### ISSUE TITLE
Backup files on Config directory not   backups_dir

### ISSUE THREAD

**Issue by cdstg** [haproxytech/dataplaneapi#298]
I m using version HAProxy Data Plane API v2.7.3 763edd3 and have configured
transaction {
    transaction_dir = "/tmp/haproxy"
    backups_number  = 30
    backups_dir     = "/data/haproxy/confback"
  }

what is happening  that the the  /data/haproxy/confback  only has the haproxy.cfg.lkg file in it the actual version backups are still in

/etc/haproxy eg 
-rw-r--r--   1 root root 3782 Apr  5 09:45 haproxy.cfg
-rw-r--r--   1 root root 3812 Apr  4 18:17 haproxy.cfg.74
-rw-r--r--   1 root root 3777 Apr  4 18:17 haproxy.cfg.75
-rw-r--r--   1 root root 3812 Apr  4 18:19 haproxy.cfg.76
-rw-r--r--   1 root root 3815 Apr  5 09:41 haproxy.cfg.77
-rw-r--r--   1 root root 3784 Apr  5 09:43 haproxy.cfg.79
-rw-r--r--   1 root root 3817 Apr  5 09:45 haproxy.cfg.81

maybe its a miss understanding of the    backups_dir  purpose ?

**Comment by mjuraga** [comment]
Hi @cdstg, thank you for the report, this is fixed with: https://github.com/haproxytech/dataplaneapi/commit/8fda41a2a94fda0dc8b9f5692a492af70d5adb05 and it will be included in one of the next versions.

**Comment by mjuraga** [comment]
Hi, this has been released in https://github.com/haproxytech/dataplaneapi/releases/tag/v2.7.4
