### ISSUE TITLE
Manage SPOE config files

### ISSUE THREAD

**Issue by bedis** [haproxytech/dataplaneapi#3]
Would be cool to manage the SPOE config file through the dataplane api

**Comment by bedis** [comment]
It's already in there!!!
https://github.com/haproxytech/dataplaneapi/blob/master/handlers/filter.go

**Comment by amelhusic** [comment]
Hi @bedis 

We added support to manage SPOE in https://github.com/haproxytech/dataplaneapi/commit/70e0dd2d73e06bef4fe222514bdad81e49a56724
