### ISSUE TITLE
Add options 'send-proxy' and 'send-proxy-v2' for a server at a backend

### ISSUE THREAD

**Issue by olafnorge** [haproxytech/dataplaneapi#30]
In order to properly pass through TCP traffic through a couple of load balancers it is necessary for me to be able to add both options `send-proxy` and `send-proxy-v2` to a server line in a backend section.

F.E.

```
backend smtp
  server smtp smtp:10025 check inter 2500 send-proxy

backend imap
  server imap imap:10143 check inter 2500 send-proxy-v2
```

**Comment by mjuraga** [comment]
Thank you for your feedback, we will add those options in the future version.

**Comment by gitforbit** [comment]
Hi @olafnorge 

We added options `send-proxy` and `send-proxy-v2` in https://github.com/haproxytech/dataplaneapi/commit/9606643f6be703cb4840b508e48b2b229232fcf2

Kind Regards,

**Comment by olafnorge** [comment]
Great, thanks a lot. Do you plan a new release soonish?

**Comment by mjuraga** [comment]
Yes, probably next week.

**Comment by olafnorge** [comment]
:+1:
