### ISSUE TITLE
ca-verify-file not supported

### ISSUE THREAD

**Issue by jenspopp** [haproxytech/dataplaneapi#302]
I use the ca-verify-file in bind directive. It seems this is not supported in dataplaneapi, "get" does not return it and a "put" removes it from config file. Are there any plans to add this?

**Comment by mjuraga** [comment]
Hi @jenspopp this is a bug, and will be fixed in some of the future patch releases.

**Comment by mjuraga** [comment]
This has been added in the recent versions.
