### ISSUE TITLE
HTTP check that uses the OPTIONS method cannot be created

### ISSUE THREAD

**Issue by razvanIncrys** [haproxytech/dataplaneapi#304]
I tried to use the OPTIONS method to create a check when adding a backend, for example if we use with "check": "enabled","method": "OPTIONS", "maxconn": 30, "weight": 100}' this will add the backend but without check "option httpchk OPTIONS / HTTP/1.1".
If we try to create the backend with httpchk using, for example, the HEAD method, the backend will be created with "option httpchk HEAD / HTTP/1.1"
Also, I tried to create an HTTP check that uses the OPTIONS method using the 'Add a new HTTP check' endpoint (POST /services/haproxy/configuration/http_checks) and although the response shows success, the HTTP check is not created.

Has anyone encountered this problem before, is there a solution

Thank you

**Comment by mjuraga** [comment]
Hi @razvanIncrys if you are trying to get something like:

`option httpchk OPTIONS / HTTP/1.1`

You should add something like this to your backend endpoint:

```json
{
  "mode": "http",
  "name": "my-backend",
  "adv_check": "httpchk",
  "httpchk_params": {
    "method": "OPTIONS",
    "version": "HTTP/1.1",
    "uri": "/"
  }
}
```

Unfortunately there is a bug in specification that currently won't allow you to add OPTIONS method here, we'll fix it, but for now workaround is not to specify the `method` field at all, as this is using `OPTIONS` by default under the hood as stated here: http://docs.haproxy.org/dev/configuration.html#4.2-option%20httpchk

**Comment by hdurand0710** [comment]
Hi @razvanIncrys ,

Please note that this issue has been fixed in the following [commit](https://gitlab.int.haproxy.com/haproxy-controller/dataplaneapi/-/commit/d0bc06002aec8ad0e08501ef9892927b5ba778ef)

Best regards
