### ISSUE TITLE
Any debian package planned?

### ISSUE THREAD

**Issue by HanXHX** [haproxytech/dataplaneapi#307]
Hi team!

Can you provide a debian package (.deb) please?

That would be amazing!

Cheers,

Emilien

**Comment by fatchan** [comment]
Haproxy packages for debian are available here: [haproxy.debian.net/](https://haproxy.debian.net/)

**Comment by HanXHX** [comment]
Hi @fatchan 

No packages for dataplaneapi in => https://haproxy.debian.net/pool/main/ and the haproxy package does not provide it too.

**Comment by dkorunic** [comment]
@HanXHX The task is in the queue, I'll let you know as soon as we have it ready for the next release.

**Comment by HanXHX** [comment]
Wow great news @dkorunic! Thanks for the update. :rocket:
