### ISSUE TITLE
dgram_binds using name from payload instead of log_forward from query

### ISSUE THREAD

**Issue by k-kingsley** [haproxytech/dataplaneapi#313]
When trying to add a new dgram_binds to an existing log_forward i am seeing a behavior where the name from the payload to be assigned to the dgram_binds is being used to search for the log forwarder instead of the log_forward query parameter being used.

query:
`/v2/services/haproxy/configuration/dgram_binds?log_forward=dev_10514_log&transaction_id=<transaction_id>`

payload:
```
{
    "name": "test",
    "address": "0.0.0.0",
    "port": 5016
}
```

return message:
```
{
    "code": 400,
    "message": "11: log-forward test does not exist"
}
```

log forwarder in config:
```
log-forward dev_10514_log
  maxconn 100000
```

**Comment by mjuraga** [comment]
Hi @k-kingsley, thanks for the bug report. We fixed this and new releases `v2.6.5`, `v2.7.8` and `v2.8.4` will be including these fixes.
