### ISSUE TITLE
Question: How to add IPs to ACL file

### ISSUE THREAD

**Issue by croessner** [haproxytech/dataplaneapi#315]
Hi,

I have installed the dataplaneapi. In my /etc/haproxy/haproxy.cfg there does exist something simple like this:

```
frontend imaps from defaults_1
  mode tcp
  bind 134.255.226.248:993
  bind [2a05:bec0:28:1:134:255:226:248]:993
  acl BLACKLIST src -f /etc/haproxy/blacklist
  tcp-request connection reject if BLACKLIST
  option tcplog
  default_backend imaps
```

I want to add IPs with the API to the file, but I am absolutely not able to find documentaion or examples on how to do this. There exists one issue here (closed) that asked a similar question and the answer was to use /storage/general for this purpose.

Is there somebody who might be able to give a simple curl example on how to add an IP?

And: If adding entries to a such a file, does it require a reload?

Many thanks in advance.

**Comment by fatchan** [comment]
Use a map file e.g.
```
acl BLACKLIST src,map_ip(/etc/haproxy/map/blacklist.map) -m found
```

Then you can add/remove map entries during runtime, no reload required:
https://www.haproxy.com/documentation/dataplaneapi/community/#post-/services/haproxy/runtime/maps_entries
https://www.haproxy.com/documentation/dataplaneapi/community/#delete-/services/haproxy/runtime/maps_entries/-id-

**Comment by croessner** [comment]
First of all thanks for your answer.

I have done this in the meantime and it works. Only question that is left over is, how to get these map entries persistent over restarts/reloads?

I have done a cron job with show map... > mapfile as a workaround, because it was impossible to me to figure out, how this works with prepare map/commit map. My result was always a cleard map at the end.

If you could give a little hint here, that would be very nice.

**Comment by mjuraga** [comment]
Hi @croessner you can actually do by enabling `update_map_files` option in `dataplaneapi.yaml` under `dataplaneapi/resources` section and set an update period with `update_map_files_period`.

You can check the example here: https://github.com/haproxytech/dataplaneapi/blob/master/configuration/examples/example-full.yaml

This feature will do exactly what you are doing with the cron job.

**Comment by croessner** [comment]
Thank you very much
