### ISSUE TITLE
Error on fetching stats info from endpoint v2/services/haproxy/stats/native

### ISSUE THREAD

**Issue by nandu506tvm** [haproxytech/dataplaneapi#321]
{"code":500,"message":"runtime error: index out of range [32] with length 1: /home/runner/go/pkg/mod/github.com/haproxytech/client-native/v5@v5.1.1/runtime/stats.go:56 (*SingleRuntime).GetStats"}

[root@localhost ~]# haproxy -v
HA-Proxy version 2.0.7 2019/09/27 - https://haproxy.org/
[root@localhost ~]# dataplaneapi -v
HAProxy Data Plane API v2.9.0 91da11d

Build from: https://github.com/haproxytech/dataplaneapi
Build date: 2023-12-08T14:53:01Z

Am i missing something here ? All other API calls seems to be working

**Comment by mjuraga** [comment]
Hi, sorry for the late response, this is confirmed as a bug and we are working on a fix for it.
