### ISSUE TITLE
Replacing multiple servers in a single dataplane call?

### ISSUE THREAD

**Issue by victornor** [haproxytech/dataplaneapi#334]
I have a very large list of servers on a project, which regularly needs to be updated.
Based on the api documentation, it looks like i have to do one call for each server replacement.
Is there any way to do one call to set an array of servers and discard the current ones in a single call?

**Comment by mjuraga** [comment]
Hi @victornor, we are currently development for v3.0 of dpapi which would solve this issue. We will be doing some breaking changes on the API to allow us changing this.

**Comment by victornor** [comment]
> Hi @victornor, we are currently development for v3.0 of dpapi which would solve this issue. We will be doing some breaking changes on the API to allow us changing this.

Perfect, thank you!
