### ISSUE TITLE
Error setting up spoe: failed to read configuration

### ISSUE THREAD

**Issue by truck0321** [haproxytech/dataplaneapi#341]
I have an Haproxy Docker container that bind mounts to an NFS share containing the config files.  
NFS has been causing some unrelated issues so I configured the mount to use CIFS.   I can confirm that I can read and write to the share from within a busybox container that has the same bind mounts but the haproxy container just errors out with the below message when starting it.  

[NOTICE]   (1) : New program 'api' (8) forked
[NOTICE]   (1) : New worker (9) forked
[NOTICE]   (1) : Loading success.
time="2024-07-30T17:00:42Z" level=fatal msg="error setting up spoe: failed to read configuration: cannot read /etc/haproxy/spoe/.dataplaneapi1705250482"
[NOTICE]   (1) : haproxy version is 3.0.2-a45a8e6
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (1) : Current program 'api' (8) exited with code 1 (Exit)
[ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
[ALERT]    (1) : Current worker (9) exited with code 143 (Terminated)
[WARNING]  (1) : All workers exited. Exiting... (1)

This is running on an Ubuntu 20.04 fully updated server with haproxy version '3.0.2-a45a8e6'.  I have another instance using the NFS share and I don't see any files in /etc/haproxy/spoe so I'm not sure what this is.

**Comment by smeroth** [comment]
Hello

From what you describe, i'm not completely sure it belongs to HAPROXY DPAPI.
I've got the feeling it is more related to the networking infra.
If it works with UBUNTU and not with Docker Container, to me the 1st approach would be to at least verify the access to the files within the container itself.
Indeed haproxy doesn't have any notion about CIFS and/or NFS.

May be I'm wrong but i think, you are using CIFS or NFS to modify one time only, a haproxy config file used by multiple containers, just to avoid you giving each haproxy container its own set of files?

Did you try giving each haproxy container it's own set of files?
In the negative it worth a test, if you haven't fixed this _infra issue_ yet

Thanks

**Comment by bedis** [comment]
problem seems to be related to underlying infrastructure.

**Comment by dkorunic** [comment]
To further add information for the OP, neither NFS or SMB/CIFS shares have atomic renames which are required for normal dataplaneapi operation which we use to have some degree of reliable writes. On top of that, NFS, SMB/CIFS shares also have their own ownership complications in terms of UID/GID translations and it's really not a recommended way of using Dataplaneapi.
