### ISSUE TITLE
Add option "port" to server configuration

### ISSUE THREAD

**Issue by learon** [haproxytech/dataplaneapi#38]
This is a feature request.

To be able to perform health checks on one port, and serve traffic on other port; we use https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#5.2-port option in haproxy configuration file. We'd like to manage it using dataplane api but are currently missing this feature.

**Comment by gorangalinec** [comment]
Hello, this is added in 54dc7efce9263d67732980d24ab139e3bbc105ba and it will be available in the next release.
