### ISSUE TITLE
Dynamic SSL Certificate Updates

### ISSUE THREAD

**Issue by lcofre** [haproxytech/dataplaneapi#4]
First of all, thanks for this new great 2.0 release.

Regarding the "Dynamic SSL Certificate Updates" 2.1 coming feature, I was wondering If that feature means we'll be able to read and write through the API the certs haproxy uses on the bind option.

I am using kubernetes and in the meantime I am planning on changing the certs though the kubernetes API and reloading haproxy with the haproxy API.

Thanks very much for your help and good work.

**Comment by dcorbett-haproxy** [comment]
The feature will allow updating of certificates using the Runtime API without requiring a reload.
