### ISSUE TITLE
Add option "check-ssl" and "downinter" to server configuration

### ISSUE THREAD

**Issue by Acronys1** [haproxytech/dataplaneapi#41]
Hello, 

This is a feature request.

Despite of my long read of the API documentation I can't find the "check-ssl" and "downinter" parameter at the server configuration level ( backend default too )
https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#check-ssl
https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#downinter
This would allow us to get an identical configuration than before

Thanks

**Comment by mjuraga** [comment]
Hi, thank you for your issue, we will be sure to add this to our roadmap.

**Comment by gorangalinec** [comment]
Hello, this is added in 90d6869ec1694568cfbf5363b8a10e9265ec2b52 and it will be available in the next release.

**Comment by Acronys1** [comment]
Hi, Thank you very much !
