### ISSUE TITLE
Can't use "kill -SIGUSR2 1" in docker

### ISSUE THREAD

**Issue by opklm78** [haproxytech/dataplaneapi#42]
I run a HAProxy with dataplaneapi  in docker container on MacOS and use the command 
`--reload-cmd "kill -SIGUSR2 1"` to do reload,  but it doesn't work , the error message is `exec: \"kill\": executable file not found in $PATH` ,

so I change the cmd to `"/bin/bash -c kill -SIGUSR2 1"` , it still get the error: `usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]`

I also tried `"/bin/bash -c 'kill -SIGUSR2 1'"` , turned out to be: `-SIGUSR2: -c: line 0: unexpected EOF while looking for matching ``''`

so how can I do reload cmd in docker?  

the docker images is based on haproxy:2.0.5

**Comment by Elufimov** [comment]
I am also cant reload haproxy in docker container with `kill -SIGUSR2 1` But I have this output
```
[NOTICE] 283/073117 (1) : New program 'api' (6) forked
[NOTICE] 283/073117 (1) : New worker #1 (7) forked
time="2019-10-11T07:31:17Z" level=warning msg="Runtime API not configured, not using it"
time="2019-10-11T07:31:17Z" level=info msg="HAProxy Data Plane API v1.2.4 a5a8984"
time="2019-10-11T07:31:17Z" level=info msg="Build from: git@github.com:haproxytech/dataplaneapi.git"
time="2019-10-11T07:31:17Z" level=info msg="Build date: 2019-10-09T15:38:21"
time="2019-10-11T07:31:17Z" level=info msg="Serving data plane at http://[::]:5555"
time="2019-10-11T07:31:28Z" level=info msg="started handling request" method=GET remote="192.168.0.138:52359" request=/v1/services/haproxy/configuration/raw
time="2019-10-11T07:31:28Z" level=info msg="completed handling request" length=122B status=200 took="457.198µs"
time="2019-10-11T07:31:28Z" level=info msg="started handling request" method=POST remote="192.168.0.138:52359" request="/v1/services/haproxy/configuration/raw?version=1"
time="2019-10-11T07:31:28Z" level=info msg="completed handling request" length=619B status=202 took=48.298825ms
time="2019-10-11T07:31:32Z" level=info msg="Reload failed, restarting with last known good config..."
time="2019-10-11T07:31:32Z" level=warning msg="Restart failed, please check the reason and restart manually: Executing  failed: fork/exec : no such file or directory"
time="2019-10-11T07:31:32Z" level=warning msg="Reload failed Executing  failed: fork/exec : no such file or directory"
```

program conf
```
program api
    command /usr/local/bin/dataplaneapi --log-level=trace --host 0.0.0.0 --port 5555 --haproxy-bin /usr/local/sbin/haproxy --config-file /usr/local/etc/haproxy/haproxy.cfg --reload-cmd 'kill -SIGUSR2 1' --reload-delay 5 --userlist dataplane-api
    no option start-on-reload
```

**Comment by opklm78** [comment]
this is because when reload failed , the dataplaneapi will try to restart it , but the official guide doesn't have the restart cmd (default is empty), so the output will have the `Restart failed, please check the reason and restart manually: Executing  failed: fork/exec : no such file or directory` , and the restart error message will override the reload error message , so we can't see the truely error `exec: \"kill\": executable file not found in $PATH`

**Comment by opklm78** [comment]
@mjuraga  I think the lkgConfigFile in reloadHAProxy() doesn't work,  the defer function will use the wrong .bck configfile to overwrite the lkgConfigFile

**Comment by Elufimov** [comment]
@opklm78 I changed base image to `haproxytech/haproxy-ubuntu:2.0.7` and it fixed reload.

**Comment by mjuraga** [comment]
@opklm78 It works, the "broken" file will always be the one at configured file, even if we fail, the *.lkg file will be the one that HAProxy is actually running, we do this to ensure we never kill haproxy process, when this happens, you should fix the broken file and then it will succeed and overwrite the *.lkg file.

Does upgrading base image fix this issue for you too?

**Comment by opklm78** [comment]
@mjuraga  Yeal, change the image is working.

And I know what you mean , I thought you wanted to use lkg file to roll back the config when something went wrong. So I should add the restart cmd to avoid this error. Thank you very much.

**Comment by duusty** [comment]
Iam currently struggling with the same behavior. After i commit the transaction the reload failed with the message: 

`"Reload failed Executing  failed: fork/exec : no such file or directory`

I have already tried different versions (alpine, debian, ubuntu) always the same problem also using the image above does not work. 

```
haproxy | time="2020-02-28T10:11:59Z" level=info msg="started handling request" method=PUT remote="172.18.0.1:52908" request=/v1/services/haproxy/transactions/b02d468e-f69a-4b6a-b004-d0cad9c5805d
haproxy | time="2020-02-28T10:11:59Z" level=info msg="completed handling request" length=78B status=202 took=17.583125ms
haproxy | time="2020-02-28T10:12:01Z" level=debug msg="Reload started..."
haproxy | time="2020-02-28T10:12:01Z" level=debug msg="Reload finished."
haproxy | time="2020-02-28T10:12:01Z" level=debug msg="Time elapsed: 649.733µs"
haproxy | time="2020-02-28T10:12:01Z" level=info msg="Reload failed, restarting with last known good config..."
haproxy | time="2020-02-28T10:12:01Z" level=warning msg="Restart failed, please check the reason and restart manually: Executing  failed: fork/exec : no such file or directory"
haproxy | time="2020-02-28T10:12:01Z" level=warning msg="Reload failed Executing  failed: fork/exec : no such file or directory"

```
Config:

```
global 
  daemon
  master-worker
  stats socket ipv4@0.0.0.0:9999 level admin
  stats socket /var/run/haproxy.sock mode 666 level admin
  stats timeout 30s
  log stdout format raw local0 info

defaults 
  mode http
  log global
  option httplog
  option http-server-close
  timeout http-request 5s
  timeout connect 5s
  timeout client 30s
  timeout server 10s

program api 
  command dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin haproxy --config-file /usr/local/etc/haproxy/haproxy.cfg -reload-cmd="/bin/bash kill -SIGUSR2 1" --show-system-info --log-to=stdout --log-level=debug --log-format=text --userlist dataplane-api --reload-delay 5
  no option start-on-reload
```

**Comment by june07** [comment]
Not clear on why this was closed?!  Doesn't seem to be a "kill" binary in either docker images

haproxy:lts
haproxy:latest

I've also used the haproxytech/haproxy-ubuntu:2.0.7 image with good results as obviously the kill binary is there:
`
root@ef8f65dfcf8f:/# which kill
/bin/kill
`

But I would like to use the haproxy repo.  Any advice...

**Comment by dkorunic** [comment]
@june07 Debian Buster seems to have dropped `procps` package from their `buster-slim` image and that's the root cause here. We'll have it added back in our `haproxytech-debian` images ASAP, in the meantime `haproxytech-ubuntu` should work as usual.
