### ISSUE TITLE
Dataplaneapi returning previous version/outdated data after "raw" update

### ISSUE THREAD

**Issue by rptl** [haproxytech/dataplaneapi#43]
Dataplaneapi version:
`/ # /usr/local/bin/dataplaneapi --version
HAProxy Data Plane API v1.2.3 d6b862c

Build from: git@github.com:haproxytech/dataplaneapi.git
Build date: 2019-08-28T15:11:49`

After PUT /configuration/raw with new definitions, Dataplaneapi is not returning updated values on subsequent calls. Either way, GET /configuration/raw returns expected results, while GET /configuration/frontends (or backends/acls/binds) doesn't.

Old values (please notice _version mismatch):
`/ # curl -X GET -H 'Cache-Control: no-cache' --user admin:admin -H "Content-Type: application/json" "http://localhost:5555/v1/services/haproxy/configuration/frontends"`

`{"_version":12,"data":[{"client_timeout":120000,"default_backend":"be_http-app-svc,"mode":"http","name":"fe_port443"},{"client_timeout":7200000,"default_backend":"backend-port443_2","mode":"http","name":"port443"},{"client_timeout":7200000,"default_backend":"backend-port80","mode":"http","name":"port80"}]}`

GET raw snippet, returns updated and expected data:

`/ # curl -X GET -H 'Cache-Control: no-cache' --user admin:admin -H "Content-Type: application/json" "http://localhost:5555/v1/services/haproxy/configuration/raw"`
`{"_version":13,"data":"\nglobal \n  daemon\n  master-worker\n  maxconn 4000\n  pidfile /var/run/haproxy.pid\n  stats socket /var/lib/stats\n  tune.ssl.default-dh-param 1024\n  log 127.0.0.1 local2\n  chroot      /var/lib\n  user        nobody\n  group       nobody\n  # turn on stats unix socket\n\ndefaults \n  mode tcp\n  maxconn 3000\n  log global\n  option httplog\n  option redispatch\n  option dontlognull\n
...
...
`

1- Doesn't work, even after kill SIGUSR2/HUP on haproxy.

Steps to reproduce:
1- PUT /config/raw - a plain text config with some change (I have changed fe timeout). I used version query instead transaction_id

2- GET /config/raw - changes are there, as expected. haproxy.cfg is also updated

3- GET /config/frontends - returns old data (please check "_version")

**Comment by mjuraga** [comment]
Thank you for your report, we'll look into it.

**Comment by rptl** [comment]
Can you confirm if /config/raw reads  current haproxy.cfg file and return value and /config/frontends use some memory cached data, maybe loaded during startup?

Let me provide more details about the issue and about my environment, I think that can help in your troubleshooting.  

I am running haproxy+dataplane as cluster. Both running in different servers. I have a 'sync daemon' that propagates haproxy.cfg among the cluster after any change. 

The issue is happening actually in the non hit dataplane. Let's say, if I do the update hitting server 1, I can retrieve /config/raw and config/frontends, hitting this server as expected. But, on server 2,  after haproxy.cfg sync, /config/raw looks good, but /config/frontends doesn't and never get updated.

Looks like there is some cache during dataplane startup or something. /config/raw probably is literally reading from haproxy.cfg, while /config/frontends (binds/backends, etc), is returning something from memory, maybe.

**Comment by mjuraga** [comment]
Actually it does, dataplaneapi keeps the config in memory (not as plain text, but as it's own structures), so configuration/frontend reads from memory. On every change it updates in memory and on disk. On raw config updates it works with a file, but it triggers a reload of the memory cache on change.

In your case I would suggest sending SIGUSR2 to the dataplaneapi process when the file is synced, that will reinitialize the config client, basically rearead the config file and update in memory state.

**Comment by rptl** [comment]
Thanks, That worked!

Got it from manual: 

"Note

The objective of the Data Plane API is to manage the HAProxy configuration file completely. So, whenever you edit the configuration manually, make sure that you restart the API or send it a SIGUSR2 signal so that it can read the file again. See below for examples on how to use the commands."
