### ISSUE TITLE
/v1/services/haproxy/stats/native?type=server does not return all servers

### ISSUE THREAD

**Issue by CRCinAU** [haproxytech/dataplaneapi#47]
Querying the following URL:
/v1/services/haproxy/stats/native?type=server

I notice that a lot of servers we have and associated backends do not appear in the output.

Is there an upper limit to the number of entries returned? How can I retrieve every server?

Currently using dataplane v1.2.4

Some counts:
```
$ grep "  server" haproxy-http.cfg | wc -l
43
$ grep '^backend' haproxy-http.cfg | wc -l
37
$ curl http://username:password@127.0.0.1:55550/v1/services/haproxy/stats/native?type=server | grep -o server | wc -l
27
```

**Comment by mjuraga** [comment]
Hi, it appears this is a bug, I am looking into it and let you know when we fix this.

**Comment by mjuraga** [comment]
Hi @CRCinAU this should be fixed with https://github.com/haproxytech/dataplaneapi/commit/c95ddc1d771bffa4cbc9e9e6c5bb21b72091f75c

Can you please test it and confirm that it is fixed so we can close this?

**Comment by CRCinAU** [comment]
I'm having a few troubles with this - I'm guessing because /v1/ is now gone and everything is under /v2/ ?

Are there any differences that I need to know about to transition? I can't seem to see anything documented for v2 as yet - and the v1 URLs now all return a 404...

**Comment by mjuraga** [comment]
Sorry, forgot to mention that, everything in the master branch is now for v2, I will tag it once we implement a few more features and create a changelog. Also I will backport all the bugfixes to the v1 branch and tag it apporpriately.

**Comment by mjuraga** [comment]
Hey, I've backported some fixes to the [v1 branch](https://github.com/haproxytech/dataplaneapi/tree/v1), including this one. Note that they are not yet released, but please could you test the latest commit there to see if it fixes your problem?

**Comment by CRCinAU** [comment]
I've built this and just waiting for some scheduled cleanup tasks to fire - I'll be able to see if it hits all the backends in the list once these run a few times.

**Comment by CRCinAU** [comment]
Looks good - I now see all backend servers listed in the request.

Thanks!
