### ISSUE TITLE
dataplaneapi can't read/access haproxy-master.sock

### ISSUE THREAD

**Issue by hellracer** [haproxytech/dataplaneapi#50]
I'm trying to call this endpoint but the response from the API is this
http://192.168.144.225:5555/v2/services/haproxy/stats/native
```

[
  {
    "error": "dial unix unix@/run/haproxy-master.sock: connect: no such file or directory",
    "runtimeAPI": "unix@/run/haproxy-master.sock@1",
    "stats": null
  }
]
evidently the socket file exist in the filesystem
root@LB01:~# ls -al /run/haproxy-master.sock 
srwxr-xr-x 1 root root 0 Nov  9 16:24 /run/haproxy-master.sock
root@LB01:~# 

haproxy snippet config
program api
    command dataplaneapi --host 192.168.144.225 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "systemctl reload haproxy" --reload-delay 5 --userlist controller

userlist controller
    user superadmin password $5$IjsO5NsBcuMA1$qOv1sUuaEVGqbqTjSxmVbc//CxRKCfiyPr/Z.2wwu4/
```

**Comment by hellracer** [comment]
Found a similar issue @ serverfault

https://serverfault.com/questions/977625/installing-the-data-plane-api-in-the-haproxy-process-manager

**Comment by mjuraga** [comment]
Are you sure you have the correct permissions for that file?

**Comment by hellracer** [comment]
haproxy run under the user haproxy, i don't know why the socket file permission was set to root even though i change the ownership of this socket file to haproxy still it didn't work and I haven't seen any instruction on how to set the permission of the socket file, thanks for looking into this

**Comment by DiscoveringWorld** [comment]
I solved this issue on my side by removing the loading of this socket from the systemd haproxy service.
"EXTRAOPTS=-S /run/haproxy-master.sock"

**Comment by hellracer** [comment]
@DiscoveringWorld  thanks a ton it's working now
