### ISSUE TITLE
Ability to validate config 

### ISSUE THREAD

**Issue by Elufimov** [haproxytech/dataplaneapi#51]
It would be very useful if one can upload file to dataplane api without applying it. For example `POST /v1/services/haproxy/configuration/raw&only_validating=true`

**Comment by mjuraga** [comment]
This seems like a nice feature, we'll definitely add it to the roadmap and let you know when it's released.

**Comment by amelhusic** [comment]
Hi @Elufimov

With https://github.com/haproxytech/dataplaneapi/commit/f28c57f3b08fe42990d851b3c144db888c053ca8 it is possible to only validate configuration without actually applying it. This feature will be available in next release.
