### ISSUE TITLE
error 500 when adding backend with default_server other than "fall".

### ISSUE THREAD

**Issue by phaza** [haproxytech/dataplaneapi#53]
> POST /v1/services/haproxy/configuration/backends?transaction_id=53c262e7-e491-4272-b93d-eaad98f5f4c0 HTTP/1.1
User-Agent: HTTPie/1.0.3
Accept-Encoding: gzip, deflate
Accept: application/json, */*
Connection: keep-alive
Content-Type: application/json
Content-Length: 125
Authorization: Basic xxx
Host: docker-haproxy-certbot_server_1:5555

>{"balance": {"algorithm": "random"}, "default_server": {"inter": 5000}, "name": "my_backend"}

>HTTP/1.1 500 Internal Server Error
Vary: Origin
Date: Fri, 22 Nov 2019 10:54:29 GMT
Content-Length: 137
Content-Type: text/plain; charset=utf-8

>{"code":500,"message":"runtime error: invalid memory address or nil pointer dereference: /usr/local/go/src/runtime/panic.go:81 panicmem"}

I'm fairly sure this happens because of buggy code in client-native configuration.go, but alas I thought it would be nice to track it here in case others experience the same issue.

Issue seems to stem from a typo, where the wrong parameter is used:  
https://github.com/haproxytech/client-native/blob/v1.2.6/configuration/configuration.go#L789
```go
if ds.Inter != nil {
	param := &params.ServerOptionValue{
		Name:  "inter",
		Value: strconv.FormatInt(*ds.Fall, 10), // <-- I think this should be *ds.Inter, but I don't know go.
	}
	ps = append(ps, param)
}
```
>time="2019-11-22T10:54:29Z" level=info msg="started handling request" method=POST remote="172.25.0.3:43872" request="/v1/services/haproxy/configuration/backends?transaction_id=53c262e7-e491-4272-b93d-eaad98f5f4c0"
time="2019-11-22T10:54:29Z" level=error msg="Panic runtime error: invalid memory address or nil pointer dereference" stack_trace="\n/usr/local/go/src/runtime/panic.go:81 panicmem\n/home/mjuraga/projects/go/pkg/mod/github.com/haproxytech/client-native@v1.2.6/configuration/configuration.go:783 (*Client).setFieldValue\n/home/mjuraga/projects/go/pkg/mod/github.com/haproxytech/client-native@v1.2.6/configuration/configuration.go:635 (*Client).createEditSection\n/home/mjuraga/projects/go/pkg/mod/github.com/haproxytech/client-native@v1.2.6/configuration/configuration.go:1181 (*Client).createSection\n/home/mjuraga/projects/go/pkg/mod/github.com/haproxytech/client-native@v1.2.6/configuration/backend.go:100 (*Client).CreateBackend\n/home/mjuraga/projects/haproxytech/dataplaneapi/handlers/backend.go:76 (*CreateBackendHandlerImpl).Handle\n/home/mjuraga/projects/haproxytech/dataplaneapi/operations/backend/create_backend.go:84 (*CreateBackend).ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/go-openapi/runtime@v0.19.0/middleware/operation.go:28 NewOperationExecutor.func1\n/usr/local/go/src/net/http/server.go:1995 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/go-openapi/runtime@v0.19.0/middleware/router.go:76 NewRouter.func1\n/usr/local/go/src/net/http/server.go:1995 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/go-openapi/runtime@v0.19.0/middleware/redoc.go:72 Redoc.func1\n/usr/local/go/src/net/http/server.go:1995 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/go-openapi/runtime@v0.19.0/middleware/spec.go:46 Spec.func1\n/usr/local/go/src/net/http/server.go:1995 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/haproxytech/dataplaneapi/adapters/adapters.go:151 RecoverMiddleware.func1.1\n/usr/local/go/src/net/http/server.go:1995 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 (*Cors).Handler.func1\n/usr/local/go/src/net/http/server.go:1995 HandlerFunc.ServeHTTP\n/home/mjuraga/projects/haproxytech/dataplaneapi/adapters/adapters.go:165 LoggingMiddleware.func1.1\n/usr/local/go/src/net/http/server.go:1995 HandlerFunc.ServeHTTP\n/usr/local/go/src/net/http/server.go:2774 serverHandler.ServeHTTP\n/usr/local/go/src/net/http/server.go:1878 (*conn).serve\n/usr/local/go/src/runtime/asm_amd64.s:1337 goexit"

**Comment by mjuraga** [comment]
This is definitely a bug. Thanks for the nice report.

**Comment by mjuraga** [comment]
Note that this is fixed in master: https://github.com/haproxytech/client-native/blob/master/configuration/configuration.go#L887

We will soon release 2.0.0 with bugfixes and some new features and 1.2.5 with backported fixes.

**Comment by mjuraga** [comment]
Hey, I've backported some fixes to the [v1 branch](https://github.com/haproxytech/dataplaneapi/tree/v1), including this one. Note that they are not yet released, but please could you test the latest commit there to see if it fixes your problem?
