### ISSUE TITLE
Setting the configuration for resolvers and init-addr for a server in backend section

### ISSUE THREAD

**Issue by virgmm** [haproxytech/dataplaneapi#54]
I try to add a server to a backend section in my haproxy.cfg via data plane api. I can't find anything in the documentation how to set the configuration for resolvers and init-addr. e.g.: resolvers docker init-addr libc,none
I was able to configure the name, address and check with the /services/haproxy/configuration/servers endpoint
This is how it should be configured:
```
backend backend1
server server1 server1:80 check resolvers docker init-addr libc,none
```
How can I set these configurations or is it not yet possible?

**Comment by bedis** [comment]
Hi,
This should be part added by #35 

I put myself as owner here so I can update you once ready.

**Comment by phaza** [comment]
Just hit the same issue.  
Is there are workaround to configure resolvers right now?

**Comment by mjuraga** [comment]
Currently you can edit it directly in file and push it using the /services/haproxy/configuration/raw endpoint.

**Comment by olafnorge** [comment]
You could also add it to the default section, if applicable:

```
defaults 
  default-server init-addr last,libc,none no-tls-tickets resolvers docker check

resolvers docker 
  parse-resolv-conf
```

This how I do it.

**Comment by phaza** [comment]
> 
> 
> You could also add it to the default section, if applicable:
> 
> ```
> defaults 
>   default-server init-addr last,libc,none no-tls-tickets resolvers docker check
> 
> resolvers docker 
>   parse-resolv-conf
> ```
> 
> This how I do it.

Yes thanks, I figured out that too. Which solves the problem for me :)

**Comment by mjuraga** [comment]
We support the `init-addr` option on `server` and `default-server` in commit https://github.com/haproxytech/dataplaneapi/commit/2622bb6e6925af304f6b86d547c2bdca27e85507
