### ISSUE TITLE
Question about releasing period for dataplaneapi

### ISSUE THREAD

**Issue by DiscoveringWorld** [haproxytech/dataplaneapi#55]
Hello,

we use datapane api dev version 1.2.4 at a client office for the
V2/specifications.

The client will feel more confortable to use this V2  version of the api
when it will be released officially.

Do you know when the dataplane api 1.2.4 or later  will be released ?

Actually we use the dev version that we compiled.

**Comment by mjuraga** [comment]
Thank you for you question, we don't have a timeline or a release period, we are currently just listening on the feedback (mostly on github issues) and then looking what to add to the new version. For 2.0 we are looking for a release before the end of the year.

**Comment by DiscoveringWorld** [comment]
Thanks for the info.
