### ISSUE TITLE
Reload Command kill SIGUSR2 failed

### ISSUE THREAD

**Issue by virgmm** [haproxytech/dataplaneapi#56]
We are running Haproxy and the Data plane API in the same Docker Container. After Updating the haproxy.cfg via the API, the reload command fails. It seems that the kill command can not be executed with the user who runs the data plane API, it only works as root. 
```
$ kill -12 1
-sh: 1: kill: Operation not permitted
```
As per this Documentation it should work without root permissions. Is there a workaround?
[https://www.haproxy.com/documentation/hapee/1-9r1/configuration/dataplaneapi/#configure-haproxy-to-start-the-api](url)

**Comment by DiscoveringWorld** [comment]
You can only kill processes for users whose processes belong to them.

Check with the command ps aux 

For example, event i'm not root, i can kill the process of my ssh session. So the kill command have to be executed on the use that run the process you wanbt to kill.
