### ISSUE TITLE
'crt' missing certificate location

### ISSUE THREAD

**Issue by DonatasFe** [haproxytech/dataplaneapi#57]
**Haproxy v2.0.5**

> `HA-Proxy version 2.0.5 2019/08/16 - https://haproxy.org/
> Build options :
>   TARGET  = linux-glibc
>   CPU     = generic
>   CC      = gcc
>   CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
>   OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1
> 
> Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS
> 
> Default settings :
>   bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
> 
> Built with multi-threading support (MAX_THREADS=64, default=2).
> Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
> Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
> OpenSSL library supports TLS extensions : yes
> OpenSSL library supports SNI : yes
> OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
> Built with network namespace support.
> Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
> Built with zlib version : 1.2.7
> Running on zlib version : 1.2.7
> Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
> Built with PCRE version : 8.32 2012-11-30
> Running on PCRE version : 8.32 2012-11-30
> PCRE library supports JIT : yes
> Encrypted password support via crypt(3): yes
> Built with the Prometheus exporter as a service
> 
> Available polling systems :
>       epoll : pref=300,  test result OK
>        poll : pref=200,  test result OK
>      select : pref=150,  test result OK
> Total: 3 (3 usable), will use epoll.
> 
> Available multiplexer protocols :
> (protocols marked as <default> cannot be specified using 'proto' keyword)
>               h2 : mode=HTX        side=FE|BE     mux=H2
>               h2 : mode=HTTP       side=FE        mux=H2
>        <default> : mode=HTX        side=FE|BE     mux=H1
>        <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS
> 
> Available services :
>         prometheus-exporter
> 
> Available filters :
>         [SPOE] spoe
>         [COMP] compression
>         [CACHE] cache
>         [TRACE] trace`

**HAProxy Data Plane API v1.2.4 9804b65.dev**

I have serveral frontend binds defined as in example and using multiple certificates
`bind *:443 ssl no-sslv3 crt /etc/haproxy/certificates/`

While executing simple payload, no matter what changes there would be
`# maint.json
{
  "address":"10.10.1.10",
  "check":"enabled",
  "maintenance":"enabled",
  "name":"srv01",
  "port":10138
}`

I get to such error code
`{
  "code": 400,
  "message": "14: ERR transactionId=2ca2f57d-74a0-4c58-a957-570c51f1adf8 \nline=35 msg=\"'bind *:443' 'crt' missing certificate location\"\nline=1278 msg=\"'bind *:10104' 'crt' missing certificate location\"\nline=1409 msg=\"'bind *:20087' 'crt' missing certificate location\"\nline=2052 msg=\"'bind *:11458' 'crt' missing certificate location\"\nline=2247 msg=\"'bind *:4440' 'crt' missing certificate location\"\nline=2298 msg=\"'bind *:11459' 'crt' missing certificate location\""
}`

Same error appears while defining certificates one by one
`bind *:443 ssl no-sslv3 crt /etc/haproxy/certificates/test_com.pem crt /etc/haproxy/certificates/test_zone.pem crt /etc/haproxy/certificates/app_test_zone.pem`

Both haproxy and dataplaneapi serivces run under root to be sure it is not a permissions issue.

**Comment by mjuraga** [comment]
Thank you for the report, we'll look into it and let you know.

**Comment by DonatasFe** [comment]
I am posting just a result as cannot expose sensitive data which might appear in warning sections due to deprecated header functions.

Using configuration with certificates defined in directory 
> bind *:443  ssl no-sslv3 crt /etc/haproxy/certificates/
result is 
`Configuration file is valid`

Using configuration with certificates defined one by one result is

> bind *:443  ssl no-sslv3 crt /etc/haproxy/certificates/test_com.pem crt /etc/haproxy/certificates/test_zone.pem crt /etc/haproxy/certificates/app_test_zone.pem

`Configuration file is valid`

**Comment by mjuraga** [comment]
I can confirm that this is a bug. We are looking into it and will fix it.

**Comment by DonatasFe** [comment]
yesterday i came with a solution while moving no-sslv3 setting after certificate path (found example on haproxy blog)
`bind *:443 ssl crt /etc/haproxy/certificates/ no-sslv3`
and it start working
Yet, i did not find anything in documentation what is the right order to declare settings in a bind section to avoid future mistakes.

**Comment by mjuraga** [comment]
Yes, this should work, it is a bug. The config-parser was expecting a value after `no-sslv3` keyword, so it took `crt` as value, and totally ignored `crt` keyword. We already have a fix, should be commited today.

Thank you for your report.

**Comment by mjuraga** [comment]
This should be fixed now with https://github.com/haproxytech/dataplaneapi/commit/06343045696c1b871f1918f2c1488687815da7e4

**Comment by mjuraga** [comment]
Backported to v1 with https://github.com/haproxytech/dataplaneapi/commit/06343045696c1b871f1918f2c1488687815da7e4
