### ISSUE TITLE
error detected in frontend while parsing 'http-request redirect' rule

### ISSUE THREAD

**Issue by DonatasFe** [haproxytech/dataplaneapi#58]
HAProxy Data Plane API v1.2.4 0634304.dev
HA-Proxy version 2.1.0 2019/11/25

we are using a bunch of ACLs on our haproxy services, thus with dataplane api trying to enable server maintenance, i get errors listed below.  It might be a similar [bug](https://github.com/haproxytech/dataplaneapi/issues/57) that had experience before.

Haproxy config valdiation: Configuration file is valid

Several examples:

**config line:**
`http-request redirect code 301 location https://site.d1.randomsite.com/healthcheck.html if { path_beg -m beg -i /health-check.html AND hdr_beg(host) -i www }`

**Error**
`{
  "code": 400,
  "message": "14: ERR transactionId=2b53e98a-b126-4e7f-a30f-83c62da5aeca \nline=283 msg=\"error detected in frontend 'incomming' while parsing 'http-request redirect' rule expects 'code', 'prefix', 'location', 'scheme', 'set-cookie', 'clear-cookie', 'drop-query' or 'append-slash' (was '{').\""
}`

**config lines**
`acl root_path_cond path -i /`
`acl site_domain_cond hdr(host) -i www.d1.randomsite.com`
`http-request redirect code 301 location http://site.d1.randomsite.com if site_domain_cond root_path_cond`
**error:** 
`{
  "code": 400,
  "message": "14: ERR transactionId=ae7236be-366a-4c42-a4b4-298ca7c0b9a0 \nline=283 msg=\"error detected in frontend 'incomming' while parsing 'http-request redirect' rule expects 'code', 'prefix', 'location', 'scheme', 'set-cookie', 'clear-cookie', 'drop-query' or 'append-slash' (was 'site_domain_cond').\""
}`

**Comment by mjuraga** [comment]
We are looking into it.

**Comment by DonatasFe** [comment]
Hi @mjuraga, do you have any update on this? Thanks in advance!

**Comment by mjuraga** [comment]
It's a bug, a fix should come soon.

**Comment by Aref-Riant** [comment]
I have the same problem with the current version "HAProxy Data Plane API v1.2.4 e99a6eb.dev"

**Comment by mjuraga** [comment]
This is fixed in the latest master, and a 2.0 release is coming soon.

**Comment by mjuraga** [comment]
2.0 release is out: https://github.com/haproxytech/dataplaneapi/releases/tag/v2.0.0
