### ISSUE TITLE
Handle "verify ( optional | required )" options in bind and server directives

### ISSUE THREAD

**Issue by Aestek** [haproxytech/dataplaneapi#6]
These settings are required to make client certificates validation.
Additionally, the `verify` option allows to retrieve the client certificate with the `ssl_c_der` variable which we use to forward intention validations via SPOE for Consul Connect.

**Comment by mjuraga** [comment]
Added in https://github.com/haproxytech/dataplaneapi/tree/v1.0.1

**Comment by Aestek** [comment]
Great thx !
