### ISSUE TITLE
Support mutual cert verification as only form of auth

### ISSUE THREAD

**Issue by akutz** [haproxytech/dataplaneapi#60]
While the dataplane API server supports mutual TLS verification  as a form of authentication, it's still necessary to supply **some** form of username/password. It would be nice to rely solely on the peer verification as the only form of authentication.

**Comment by mjuraga** [comment]
As agreed on slack, we need to implement this.

**Comment by prometherion** [comment]
Basic Authentication disabling when performing client-based certificate authentication has been implemented in 51a6765.

Please note that the environment variable `TLS_CA_CERTIFICATE` **must** be assigned, otherwise the verification cannot be performed.
