### ISSUE TITLE
Unable to run dataplaneapi on Haproxy Community

### ISSUE THREAD

**Issue by harsha97396** [haproxytech/dataplaneapi#61]
bash: dataplaneapi: command not found
i am getting an issue like that

**Comment by DonatasFe** [comment]
after building the package you will find executable at `dataplaneapi/build`
make sure it has +x permissions and copy it `/usr/local/bin/ ` or other dir depending on your os or config

**Comment by harsha97396** [comment]
Thanks for the response. It worked but again i getting this error
{"code":404,"message":"path /v1/specification was not found"} when i tried localhost:5555/v1/specification

**Comment by mjuraga** [comment]
If you built it using the latest master the path starts with /v2 not /v1.

**Comment by dragoangel** [comment]
Strange that docs omits version `/v2` or `/v1` for dataplaneapi.

**Comment by dkorunic** [comment]
@dragoangel Both [README](https://github.com/haproxytech/dataplaneapi/blob/master/README.md) (at the bottom of the file) and [Usage docs](https://www.haproxy.com/documentation/hapee/2-4r1/api/data-plane-api/usage/) very clearly show that we use `/v2` prefix in the recent versions.

**Comment by dragoangel** [comment]
Yeah, I missed it
