### ISSUE TITLE
Dataplane removes user from option pgsql-check 

### ISSUE THREAD

**Issue by jgould22** [haproxytech/dataplaneapi#64]
Whenever a dataplane transaction is completed and the dataplane rewrites the config it removed the `user` portion of the `option pgsql-check` line so the below example
```
backend pgbackend
  mode tcp
  balance first
  option pgsql-check user postgresuser
  timeout server 5m
  timeout connect 5s
  server pg01 pg01:5432 check 
  server pg02 pg02:5432 check backup
  option tcpka
```
becomes 
```
backend pgbackend
  mode tcp
  balance first
  option pgsql-check
  timeout server 5m
  timeout connect 5s
  server pg01 pg01:5432 check 
  server pg02 pg02:5432 check backup
  option tcpka
```
and then the health checks fail because the user is no longer specified

This happens with the latest dataplane-api and latest haproxy release

**Comment by mjuraga** [comment]
This is a bug, thank you for reporting it.

**Comment by mjuraga** [comment]
This is fixed in the latest master, a new release is coming soon.
