### ISSUE TITLE
Support for grpc load balancing using HDR algorithm

### ISSUE THREAD

**Issue by yoanisgil** [haproxytech/dataplaneapi#66]
Hi there,

I'm looking to generate the following configuration:

```
frontend fe_proxy
    bind :9000 proto h2
    default_backend be_servers

backend be_servers
    balance hdr(trial_id)
    server server1 srv1:9000 check maxconn 20 proto h2
    server server2 srv2:9000 check maxconn 20 proto h2
    server server3 srv3:9000 check maxconn 20 proto h2

```

but from looking at the JSON schema definition, this does not look possible at the moment. Any ideas why? Happy to contribute if a patch is welcomed.

**Comment by mjuraga** [comment]
We don't have the `proto` keyword supportend on `bind` and `server` lines.

the `hdr(trial_id)` is also not supported in the 1.x version, but in the following 2.0 version will be supported. It is already supported if you build from master.

Of course a patch is welcomed, you can add the `proto` keyword to the `server` and `bind` lines.

Firstly you should update the specification in the https://github.com/haproxytech/dataplaneapi-specification project, then build the https://github.com/haproxytech/models package from it, update the https://github.com/haproxytech/client-native. And finally just build this project from the specification.

**Comment by mjuraga** [comment]
We have added the proto keyword to the server resource. You can find it in the latest master. Also 2.0 release is coming soon.

**Comment by mjuraga** [comment]
2.0 is released: https://github.com/haproxytech/dataplaneapi/releases/tag/v2.0.0
