### ISSUE TITLE
connect ECONNREFUSED recursive api call

### ISSUE THREAD

**Issue by abhishekwish** [haproxytech/dataplaneapi#67]
This is occured when called recursive api call in process  
connect ECONNREFUSED 0.0.0.0:5555:

{"message":"connect ECONNREFUSED  0.0.0.0:5555","name":"Error","stack":"Error: connect ECONNREFUSED  0.0.0.0:5555\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)"

**Comment by mjuraga** [comment]
We need more info. I don't see where the API fails?
