### ISSUE TITLE
empty system info

### ISSUE THREAD

**Issue by chipitsine** [haproxytech/dataplaneapi#69]
`/v1/info`

returns (note empty "system" node)

`{"api":{"build_date":"2019-10-09T15:38:21.000Z","version":"v1.2.4 a5a8984"},"system":{}}`

**Comment by chipitsine** [comment]
run on `CentOS Linux release 7.6.1810 (Core)`

**Comment by chipitsine** [comment]
btw, api itself is perfect

**Comment by mjuraga** [comment]
This is why we added a `-i` CLI option. If you want your system info to be shown, start the dataplaneapi with it. It is for people that don't want to expose their system info through the API.

**Comment by chipitsine** [comment]
that is a feature, not a bug :/
