### ISSUE TITLE
Path from README does not work

### ISSUE THREAD

**Issue by jadencodes** [haproxytech/dataplaneapi#74]
The path in the bottom of the README `http://127.0.0.1:5555/v1` does not work. It should be `http://127.0.0.1:5555/v2`. The former will return a 404. Happy to make a small PR if wanted and if there are other places this is incorrect I can change it there as well.

**Comment by mjuraga** [comment]
Sure, that is an error, every PR is welcome.

**Comment by mjuraga** [comment]
Fixed this, it's in the 2.0.0 release.
