### ISSUE TITLE
Reloading haproxy process inside docker Executing  failed: fork/exec : no such file or directory"

### ISSUE THREAD

**Issue by duusty** [haproxytech/dataplaneapi#75]
When the haproxy process inside the docker container is reloaded after the transaction commit iam getting the following error

`"Reload failed Executing  failed: fork/exec : no such file or directory`

I have already tried different versions (alpine, debian, ubuntu) always the same problem also using the image from #42  does not work. 

```
haproxy | time="2020-02-28T10:11:59Z" level=info msg="started handling request" method=PUT remote="172.18.0.1:52908" request=/v1/services/haproxy/transactions/b02d468e-f69a-4b6a-b004-d0cad9c5805d
haproxy | time="2020-02-28T10:11:59Z" level=info msg="completed handling request" length=78B status=202 took=17.583125ms
haproxy | time="2020-02-28T10:12:01Z" level=debug msg="Reload started..."
haproxy | time="2020-02-28T10:12:01Z" level=debug msg="Reload finished."
haproxy | time="2020-02-28T10:12:01Z" level=debug msg="Time elapsed: 649.733µs"
haproxy | time="2020-02-28T10:12:01Z" level=info msg="Reload failed, restarting with last known good config..."
haproxy | time="2020-02-28T10:12:01Z" level=warning msg="Restart failed, please check the reason and restart manually: Executing  failed: fork/exec : no such file or directory"
haproxy | time="2020-02-28T10:12:01Z" level=warning msg="Reload failed Executing  failed: fork/exec : no such file or directory"

```
Config:

```
global 
  daemon
  master-worker
  stats socket ipv4@0.0.0.0:9999 level admin
  stats socket /var/run/haproxy.sock mode 666 level admin
  stats timeout 30s
  log stdout format raw local0 info

defaults 
  mode http
  log global
  option httplog
  option http-server-close
  timeout http-request 5s
  timeout connect 5s
  timeout client 30s
  timeout server 10s

program api 
  command dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin haproxy --config-file /usr/local/etc/haproxy/haproxy.cfg -reload-cmd="/bin/bash kill -SIGUSR2 1" --show-system-info --log-to=stdout --log-level=debug --log-format=text --userlist dataplane-api --reload-delay 5
  no option start-on-reload
```

**Comment by mjuraga** [comment]
You are missing `--restart-cmd` as a parameter to dataplaneapi.

**Comment by duusty** [comment]
Thanks! The following change did it...
```
program api 
  command dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin haproxy --config-file /usr/local/etc/haproxy/haproxy.cfg --reload-cmd="kill -SIGUSR2 1" --restart-cmd="" --show-system-info --log-to=stdout --log-level=debug --log-format=text --userlist dataplane-api --reload-delay 5
  no option start-on-reload
```
Maybe the restart command can be added to the documentation ?

https://www.haproxy.com/documentation/hapee/2-0r1/configuration/dataplaneapi/

**Comment by sgarcialaguna-mms** [comment]
I'm having the same issue, adding the restart-cmd didn't help. 
This is with the haproxy:2.3 Docker image and HAProxy Dataplane 2.1.0

**Comment by aiharos** [comment]
Instead of leaving the `--restart-cmd` option set to an empty string, try setting it like the --reload-cmd parameter, i.e. `--reload-cmd='kill -SIGUSR2 1' --restart-cmd='kill -SIGUSR2 1'`.

**Comment by sgarcialaguna-mms** [comment]
That results in a different error message:

time="2021-01-13T07:48:44Z" level=info msg="completed handling request" length=106B status=202 took=78.8638ms
time="2021-01-13T07:48:45Z" level=debug msg="Reload started..."
time="2021-01-13T07:48:45Z" level=debug msg="Reload finished."
time="2021-01-13T07:48:45Z" level=debug msg="Time elapsed: 2.9994ms"
time="2021-01-13T07:48:45Z" level=info msg="Reload failed, restarting with last known good config..."
time="2021-01-13T07:48:45Z" level=warning msg="Restart failed, please check the reason and restart manually: executing kill -SIGUSR2 1 failed: exec: \"kill\": executable file not found in $PATH"
time="2021-01-13T07:48:45Z" level=warning msg="Reload failed executing kill -SIGUSR2 1 failed: exec: \"kill\": executable file not found in $PATH"

**Comment by sgarcialaguna-mms** [comment]
I could work around the issue by installing procps in my container which includes kill as an executable and not just a shell built-in.

**Comment by dkorunic** [comment]
@sgarcialaguna-mms This looks like you are not using haproxytech images with dataplane and procps already in the image, are you?

**Comment by sgarcialaguna-mms** [comment]
No, I hadn't realized those existed and started from an haproxy base image. That's good to know.

**Comment by dkorunic** [comment]
Ah OK. In any case, haproxytech images contain required binaries (procps in this case) and already contain recent dataplaneapi releases as well so they would be preferred way of using/testing it. If there are issues with Docker HAProxy images, we are currently not responsible for those -- we can send PRs (as much as anybody else), but otherwise it's still not under our jurisdiction.
