### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by randomvariable** [haproxytech/dataplaneapi#76]
Hello,

Wondering if we could get a tagged release for the 2.0 API.

Regards,

Naadir

**Comment by mjuraga** [comment]
Hi Naadir, we are working on some more stuff, and hopefully a release is coming soon.

**Comment by randomvariable** [comment]
Sounds good, thanks for the quick reply!

**Comment by mjuraga** [comment]
Here it is: https://github.com/haproxytech/dataplaneapi/releases/tag/v2.0.0

**Comment by randomvariable** [comment]
Great, thanks so much!
