### ISSUE TITLE
DataPlane API spec no longer works with master

### ISSUE THREAD

**Issue by akutz** [haproxytech/dataplaneapi#77]
The spec https://www.haproxy.com/documentation/dataplaneapi/latest/ no longer works with master due to at least one error with the `BackendSwitchingRule`:

```
POST /v2/services/haproxy/configuration/backend_switching_rules?frontend=lb-frontend&transaction_id=87e82ce9-a99a-4f66-ac3d-b564eeb43888 HTTP/1.1
Host: localhost:16965
User-Agent: LB API HAProxy DataPlane API Client
Content-Length: 78
Accept: application/json
Authorization: Basic Y2xpZW50OmNlcnQ=
Content-Type: application/json
Accept-Encoding: gzip

{"cond":"if","cond_test":"{ dst_port 8086 }","id":null,"name":"lb-backend-2"}

2020/04/15 15:49:54 
HTTP/1.1 422 Unprocessable Entity
Content-Length: 50
Content-Type: application/json
Date: Wed, 15 Apr 2020 20:49:54 GMT
Vary: Origin

{"code":602,"message":"index in body is required"}
--- FAIL: TestCreateLoadBalancer (6.33s)
    haproxy_test.go:335: 
        Unexpected error:
            <*errors.withStack | 0xc00000f7a0>: {
                error: {
                    cause: {
                        body: "{\"code\":602,\"message\":\"index in body is required\"}",
                        error: "422 Unprocessable Entity",
                        model: {
                            Code: 602,
                            Message: "index in body is required",
                        },
                    },
                    msg: "failed to create openapi.BackendSwitchingRule",
                },
                stack: [0x151eb0e, 0x1554475, 0x154f009, 0x10fb669, 0x105fce1],
            }
            failed to create openapi.BackendSwitchingRule: 422 Unprocessable Entity
        occurred
```

Talk about misleading. `Index` is the name of a field, not part of the error message. I guess somewhere someone renamed `Id` to `Index` and didn't update the other half. Or the repo is behind the spec. Not sure.

The embedded spec uses `Index` and the documented spec uses `Id`.

**Comment by mjuraga** [comment]
Yeah, the documenatation here: https://www.haproxy.com/documentation/dataplaneapi/latest/ is not tracking the latest master commits.

For the latest you should rely to embedded_spec or here: https://github.com/haproxytech/dataplaneapi-specification/blob/master/build/haproxy_spec.yaml

We will work to fix the officeal documentation to support only tagged versions (releases) from now on. Thank you for pointing this out.

**Comment by aiharos** [comment]
You can also find the always up-to-date docs served directly from the dataplane:
- just open the  `/v2/docs` url in your browser

**Comment by akutz** [comment]
Thanks to you both. I think I will continue to use the process I outlined in #78 as it ensures the spec is aligned with the version of DP API I am building.

**Comment by akutz** [comment]
I understand that there is a separate DP API repo, but what would be super helpful is for the swagger and OpenAPI specs to be generated for any commits to master. There is no clear link between this repo and https://github.com/haproxytech/dataplaneapi-specification, so it's difficult to know when a break occurs. That's why I like the solution I crafted in https://github.com/haproxytech/dataplaneapi/issues/78#issuecomment-614719560. It lets me grab the spec from the running DP server.

**Comment by akutz** [comment]
I will close this issue once https://www.haproxy.com/documentation/dataplaneapi/latest/ is updated. It represents itself as v2.0 of the spec, and it isn't up to date.

**Comment by mjuraga** [comment]
This should be up to date now.
