### ISSUE TITLE
Master is broken since d004346

### ISSUE THREAD

**Issue by akutz** [haproxytech/dataplaneapi#79]
Commit d0043465e176d046d41a5d2bfe8c1bd5ae20f197  broke master. Please see https://github.com/haproxytech/dataplaneapi/commit/d0043465e176d046d41a5d2bfe8c1bd5ae20f197#commitcomment-38510562 for more information.

**Comment by mjuraga** [comment]
Sorry for that, my bad it was a missing upgrade of the dependant library, fixed with https://github.com/haproxytech/dataplaneapi/commit/0553265cdddc4817d5f30d477e2ef5bd81027ccb

**Comment by akutz** [comment]
Grazzie. I'll close this as soon as I rebuild to verify (I'm sure it works, but I just want to do my due diligence).

Also, good to see you again. I was yanked off my previous project almost as soon as we first met. I'm back on a project involving HAProxy, so here I go again :)

**Comment by akutz** [comment]
Looks good, thank you @mjuraga !
