### ISSUE TITLE
When is 2.0 being released?

### ISSUE THREAD

**Issue by akutz** [haproxytech/dataplaneapi#81]
Hi there,

We are working on a project that requires DataPlane API 2.0 due to support for some of the newer flags (ex. `ssl-check`). We are currently building from source, but our Photon team will not create an RPM for DataPlane API 2.0 until you tag a release. We really do need this ASAP, and I was wondering if you know when you are planning to cut a 2.0 release?

Thank you!

**Comment by mjuraga** [comment]
Hi @akutz, the 2.0 release is coming this week.

**Comment by akutz** [comment]
FYI, I just filed https://github.com/vmware/photon/pull/1003 so we can quickly include support for DP 2.0 once it is available.

**Comment by akutz** [comment]
Is the plan for this release still for this week? Not pushing, just want to adjust some things on our end if the plan has changed. Thanks!

**Comment by mjuraga** [comment]
Hi @akutz sorry for running a little late but finally here it is: https://github.com/haproxytech/dataplaneapi/releases/tag/v2.0.0

**Comment by akutz** [comment]
Hi @mjuraga,

No worries, and thank you!!
