### ISSUE TITLE
authentification: support of variable in userlist

### ISSUE THREAD

**Issue by wlallemand** [haproxytech/dataplaneapi#83]
Hello dear colleagues :-),

In the ticket https://github.com/haproxy/haproxy/issues/590, @slimhazard is trying to use the dataplaneapi authentication with an environment variable. This is supported by HAProxy but I'm not sure the dataplane-api supports this. Indeed HAProxy supports variable in all the configuration file when a variable is framed by double-quotes. (ex. "${HAPROXY_PASSWORD}" )

A solution was found by chaining an haproxy listener in front of the dataplane-api, but I think that does not address all use cases.

**Comment by mjuraga** [comment]
dataplaneapi does not support this format of variables in the userlist section, we will add it.

**Comment by amelhusic** [comment]
Hi @wlallemand ,

With https://github.com/haproxytech/dataplaneapi/commit/f2a732aff1d0d65c869691972c935b89f4cec0c8 password from environment variable is supported.
