### ISSUE TITLE
Support for http-request options 

### ISSUE THREAD

**Issue by ShimmerGlass** [haproxytech/dataplaneapi#84]
I may have missed something but AFAICT the `http-request` option (https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4-http-request) is not supported by the dataplaneapi.
I would like to use it for `haproxy-consul-connect` to add a header containing the app name when a request is received through connect.

Is there a plan to add support for it already?

Additionally, as this option is pretty complex, maybe a first version with the rule as a string will be enough, such as :

```
fe := &models.Frontend{
  HttpRequest: []string{
    "set-header Host maintenance.domain.com",
  },
}
```

Thank you !

**Comment by mjuraga** [comment]
Actually this is supported, and you can add this by using:

```
POST /v2/services/haproxy/configuration/http_request_rules?parent_type=frontend&parent_name=<your frontend>&version=<your version>

{
  "index": 1,
  "type": "set-header",
  "hdr_name": "Host",
  "hdr_format": "maintenance.domain.com"
}
```

**Comment by ShimmerGlass** [comment]
Oh great, sorry for the noise then.
Thx a lot !
