### ISSUE TITLE
Please tag release 2.0.1

### ISSUE THREAD

**Issue by akutz** [haproxytech/dataplaneapi#88]
Hi all,

The following bugs were fixed post 2.0:

* Bug #87 - Fix 87e63bc31b2c17561ce545791287942e80a7c060
* Fix 0d226c3e5f058c7761a11e941711ed3b3b7159e8

It would be nice to have a tagged release for 2.0.1. Thank you!

**Comment by aiharos** [comment]
Hi, thank you for the interest!

We're looking to add a couple more fixes before the tag, maybe later this week.

**Comment by mjuraga** [comment]
Here it is: https://github.com/haproxytech/dataplaneapi/releases/tag/v2.0.1
