### ISSUE TITLE
Checksum mismatch with client-native

### ISSUE THREAD

**Issue by SimonSchimmels** [haproxytech/dataplaneapi#9]
Hello, 

when I try to build the dataplaneapi, I get a checksum mismatch:
```
# make 
go get -v
verifying github.com/haproxytech/client-native@v1.0.1: checksum mismatch
	downloaded: h1:uY9KMY5fu/7vcpi2lL3jQ6MgvJsU8e7YgL6AvGeDOLs=
	go.sum:     h1:z07dOpU9Q+1gDc5n8NTjkYu3GFOFWoe3Hf/HSN30AXA=
Makefile:14: recipe for target 'update' failed
make: *** [update] Error 1
```

I am using golang 1.12.6:
```
# go version
go version go1.12.6 linux/amd64
```

Am I missing something or is it possible to solve this?

Kind regards,
Simon

**Comment by mjuraga** [comment]
Fixed with https://github.com/haproxytech/dataplaneapi/commit/abebc085d2b77034e80262caafc50faf9fdcf301
