### ISSUE TITLE
Global: Add support for ssl-default-bind-ciphersuites

### ISSUE THREAD

**Issue by dcorbett-haproxy** [haproxytech/dataplaneapi#92]
Now that the Data Plane API supports both `ssl-default-server-ciphers` and `ssl-default-bind-ciphers`, it would be nice to add support for `ssl-default-bind-ciphersuites` and `ssl-default-server-ciphersuites` as these are part of the recommended settings when generating an intermediate or modern TLS configuration using https://ssl-config.mozilla.org/#server=haproxy&version=2.1&config=modern&openssl=1.1.1d&guideline=5.4

**Comment by mjuraga** [comment]
Added with: https://github.com/haproxytech/dataplaneapi/commit/99e6860b2b9c1776d41e532e2844e9716b5e50f1
