### ISSUE TITLE
Support for http-request Lua actions

### ISSUE THREAD

**Issue by philipcristiano** [haproxytech/dataplaneapi#93]
Is there support for http-request lua actions / could this be added? [Docs](https://www.haproxy.com/documentation/dataplaneapi/latest/#operation/createHTTPRequestRule) mention an enum for various actions, which fails for actions added via Lua scripts (as the `lua.<action_name>` isn't part of the enum). 

Testing this out with an `type=lua.test` I get `type in body should be one of [allow deny auth redirect tarpit add-header replace-header replace-value del-header set-header set-log-level set-path set-query set-uri set-var send-spoe-group add-acl del-acl]` 

I was following https://www.haproxy.com/blog/5-ways-to-extend-haproxy-with-lua/ (under the "Actions" section) and recreating it with the API when running into this problem. 

I was able to get `http-request lua.test` to work with a manually crafted configuration file.

**Comment by mjuraga** [comment]
We can add this feature to the roadmap for the following releases.

**Comment by philipcristiano** [comment]
Wonderful, thanks!

**Comment by rmaticevic** [comment]
@philipcristiano lua actions have been added with the latest patch.

**Comment by philipcristiano** [comment]
Woo! Thanks!
