### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by lz006** [haproxytech/dataplaneapi#94]
Hello Together,
Our haproxy crashes when committing a transaction (via curl). Logs say "bind: address already in use" as you can see:

...
May 08 22:10:26 inst205.novalocal haproxy[10625]: Proxy harbor stopped (FE: 0 conns, BE: 0 conns).
May 08 22:10:26 inst205.novalocal haproxy[10625]: Proxy keycloak stopped (FE: 0 conns, BE: 0 conns).
May 08 22:10:26 inst205.novalocal haproxy[10625]: Proxy plain stopped (FE: 0 conns, BE: 0 conns).
time="2020-05-08T22:10:26Z" level=info msg="HAProxy Data Plane API v2.0.1 01b7b38"
time="2020-05-08T22:10:26Z" level=info msg="Build from: git@github.com:haproxytech/dataplaneapi.git"
time="2020-05-08T22:10:26Z" level=info msg="Build date: 2020-05-08T15:05:52Z"
**time="2020-05-08T22:10:26Z" level=fatal msg="listen tcp 0.0.0.0:5555: bind: address already in use"**
[ALERT] 128/221026 (10623) : Current program 'api' (10652) exited with code 1 (Exit)
[ALERT] 128/221026 (10623) : exit-on-failure: killing every processes with SIGTERM
[ALERT] 128/221026 (10623) : Current worker #1 (10653) exited with code 143 (Terminated)
[WARNING] 128/221026 (10623) : Former program 'api' (10624) exited with code 0 (Exit)
[WARNING] 128/221026 (10623) : Former worker #1 (10625) exited with code 143 (Terminated)
[WARNING] 128/221026 (10623) : All workers exited. Exiting... (1)
May 08 22:10:26 inst205.novalocal systemd[1]: haproxy.service: main process exited, code=exited, status=1/FAILURE
May 08 22:10:26 inst205.novalocal systemd[1]: Unit haproxy.service entered failed state.
May 08 22:10:26 inst205.novalocal systemd[1]: haproxy.service failed.

**But running "systemctl reload/restart haproxy" works fine.**

haproxy.cfg
```
global
  daemon
  user haproxy
  group haproxy
  maxconn 50000
  pidfile /var/run/haproxy.pid
  stats socket /run/haproxy.sock user haproxy group haproxy mode 660 level admin
  log /dev/log local0

defaults
  mode http
  maxconn 3000
  log global
  timeout connect 10s
  timeout client 30s
  timeout server 30s

userlist hapee-dataplaneapi
  user dummy password bla

frontend ltm-web-services
  mode http
  bind :80
  bind :443 ssl crt /etc/haproxy/certs/server.pem
  option forwardfor

  ## ACLs added via dataplane transactions

backend test
  server test_apache 127.0.0.1:8080

program api
  command dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/local/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "systemctl reload haproxy" --reload-delay 5 --userlist hapee-dataplaneapi
```
**Setup**
dataplane release:  v2.0.1
haproxy version: 2.1.4
os: centos7.7
deployment: native (no container)

However it seems that adding **no option start-on-reload** to section "program api" fixes this problem. But according to docs at "https://www.haproxy.com/documentation/hapee/2-1r1/configuration/dataplaneapi/" this option should only be necessary if running it in a docker container.

Do we miss here something?

**Comment by mjuraga** [comment]
No this is needed when the dataplaneapi is run from the program section regardless where it is ran. We'll fix the documentation.
