### ISSUE TITLE
Add support for spaces within the hrd_format value

### ISSUE THREAD

**Issue by ArtForeverUnlimited** [haproxytech/dataplaneapi#97]
*hrd_format in the tile was supposed to be hdr_name*

For example, a proxy auth header requires a space in the add_header rule: 
"Basic YWxhZGRpbjpvcGVuc2VzYW1l"

Currently, this is not possible as the hdr_format regex validator is "^[^\s]+$" and there are no quotes placed around the value in the config.

As a workaround I have had to do something silly like "!!!Basic???YWxhZGRpbjpvcGVuc2VzYW1l!!!" for the hdr_value and then fetch the config and replace !!! with quotes and ??? with space, then re-submit the raw config.

**Comment by mjuraga** [comment]
This indeed is a bug.

**Comment by oktalz** [comment]
hi @ArtForeverUnlimited 
fix for this has been merged in master (https://github.com/haproxytech/dataplaneapi/commit/0f3e49553008b2b6b6cf82754bcd5f6624080920) and will be available in next release
